package model

import (
	"time"

	"github.com/olivertgwalton/photon-server/internal/domain"
)

type Folder struct {
	LibraryID   UUID   `gorm:"type:uuid;primaryKey"`
	Path        string `gorm:"primaryKey"`
	Fingerprint []byte
}

type Item struct {
	ID        UUID `gorm:"type:uuid;default:uuidv7()"`
	LibraryID UUID `gorm:"type:uuid"`
	Kind      domain.ItemKind
	Title     string
	SortTitle string
	Year      *int
	Folder    string
	AddedAt   time.Time `gorm:"default:now()"`

	ParentID      *UUID `gorm:"type:uuid"`
	SeasonNumber  *int
	EpisodeNumber *int
	EpisodeEnd    *int
	AirDate       *time.Time `gorm:"type:date"`
	ExtraKind     *domain.ExtraKind

	ScanTitle     string
	OriginalTitle *string
	Overview      *string
	Tagline       *string
	Certificate   *string
	ReleaseDate   *time.Time `gorm:"type:date"`
	Genres        []string   `gorm:"serializer:json"`
	Studios       []string   `gorm:"serializer:json"`
	// Generated by the database: see the released sort's migration.
	ReleasedAsc  time.Time `gorm:"->;type:date"`
	ReleasedDesc time.Time `gorm:"->;type:date"`
	IdentifiedAt *time.Time
	EpisodeOrder domain.EpisodeOrder `gorm:"default:aired"`
}

// ItemField is where one of a title's fields came from.
type ItemField struct {
	ItemID    UUID         `gorm:"type:uuid;primaryKey"`
	Field     domain.Field `gorm:"primaryKey"`
	Source    domain.FieldSource
	UpdatedAt time.Time `gorm:"default:now()"`
}

// LibrarySource is a source a library takes metadata from; position 0 is the most trusted.
type LibrarySource struct {
	LibraryID UUID               `gorm:"type:uuid;primaryKey"`
	Source    domain.FieldSource `gorm:"primaryKey"`
	Position  int
}

// LibraryRemoteExtra is a kind of video a library keeps providers' links to.
type LibraryRemoteExtra struct {
	LibraryID UUID             `gorm:"type:uuid;primaryKey"`
	Kind      domain.ExtraKind `gorm:"primaryKey"`
}

type RemoteVideo struct {
	ItemID      UUID               `gorm:"type:uuid;primaryKey"`
	Source      domain.FieldSource `gorm:"primaryKey"`
	Position    int                `gorm:"primaryKey"`
	Kind        domain.ExtraKind
	Site        string
	Key         string
	Name        string
	Language    *string
	PublishedAt *time.Time
}

// Artwork is a picture of a title: a file in its library, at place relative to the library's
// root, or a provider's, at place as a URL.
type Artwork struct {
	ID       UUID               `gorm:"type:uuid;default:uuidv7()"`
	ItemID   UUID               `gorm:"type:uuid;primaryKey"`
	Source   domain.FieldSource `gorm:"primaryKey"`
	Kind     domain.ArtworkKind `gorm:"primaryKey"`
	Place    string             `gorm:"primaryKey"`
	Position int
	Folder   *string
	Language *string
	Width    *int
	Height   *int
}

func (Artwork) TableName() string { return "artwork" }

// WatchState is what a profile has made of a film or episode.
type WatchState struct {
	ProfileID    UUID  `gorm:"type:uuid;primaryKey"`
	ItemID       UUID  `gorm:"type:uuid;primaryKey"`
	PositionMS   int64 `gorm:"column:position_ms"`
	Plays        int
	WatchedAt    *time.Time
	LastPlayedAt *time.Time
}

func (WatchState) TableName() string { return "watch_state" }

type Favourite struct {
	ProfileID UUID      `gorm:"type:uuid;primaryKey"`
	ItemID    UUID      `gorm:"type:uuid;primaryKey"`
	AddedAt   time.Time `gorm:"default:now()"`
}

type ExternalID struct {
	ItemID   UUID            `gorm:"type:uuid;primaryKey"`
	Provider domain.Provider `gorm:"primaryKey"`
	Value    string
	Source   domain.IDSource
}

type Version struct {
	ID           UUID `gorm:"type:uuid;default:uuidv7()"`
	ItemID       UUID `gorm:"type:uuid"`
	LibraryID    UUID `gorm:"type:uuid"`
	Fingerprint  []byte
	Edition      *string
	Label        *string
	Container    string
	Width        *int
	Height       *int
	VideoCodec   *string
	VideoRange   *domain.Range
	DVProfile    *int16 `gorm:"column:dv_profile"`
	BitrateKbps  int
	SizeBytes    int64
	DurationMS   int64 `gorm:"column:duration_ms"`
	MissingSince *time.Time
}

type Part struct {
	ID         UUID `gorm:"type:uuid;default:uuidv7()"`
	VersionID  UUID `gorm:"type:uuid"`
	Idx        int16
	SizeBytes  int64
	DurationMS int64 `gorm:"column:duration_ms"`
	OffsetMS   int64 `gorm:"column:offset_ms"`
	// FingerprintedAt is when the part's sound was last compared with its season's.
	FingerprintedAt *time.Time
}

// PartFile is one place a part's bytes are on disk.
type PartFile struct {
	PartID    UUID   `gorm:"type:uuid"`
	LibraryID UUID   `gorm:"type:uuid;primaryKey"`
	RelPath   string `gorm:"primaryKey"`
	SizeBytes int64
	MtimeNS   int64 `gorm:"column:mtime_ns"`
}

type Stream struct {
	PartID          UUID `gorm:"type:uuid;primaryKey"`
	Idx             int  `gorm:"primaryKey"`
	Kind            domain.StreamKind
	Codec           string
	Profile         *string
	Language        *string
	Title           *string
	IsDefault       bool
	Forced          bool
	HearingImpaired bool
	Commentary      bool
	Width           *int
	Height          *int
	FrameRate       *float64
	BitDepth        *int16
	Level           *int
	VideoRange      *domain.Range
	DVProfile       *int16 `gorm:"column:dv_profile"`
	DVLevel         *int16 `gorm:"column:dv_level"`
	DVCompatibility *int16 `gorm:"column:dv_compatibility"`
	Channels        *int
	ChannelLayout   *string
	SampleRate      *int
	BitrateKbps     *int
}

type Chapter struct {
	PartID  UUID  `gorm:"type:uuid;primaryKey"`
	Idx     int   `gorm:"primaryKey"`
	StartMS int64 `gorm:"column:start_ms"`
	EndMS   int64 `gorm:"column:end_ms"`
	Title   *string
}

// Marker is a stretch of a part a player may offer to skip, from the part's start.
type Marker struct {
	PartID UUID                `gorm:"type:uuid;primaryKey"`
	Kind   domain.MarkerKind   `gorm:"primaryKey"`
	Source domain.MarkerSource `gorm:"primaryKey"`
	// StartMS and EndMS are absent where an admin said the part has none of the kind.
	StartMS *int64 `gorm:"column:start_ms"`
	EndMS   *int64 `gorm:"column:end_ms"`
}

// SubtitleFile is a subtitle beside a copy rather than inside it.
type SubtitleFile struct {
	ID              UUID   `gorm:"type:uuid;default:uuidv7()"`
	VersionID       UUID   `gorm:"type:uuid"`
	LibraryID       UUID   `gorm:"type:uuid;primaryKey"`
	RelPath         string `gorm:"primaryKey"`
	Codec           string
	Language        *string
	Title           *string
	Forced          bool
	IsDefault       bool
	HearingImpaired bool
	SizeBytes       int64
	MtimeNS         int64 `gorm:"column:mtime_ns"`
}

type Rating struct {
	ItemID UUID               `gorm:"type:uuid;primaryKey"`
	Source domain.FieldSource `gorm:"primaryKey"`
	Site   domain.RatingSite  `gorm:"primaryKey"`
	Score  float32
	Votes  *int
}

type Provider struct {
	ID       string `gorm:"primaryKey"`
	Settings []byte `gorm:"type:jsonb"`
}

type Plugin struct {
	Slug     string `gorm:"primaryKey"`
	URL      string
	Manifest []byte `gorm:"type:jsonb"`
}

type Collection struct {
	ItemID UUID `gorm:"type:uuid;primaryKey"`
	Origin domain.CollectionOrigin
}

type CollectionMember struct {
	CollectionID UUID `gorm:"type:uuid;primaryKey"`
	ItemID       UUID `gorm:"type:uuid;primaryKey"`
	Position     int
}

type Playlist struct {
	ID        UUID `gorm:"type:uuid;default:uuidv7()"`
	ProfileID UUID `gorm:"type:uuid"`
	Name      string
	UpdatedAt time.Time `gorm:"default:now()"`
}

type PlaylistEntry struct {
	ID         UUID `gorm:"type:uuid;default:uuidv7()"`
	PlaylistID UUID `gorm:"type:uuid"`
	ItemID     UUID `gorm:"type:uuid"`
	Position   int
}

type Person struct {
	ID          UUID `gorm:"type:uuid;default:uuidv7()"`
	Name        string
	PhotoURL    *string
	PhotoID     *UUID `gorm:"type:uuid"`
	Biography   *string
	Born        *time.Time `gorm:"type:date"`
	Died        *time.Time `gorm:"type:date"`
	Birthplace  *string
	DescribedAt *time.Time
}

func (Person) TableName() string { return "people" }

type PersonExternalID struct {
	PersonID UUID            `gorm:"type:uuid"`
	Provider domain.Provider `gorm:"primaryKey"`
	Value    string          `gorm:"primaryKey"`
}

func (PersonExternalID) TableName() string { return "person_ids" }

type Credit struct {
	ItemID   UUID               `gorm:"type:uuid;primaryKey"`
	PersonID UUID               `gorm:"type:uuid;primaryKey"`
	Source   domain.FieldSource `gorm:"primaryKey"`
	Kind     domain.CreditKind  `gorm:"primaryKey"`
	Role     string             `gorm:"primaryKey"`
	Position int
}
