-- +goose Up
-- Each country's certificates and the age each is for, from Jellyfin's rating files
-- (Emby.Server.Implementations/Localization/Ratings); 1000 and over are adults-only and banned.
-- 0-PREFER is Jellyfin's own, tried before any country's.
CREATE TABLE certificates (
  country text NOT NULL,
  rating text NOT NULL,
  age smallint NOT NULL,
  PRIMARY KEY (country, rating)
);
INSERT INTO certificates (country, rating, age) VALUES
  ('0-PREFER', 'AO', 18),
  ('0-PREFER', 'E', 0),
  ('0-PREFER', 'EC', 0),
  ('0-PREFER', 'M', 18),
  ('0-PREFER', 'P', 1000),
  ('0-PREFER', 'RP', 18),
  ('0-PREFER', 'T', 7),
  ('0-PREFER', 'UR', 18),
  ('0-PREFER', 'X', 1000),
  ('0-PREFER', 'XX', 1000),
  ('0-PREFER', 'XXX', 1000),
  ('0-PREFER', 'XXXX', 1000),
  ('AR', '+13', 13),
  ('AR', '+16', 16),
  ('AR', '+18', 18),
  ('AR', '+18 C', 1001),
  ('AR', 'APTA PARA TODO PÚBLICO', 0),
  ('AR', 'ATP', 0),
  ('AR', 'C', 1001),
  ('AR', 'G', 0),
  ('AR', 'R-13', 13),
  ('AR', 'R-17', 17),
  ('AR', 'SAM 13', 13),
  ('AR', 'SAM 16', 16),
  ('AR', 'SAM 18', 18),
  ('AR', 'SAM 18 C', 1001),
  ('AR', 'SAM 18C', 1001),
  ('AR', 'SAM13', 13),
  ('AR', 'SAM16', 16),
  ('AR', 'SAM18', 18),
  ('AR', 'SAM18C', 1001),
  ('AR', 'SP', 10),
  ('AU', '16+', 16),
  ('AU', '18+', 18),
  ('AU', '7+', 7),
  ('AU', 'EXEMPT', 0),
  ('AU', 'G', 0),
  ('AU', 'M', 15),
  ('AU', 'MA', 15),
  ('AU', 'MA 15+', 15),
  ('AU', 'MA15+', 15),
  ('AU', 'PG', 15),
  ('AU', 'R', 18),
  ('AU', 'R 18+', 18),
  ('AU', 'R18+', 18),
  ('AU', 'RC', 1001),
  ('AU', 'X', 1000),
  ('AU', 'X 18', 1000),
  ('AU', 'X 18+', 1000),
  ('AU', 'X18', 1000),
  ('AU', 'X18+', 1000),
  ('BE', '12', 12),
  ('BE', '14', 14),
  ('BE', '16', 16),
  ('BE', '18', 18),
  ('BE', '6', 6),
  ('BE', '9', 9),
  ('BE', 'AL', 0),
  ('BE', 'KNT', 12),
  ('BE', 'KT', 0),
  ('BE', 'MG6', 6),
  ('BE', 'TOUS', 0),
  ('BG', 'A', 0),
  ('BG', 'B', 0),
  ('BG', 'C', 12),
  ('BG', 'D', 16),
  ('BG', 'X', 18),
  ('BR', '10', 10),
  ('BR', '12', 12),
  ('BR', '14', 14),
  ('BR', '16', 16),
  ('BR', '18', 18),
  ('BR', '9', 9),
  ('BR', 'A10', 10),
  ('BR', 'A12', 12),
  ('BR', 'A14', 14),
  ('BR', 'A16', 16),
  ('BR', 'A18', 18),
  ('BR', 'AL', 0),
  ('BR', 'ER', 10),
  ('BR', 'L', 0),
  ('BR', 'LIVRE', 0),
  ('CA', '14+', 14),
  ('CA', '14A', 14),
  ('CA', '16+', 16),
  ('CA', '18+', 18),
  ('CA', '18A', 18),
  ('CA', 'A', 1000),
  ('CA', 'C', 0),
  ('CA', 'C8', 8),
  ('CA', 'E', 0),
  ('CA', 'G', 0),
  ('CA', 'NC-17', 17),
  ('CA', 'PG', 8),
  ('CA', 'PROHIBITED', 1001),
  ('CA', 'R', 18),
  ('CA', 'TV-14', 14),
  ('CA', 'TV-G', 0),
  ('CA', 'TV-MA', 18),
  ('CA', 'TV-PG', 8),
  ('CA', 'TV-Y', 0),
  ('CA', 'TV-Y7', 7),
  ('CA', 'TV-Y7-FV', 7),
  ('CL', '14', 14),
  ('CL', '18', 18),
  ('CL', '18S', 18),
  ('CL', '18V', 18),
  ('CL', '6', 6),
  ('CL', 'TE', 0),
  ('CL', 'TE+7', 7),
  ('CO', '12', 12),
  ('CO', '15', 15),
  ('CO', '18', 18),
  ('CO', '7', 7),
  ('CO', 'PROHIBITED', 1001),
  ('CO', 'T', 0),
  ('CO', 'X', 1000),
  ('CZ', '12+', 12),
  ('CZ', '15+', 15),
  ('CZ', '18+', 18),
  ('CZ', 'U', 0),
  ('DE', '0', 0),
  ('DE', '12', 12),
  ('DE', '16', 16),
  ('DE', '18', 18),
  ('DE', '6', 6),
  ('DE', 'AB 0', 0),
  ('DE', 'AB 12', 12),
  ('DE', 'AB 16', 16),
  ('DE', 'AB 18', 18),
  ('DE', 'AB 6', 6),
  ('DE', 'EDUCATIONAL', 0),
  ('DE', 'FSK 0', 0),
  ('DE', 'FSK 12', 12),
  ('DE', 'FSK 16', 16),
  ('DE', 'FSK 18', 18),
  ('DE', 'FSK 6', 6),
  ('DE', 'FSK-0', 0),
  ('DE', 'FSK-12', 12),
  ('DE', 'FSK-16', 16),
  ('DE', 'FSK-18', 18),
  ('DE', 'FSK-6', 6),
  ('DE', 'FSK0', 0),
  ('DE', 'FSK12', 12),
  ('DE', 'FSK16', 16),
  ('DE', 'FSK18', 18),
  ('DE', 'FSK6', 6),
  ('DE', 'INFOPROGRAMM', 0),
  ('DK', '11', 11),
  ('DK', '12', 12),
  ('DK', '15', 15),
  ('DK', '16', 16),
  ('DK', '7', 7),
  ('DK', 'A', 0),
  ('DK', 'F', 0),
  ('ES', '0+', 0),
  ('ES', '10', 10),
  ('ES', '12', 12),
  ('ES', '12/FIG', 12),
  ('ES', '13', 13),
  ('ES', '14', 14),
  ('ES', '16', 16),
  ('ES', '16/FIG', 16),
  ('ES', '18', 18),
  ('ES', '18/FIG', 18),
  ('ES', '6+', 6),
  ('ES', '7', 11),
  ('ES', '7/FIG', 11),
  ('ES', '7/I', 11),
  ('ES', '7/I/FIG', 11),
  ('ES', '7I', 11),
  ('ES', '9+', 9),
  ('ES', 'A', 0),
  ('ES', 'A/FIG', 0),
  ('ES', 'A/I', 0),
  ('ES', 'A/I/FIG', 0),
  ('ES', 'AI', 0),
  ('ES', 'APTA', 0),
  ('ES', 'BANNED', 1001),
  ('ES', 'ERI', 0),
  ('ES', 'TP', 0),
  ('ES', 'X', 1000),
  ('FI', '12', 12),
  ('FI', '16', 16),
  ('FI', '18', 18),
  ('FI', '7', 7),
  ('FI', 'K-12', 12),
  ('FI', 'K-16', 16),
  ('FI', 'K-18', 18),
  ('FI', 'K-7', 7),
  ('FI', 'K12', 12),
  ('FI', 'K16', 16),
  ('FI', 'K18', 18),
  ('FI', 'K7', 7),
  ('FI', 'KK', 1001),
  ('FI', 'S', 0),
  ('FI', 'T', 0),
  ('FR', '0+', 0),
  ('FR', '10', 10),
  ('FR', '12', 12),
  ('FR', '14+', 14),
  ('FR', '16', 16),
  ('FR', '18', 18),
  ('FR', '6+', 6),
  ('FR', '9+', 9),
  ('FR', 'INTERDIT AUX MOINS DE 10 ANS', 10),
  ('FR', 'INTERDIT AUX MOINS DE 12 ANS', 12),
  ('FR', 'INTERDIT AUX MOINS DE 16 ANS', 16),
  ('FR', 'INTERDIT AUX MOINS DE 18 ANS', 18),
  ('FR', 'PUBLIC AVERTI', 0),
  ('FR', 'TOUS PUBLICS', 0),
  ('FR', 'TP', 0),
  ('FR', 'U', 0),
  ('FR', 'X', 1000),
  ('FR', '–12', 12),
  ('FR', '–16', 16),
  ('FR', '–18', 18),
  ('GB', '0+', 0),
  ('GB', '12', 12),
  ('GB', '12+', 12),
  ('GB', '12A', 12),
  ('GB', '12PG', 12),
  ('GB', '13+', 13),
  ('GB', '14+', 14),
  ('GB', '15', 15),
  ('GB', '16', 16),
  ('GB', '18', 18),
  ('GB', '6+', 6),
  ('GB', '7+', 7),
  ('GB', '9', 9),
  ('GB', 'ADULT', 1000),
  ('GB', 'ALL', 0),
  ('GB', 'CAUTION', 18),
  ('GB', 'E', 0),
  ('GB', 'G', 0),
  ('GB', 'MATURE', 1000),
  ('GB', 'PG', 8),
  ('GB', 'R18', 1000),
  ('GB', 'TEEN', 13),
  ('GB', 'U', 0),
  ('GR', '12', 12),
  ('GR', '13', 13),
  ('GR', '15', 15),
  ('GR', '16', 16),
  ('GR', '17', 17),
  ('GR', '18', 18),
  ('GR', '18+', 18),
  ('GR', 'K', 0),
  ('GR', 'K-12', 12),
  ('GR', 'K-13', 13),
  ('GR', 'K-15', 15),
  ('GR', 'K-16', 16),
  ('GR', 'K-17', 17),
  ('GR', 'K-18', 18),
  ('GR', 'K12', 12),
  ('GR', 'K13', 13),
  ('GR', 'K15', 15),
  ('GR', 'K16', 16),
  ('GR', 'K17', 17),
  ('GR', 'K18', 18),
  ('HU', '12', 12),
  ('HU', '16', 16),
  ('HU', '18', 18),
  ('HU', '6', 6),
  ('HU', 'KN', 0),
  ('HU', 'X', 18),
  ('ID', '13+', 13),
  ('ID', '17+', 17),
  ('ID', '21+', 21),
  ('ID', 'A', 7),
  ('ID', 'A-BO', 7),
  ('ID', 'A7+', 7),
  ('ID', 'ANAK', 7),
  ('ID', 'D', 18),
  ('ID', 'D18+', 18),
  ('ID', 'DEWASA', 18),
  ('ID', 'P', 2),
  ('ID', 'P-BO', 2),
  ('ID', 'P2+', 2),
  ('ID', 'PRASEKOLAH', 2),
  ('ID', 'R', 13),
  ('ID', 'R-BO', 13),
  ('ID', 'R13+', 13),
  ('ID', 'REMAJA', 13),
  ('ID', 'SEMUA UMUR', 0),
  ('ID', 'SU', 0),
  ('ID', 'SU-BO', 0),
  ('IE', '12', 12),
  ('IE', '12A', 12),
  ('IE', '12PG', 12),
  ('IE', '15', 15),
  ('IE', '15A', 15),
  ('IE', '15PG', 15),
  ('IE', '16', 16),
  ('IE', '18', 18),
  ('IE', 'G', 4),
  ('IE', 'PG', 12),
  ('IN', 'A', 18),
  ('IN', 'S', 1001),
  ('IN', 'U', 0),
  ('IN', 'U/A 13+', 13),
  ('IN', 'U/A 16+', 16),
  ('IN', 'U/A 7+', 7),
  ('IN', 'UA', 12),
  ('IT', '10+', 10),
  ('IT', '12+', 12),
  ('IT', '14+', 14),
  ('IT', '18+', 18),
  ('IT', '6+', 6),
  ('IT', 'PER TUTTI', 0),
  ('IT', 'PT', 0),
  ('IT', 'T', 0),
  ('IT', 'VIETATO AI MINORI DI 10 ANNI', 10),
  ('IT', 'VIETATO AI MINORI DI 12 ANNI', 12),
  ('IT', 'VIETATO AI MINORI DI 14 ANNI', 14),
  ('IT', 'VIETATO AI MINORI DI 18 ANNI', 18),
  ('IT', 'VIETATO AI MINORI DI 6 ANNI', 6),
  ('IT', 'VM 10', 10),
  ('IT', 'VM 12', 12),
  ('IT', 'VM 14', 14),
  ('IT', 'VM 18', 18),
  ('IT', 'VM 6', 6),
  ('IT', 'VM-10', 10),
  ('IT', 'VM-12', 12),
  ('IT', 'VM-14', 14),
  ('IT', 'VM-18', 18),
  ('IT', 'VM-6', 6),
  ('IT', 'VM10', 10),
  ('IT', 'VM12', 12),
  ('IT', 'VM14', 14),
  ('IT', 'VM18', 18),
  ('IT', 'VM6', 6),
  ('JP', '15+', 15),
  ('JP', '15A', 15),
  ('JP', '15PG', 15),
  ('JP', '16+', 16),
  ('JP', '18+', 18),
  ('JP', 'A', 0),
  ('JP', 'B', 12),
  ('JP', 'C', 15),
  ('JP', 'D', 17),
  ('JP', 'G', 0),
  ('JP', 'PG12', 12),
  ('JP', 'R15+', 15),
  ('JP', 'Z', 18),
  ('KR', '12', 12),
  ('KR', '15', 15),
  ('KR', '19', 19),
  ('KR', 'ALL', 0),
  ('KR', 'RESTRICTED SCREENING', 1001),
  ('KZ', 'E16', 16),
  ('KZ', 'E18', 18),
  ('KZ', 'HA', 18),
  ('KZ', 'K', 0),
  ('KZ', 'Б14', 14),
  ('KZ', 'БА', 12),
  ('LT', 'N-13', 13),
  ('LT', 'N-16', 16),
  ('LT', 'N-18', 18),
  ('LT', 'N-7', 7),
  ('LT', 'V', 0),
  ('MX', 'A', 0),
  ('MX', 'AA', 0),
  ('MX', 'B', 12),
  ('MX', 'B-15', 15),
  ('MX', 'C', 18),
  ('MX', 'D', 1000),
  ('NL', '12', 12),
  ('NL', '14', 14),
  ('NL', '16', 16),
  ('NL', '18', 18),
  ('NL', '6', 6),
  ('NL', '9', 9),
  ('NL', 'AL', 0),
  ('NL', 'MG6', 6),
  ('NO', '11', 11),
  ('NO', '11 ÅR', 11),
  ('NO', '12', 12),
  ('NO', '12 ÅR', 12),
  ('NO', '15', 15),
  ('NO', '15 ÅR', 15),
  ('NO', '18', 18),
  ('NO', '18 ÅR', 18),
  ('NO', '6', 6),
  ('NO', '6 ÅR', 6),
  ('NO', '7', 7),
  ('NO', '7 ÅR', 7),
  ('NO', '9', 9),
  ('NO', '9 ÅR', 9),
  ('NO', 'A', 0),
  ('NO', 'NOT APPROVED', 1001),
  ('NZ', 'EXEMPT', 0),
  ('NZ', 'G', 0),
  ('NZ', 'GA', 18),
  ('NZ', 'GY', 13),
  ('NZ', 'M', 16),
  ('NZ', 'MA', 1000),
  ('NZ', 'OBJECTIONABLE', 1001),
  ('NZ', 'PG', 13),
  ('NZ', 'R', 1001),
  ('NZ', 'R13', 13),
  ('NZ', 'R15', 15),
  ('NZ', 'R16', 16),
  ('NZ', 'R18', 18),
  ('NZ', 'RP13', 13),
  ('NZ', 'RP16', 16),
  ('NZ', 'RP18', 18),
  ('PH', 'G', 0),
  ('PH', 'PG', 13),
  ('PH', 'R-13', 13),
  ('PH', 'R-16', 16),
  ('PH', 'R-18', 18),
  ('PH', 'X', 1001),
  ('PL', '12', 12),
  ('PL', '16', 16),
  ('PL', '18', 18),
  ('PL', '7', 7),
  ('PL', 'AL', 0),
  ('PL', 'B.O.', 0),
  ('PL', 'OD 12 LAT', 12),
  ('PL', 'OD 16 LAT', 16),
  ('PL', 'OD 18 LAT', 18),
  ('PL', 'OD 7 LAT', 7),
  ('PL', 'R', 18),
  ('PT', 'M/12', 12),
  ('PT', 'M/14', 14),
  ('PT', 'M/16', 16),
  ('PT', 'M/18', 18),
  ('PT', 'M/3', 3),
  ('PT', 'M/6', 6),
  ('PT', 'P', 1000),
  ('PT', 'PÚBLICOS', 0),
  ('RO', '12', 12),
  ('RO', '15', 15),
  ('RO', '18', 18),
  ('RO', '18+', 1000),
  ('RO', 'AG', 0),
  ('RO', 'AP', 0),
  ('RO', 'AP-12', 12),
  ('RO', 'IC', 1001),
  ('RO', 'IM-18', 18),
  ('RO', 'IM-18-XXX', 1000),
  ('RO', 'N-15', 15),
  ('RU', '0+', 0),
  ('RU', '12+', 12),
  ('RU', '16+', 16),
  ('RU', '18+', 18),
  ('RU', '6+', 6),
  ('RU', 'REFUSED CLASSIFICATION', 1001),
  ('SE', '0+', 0),
  ('SE', '10+', 10),
  ('SE', '11', 11),
  ('SE', '11 ÅR', 11),
  ('SE', '11+', 11),
  ('SE', '14', 14),
  ('SE', '15', 15),
  ('SE', '15 ÅR', 15),
  ('SE', '15+', 15),
  ('SE', '18', 18),
  ('SE', '18+', 18),
  ('SE', '7', 7),
  ('SE', '7 ÅR', 7),
  ('SE', '7+', 7),
  ('SE', '9+', 9),
  ('SE', 'ALLA', 0),
  ('SE', 'BARNFÖRBJUDEN', 18),
  ('SE', 'BARNTILLÅTEN', 0),
  ('SE', 'BFJ', 18),
  ('SE', 'BTL', 0),
  ('SE', 'FRÅN 11 ÅR', 11),
  ('SE', 'FRÅN 15 ÅR', 15),
  ('SE', 'FRÅN 7 ÅR', 7),
  ('SG', 'G', 0),
  ('SG', 'M18', 18),
  ('SG', 'NC16', 16),
  ('SG', 'PG', 7),
  ('SG', 'PG13', 13),
  ('SG', 'R21', 21),
  ('SK', '12', 12),
  ('SK', '15', 15),
  ('SK', '18', 18),
  ('SK', '7', 7),
  ('SK', 'NR', 0),
  ('SK', 'U', 0),
  ('TH', '13', 13),
  ('TH', '15', 15),
  ('TH', '18+', 18),
  ('TH', '20', 20),
  ('TH', 'BANNED', 1001),
  ('TH', 'G', 0),
  ('TH', 'P', 0),
  ('TR', '10+', 10),
  ('TR', '10A', 10),
  ('TR', '13+', 13),
  ('TR', '13A', 13),
  ('TR', '16+', 16),
  ('TR', '18+', 18),
  ('TR', '6+', 6),
  ('TR', '6A', 6),
  ('TR', 'GENEL İZLEYICI KITLESI', 0),
  ('TW', '0+', 0),
  ('TW', '12+', 12),
  ('TW', '15+', 15),
  ('TW', '18+', 18),
  ('TW', '6+', 6),
  ('TW', '保護級', 6),
  ('TW', '普', 0),
  ('TW', '普遍級', 0),
  ('TW', '護', 6),
  ('TW', '輔12級', 12),
  ('TW', '輔15級', 15),
  ('TW', '輔導12歲級', 12),
  ('TW', '輔導15歲級', 15),
  ('TW', '輔導級', 12),
  ('TW', '限', 18),
  ('TW', '限制級', 18),
  ('UA', '0+', 0),
  ('UA', '12+', 12),
  ('UA', '16+', 16),
  ('UA', '18+', 18),
  ('US', 'APPROVED', 0),
  ('US', 'G', 0),
  ('US', 'NC-17', 17),
  ('US', 'PG', 10),
  ('US', 'PG-13', 13),
  ('US', 'R', 17),
  ('US', 'TV-14', 14),
  ('US', 'TV-14-D', 14),
  ('US', 'TV-14-DL', 14),
  ('US', 'TV-14-DLS', 14),
  ('US', 'TV-14-DLSV', 14),
  ('US', 'TV-14-DLV', 14),
  ('US', 'TV-14-DS', 14),
  ('US', 'TV-14-DSV', 14),
  ('US', 'TV-14-DV', 14),
  ('US', 'TV-14-L', 14),
  ('US', 'TV-14-LS', 14),
  ('US', 'TV-14-LSV', 14),
  ('US', 'TV-14-LV', 14),
  ('US', 'TV-14-S', 14),
  ('US', 'TV-14-SV', 14),
  ('US', 'TV-14-V', 14),
  ('US', 'TV-AO', 18),
  ('US', 'TV-G', 0),
  ('US', 'TV-MA', 17),
  ('US', 'TV-MA-L', 17),
  ('US', 'TV-MA-LS', 17),
  ('US', 'TV-MA-LSV', 17),
  ('US', 'TV-MA-LV', 17),
  ('US', 'TV-MA-S', 17),
  ('US', 'TV-MA-SV', 17),
  ('US', 'TV-MA-V', 17),
  ('US', 'TV-PG', 10),
  ('US', 'TV-PG-D', 10),
  ('US', 'TV-PG-DL', 10),
  ('US', 'TV-PG-DLS', 10),
  ('US', 'TV-PG-DLSV', 10),
  ('US', 'TV-PG-DLV', 10),
  ('US', 'TV-PG-DS', 10),
  ('US', 'TV-PG-DSV', 10),
  ('US', 'TV-PG-DV', 10),
  ('US', 'TV-PG-L', 10),
  ('US', 'TV-PG-LS', 10),
  ('US', 'TV-PG-LSV', 10),
  ('US', 'TV-PG-LV', 10),
  ('US', 'TV-PG-S', 10),
  ('US', 'TV-PG-SV', 10),
  ('US', 'TV-PG-V', 10),
  ('US', 'TV-X', 18),
  ('US', 'TV-Y', 0),
  ('US', 'TV-Y7', 7),
  ('US', 'TV-Y7-FV', 7),
  ('ZA', '10-12PG', 10),
  ('ZA', '13', 13),
  ('ZA', '16', 16),
  ('ZA', '18', 18),
  ('ZA', '7-9PG', 7),
  ('ZA', 'A', 0),
  ('ZA', 'PG', 7),
  ('ZA', 'X18', 1001),
  ('ZA', 'XX', 1001);

-- The country certificates are fetched in, which a bare one such as India's A is read in.
ALTER TABLE server ADD COLUMN certificate_country text;

DROP FUNCTION visible(uuid, uuid);
DROP FUNCTION certificate_age(text);

-- +goose StatementBegin
-- The age one certificate is for, as Jellyfin's GetSingleRatingScore reads it: a plain age (16,
-- 18+, France's -12), else the certificate in the country's system, also written with that
-- country before it (GB:15), else the US's, else any country's; else, written COUNTRY:RATING or
-- COUNTRY-RATING, the rating in that country's. NULL is unrated.
CREATE FUNCTION certificate_score(c text, country text) RETURNS smallint LANGUAGE plpgsql STABLE PARALLEL SAFE AS $$
DECLARE
  r text := upper(trim(regexp_replace(c, '^\s*rated\s*:?\s*', '', 'i')));
  cc text := upper(country);
  found smallint;
  sep text;
  head text;
  tail text;
BEGIN
  IF r IN ('', 'N/A', 'UNRATED', 'NOT RATED', 'NR') THEN
    RETURN NULL;
  END IF;
  IF r ~ '^-?\d{1,4}\+?$' THEN
    RETURN btrim(r, '+-')::smallint;
  END IF;
  SELECT a.age INTO found FROM certificates a
  WHERE a.rating = r OR (a.country = cc AND regexp_replace(r, '^' || cc || '\s*[:-]\s*', '') = a.rating)
  ORDER BY a.country = cc DESC, a.country = 'US' DESC, a.country
  LIMIT 1;
  IF found IS NOT NULL OR position('/' IN r) > 0 THEN
    RETURN found;
  END IF;
  FOREACH sep IN ARRAY ARRAY[':', '-'] LOOP
    head := trim(split_part(r, sep, 1));
    tail := trim(substr(r, position(sep IN r) + 1));
    IF position(sep IN r) > 0 AND tail <> '' AND EXISTS (SELECT 1 FROM certificates WHERE certificates.country = head) THEN
      SELECT a.age INTO found FROM certificates a WHERE a.country = head AND a.rating = tail;
      RETURN coalesce(found, certificate_score(tail, head));
    END IF;
  END LOOP;
  RETURN NULL;
END $$;
-- +goose StatementEnd

-- +goose StatementBegin
-- The age a certificate is for: the whole of it, else the first of a list (SE:15 / SE:15+) that
-- reads, as Jellyfin's GetRatingScore.
CREATE FUNCTION certificate_age(c text) RETURNS smallint LANGUAGE plpgsql STABLE PARALLEL SAFE AS $$
DECLARE
  country text := (SELECT certificate_country FROM server);
  found smallint := certificate_score(c, country);
  entry text;
BEGIN
  IF found IS NOT NULL OR upper(trim(c)) = 'N/A' THEN
    RETURN found;
  END IF;
  FOREACH entry IN ARRAY string_to_array(c, '/') LOOP
    found := certificate_score(entry, country);
    IF found IS NOT NULL THEN
      RETURN found;
    END IF;
  END LOOP;
  RETURN NULL;
END $$;
-- +goose StatementEnd

-- Whether a profile may see a title: it is in a library the profile has, and every certificate
-- from it up to the film or show it belongs to is within the profile's age, so an episode's own
-- is honoured beside its show's; with none on the way up it is unrated. A collection is seen as
-- its library.
CREATE FUNCTION visible(item uuid, profile uuid) RETURNS boolean LANGUAGE sql STABLE PARALLEL SAFE RETURN (
  WITH RECURSIVE up AS (
    SELECT i.id, i.parent_id, i.kind, i.certificate, i.library_id FROM items i WHERE i.id = item
    UNION ALL
    SELECT p.id, p.parent_id, p.kind, p.certificate, p.library_id FROM items p JOIN up ON p.id = up.parent_id
  ),
  top AS (SELECT * FROM up WHERE parent_id IS NULL),
  me AS (SELECT * FROM profiles WHERE id = profile)
  SELECT
    (NOT EXISTS (SELECT 1 FROM profile_libraries l WHERE l.profile_id = profile)
      OR EXISTS (SELECT 1 FROM profile_libraries l, top WHERE l.profile_id = profile AND l.library_id = top.library_id))
    AND (me.max_age IS NULL OR top.kind = 'collection'
      OR coalesce(
        (SELECT bool_and(coalesce(certificate_age(up.certificate) <= me.max_age, me.unrated = 'allow')) FROM up WHERE up.certificate IS NOT NULL),
        me.unrated = 'allow'))
  -- No profile at all (the server itself asking) sees everything.
  FROM top LEFT JOIN me ON true
);

-- +goose Down
DROP FUNCTION visible(uuid, uuid);
DROP FUNCTION certificate_age(text);
DROP FUNCTION certificate_score(text, text);
ALTER TABLE server DROP COLUMN certificate_country;
DROP TABLE certificates;

-- The youngest age a certificate is for, across the systems providers give: the BBFC's, the
-- MPA's, the US TV guidelines, and the plain ages most countries use (FSK 12, 16+). NULL is a
-- certificate no system here knows: unrated.
CREATE FUNCTION certificate_age(c text) RETURNS smallint LANGUAGE sql IMMUTABLE PARALLEL SAFE RETURN
  CASE
    WHEN upper(trim(c)) IN ('G', 'U', 'UC', 'E', 'AL', 'TP', 'TV-Y', 'TV-G', 'ALL') THEN 0
    WHEN upper(trim(c)) IN ('TV-Y7', 'TV-Y7-FV') THEN 7
    WHEN upper(trim(c)) IN ('PG', 'TV-PG') THEN 10
    WHEN upper(trim(c)) IN ('12A', 'PG-12') THEN 12
    WHEN upper(trim(c)) IN ('PG-13') THEN 13
    WHEN upper(trim(c)) IN ('TV-14') THEN 14
    WHEN upper(trim(c)) IN ('M', 'MA15+') THEN 15
    WHEN upper(trim(c)) IN ('R', 'TV-MA') THEN 17
    WHEN upper(trim(c)) IN ('NC-17', 'R18', 'R18+', 'X', 'XXX') THEN 18
    WHEN regexp_replace(c, '\D', '', 'g') ~ '^\d{1,2}$' THEN regexp_replace(c, '\D', '', 'g')::smallint
  END;

-- Whether a profile may see a title: it is in a library the profile has, and it, or the film or
-- show it belongs to, is rated within the profile's age. A collection is seen as its library.
CREATE FUNCTION visible(item uuid, profile uuid) RETURNS boolean LANGUAGE sql STABLE PARALLEL SAFE RETURN (
  WITH RECURSIVE up AS (
    SELECT i.id, i.parent_id, i.kind, i.certificate, i.library_id FROM items i WHERE i.id = item
    UNION ALL
    SELECT p.id, p.parent_id, p.kind, p.certificate, p.library_id FROM items p JOIN up ON p.id = up.parent_id
  ),
  top AS (SELECT * FROM up WHERE parent_id IS NULL),
  me AS (SELECT * FROM profiles WHERE id = profile)
  SELECT
    (NOT EXISTS (SELECT 1 FROM profile_libraries l WHERE l.profile_id = profile)
      OR EXISTS (SELECT 1 FROM profile_libraries l, top WHERE l.profile_id = profile AND l.library_id = top.library_id))
    AND (me.max_age IS NULL OR top.kind = 'collection'
      OR coalesce(certificate_age(top.certificate) <= me.max_age, me.unrated = 'allow'))
  -- No profile at all (the server itself asking) sees everything.
  FROM top LEFT JOIN me ON true
);
