// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newArtwork(db *gorm.DB, opts ...gen.DOOption) artwork {
	_artwork := artwork{}

	_artwork.artworkDo.UseDB(db, opts...)
	_artwork.artworkDo.UseModel(&model.Artwork{})

	tableName := _artwork.artworkDo.TableName()
	_artwork.ALL = field.NewAsterisk(tableName)
	_artwork.ID = field.NewField(tableName, "id")
	_artwork.ItemID = field.NewField(tableName, "item_id")
	_artwork.Source = field.NewString(tableName, "source")
	_artwork.Kind = field.NewString(tableName, "kind")
	_artwork.Place = field.NewString(tableName, "place")
	_artwork.Position = field.NewInt(tableName, "position")
	_artwork.Folder = field.NewString(tableName, "folder")
	_artwork.Language = field.NewString(tableName, "language")
	_artwork.Width = field.NewInt(tableName, "width")
	_artwork.Height = field.NewInt(tableName, "height")

	_artwork.fillFieldMap()

	return _artwork
}

type artwork struct {
	artworkDo artworkDo

	ALL      field.Asterisk
	ID       field.Field
	ItemID   field.Field
	Source   field.String
	Kind     field.String
	Place    field.String
	Position field.Int
	Folder   field.String
	Language field.String
	Width    field.Int
	Height   field.Int

	fieldMap map[string]field.Expr
}

func (a artwork) Table(newTableName string) *artwork {
	a.artworkDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a artwork) As(alias string) *artwork {
	a.artworkDo.DO = *(a.artworkDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *artwork) updateTableName(table string) *artwork {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewField(table, "id")
	a.ItemID = field.NewField(table, "item_id")
	a.Source = field.NewString(table, "source")
	a.Kind = field.NewString(table, "kind")
	a.Place = field.NewString(table, "place")
	a.Position = field.NewInt(table, "position")
	a.Folder = field.NewString(table, "folder")
	a.Language = field.NewString(table, "language")
	a.Width = field.NewInt(table, "width")
	a.Height = field.NewInt(table, "height")

	a.fillFieldMap()

	return a
}

func (a *artwork) WithContext(ctx context.Context) IArtworkDo { return a.artworkDo.WithContext(ctx) }

func (a artwork) TableName() string { return a.artworkDo.TableName() }

func (a artwork) Alias() string { return a.artworkDo.Alias() }

func (a artwork) Columns(cols ...field.Expr) gen.Columns { return a.artworkDo.Columns(cols...) }

func (a *artwork) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *artwork) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["item_id"] = a.ItemID
	a.fieldMap["source"] = a.Source
	a.fieldMap["kind"] = a.Kind
	a.fieldMap["place"] = a.Place
	a.fieldMap["position"] = a.Position
	a.fieldMap["folder"] = a.Folder
	a.fieldMap["language"] = a.Language
	a.fieldMap["width"] = a.Width
	a.fieldMap["height"] = a.Height
}

func (a artwork) clone(db *gorm.DB) artwork {
	a.artworkDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a artwork) replaceDB(db *gorm.DB) artwork {
	a.artworkDo.ReplaceDB(db)
	return a
}

type artworkDo struct{ gen.DO }

type IArtworkDo interface {
	gen.SubQuery
	Debug() IArtworkDo
	WithContext(ctx context.Context) IArtworkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IArtworkDo
	WriteDB() IArtworkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IArtworkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IArtworkDo
	Not(conds ...gen.Condition) IArtworkDo
	Or(conds ...gen.Condition) IArtworkDo
	Select(conds ...field.Expr) IArtworkDo
	Where(conds ...gen.Condition) IArtworkDo
	Order(conds ...field.Expr) IArtworkDo
	Distinct(cols ...field.Expr) IArtworkDo
	Omit(cols ...field.Expr) IArtworkDo
	Join(table schema.Tabler, on ...field.Expr) IArtworkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IArtworkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IArtworkDo
	Group(cols ...field.Expr) IArtworkDo
	Having(conds ...gen.Condition) IArtworkDo
	Limit(limit int) IArtworkDo
	Offset(offset int) IArtworkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IArtworkDo
	Unscoped() IArtworkDo
	Create(values ...*model.Artwork) error
	CreateInBatches(values []*model.Artwork, batchSize int) error
	Save(values ...*model.Artwork) error
	First() (*model.Artwork, error)
	Take() (*model.Artwork, error)
	Last() (*model.Artwork, error)
	Find() ([]*model.Artwork, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Artwork, err error)
	FindInBatches(result *[]*model.Artwork, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Artwork) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IArtworkDo
	Assign(attrs ...field.AssignExpr) IArtworkDo
	Joins(fields ...field.RelationField) IArtworkDo
	Preload(fields ...field.RelationField) IArtworkDo
	FirstOrInit() (*model.Artwork, error)
	FirstOrCreate() (*model.Artwork, error)
	FindByPage(offset int, limit int) (result []*model.Artwork, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IArtworkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a artworkDo) Debug() IArtworkDo {
	return a.withDO(a.DO.Debug())
}

func (a artworkDo) WithContext(ctx context.Context) IArtworkDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a artworkDo) ReadDB() IArtworkDo {
	return a.Clauses(dbresolver.Read)
}

func (a artworkDo) WriteDB() IArtworkDo {
	return a.Clauses(dbresolver.Write)
}

func (a artworkDo) Session(config *gorm.Session) IArtworkDo {
	return a.withDO(a.DO.Session(config))
}

func (a artworkDo) Clauses(conds ...clause.Expression) IArtworkDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a artworkDo) Returning(value interface{}, columns ...string) IArtworkDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a artworkDo) Not(conds ...gen.Condition) IArtworkDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a artworkDo) Or(conds ...gen.Condition) IArtworkDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a artworkDo) Select(conds ...field.Expr) IArtworkDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a artworkDo) Where(conds ...gen.Condition) IArtworkDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a artworkDo) Order(conds ...field.Expr) IArtworkDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a artworkDo) Distinct(cols ...field.Expr) IArtworkDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a artworkDo) Omit(cols ...field.Expr) IArtworkDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a artworkDo) Join(table schema.Tabler, on ...field.Expr) IArtworkDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a artworkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IArtworkDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a artworkDo) RightJoin(table schema.Tabler, on ...field.Expr) IArtworkDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a artworkDo) Group(cols ...field.Expr) IArtworkDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a artworkDo) Having(conds ...gen.Condition) IArtworkDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a artworkDo) Limit(limit int) IArtworkDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a artworkDo) Offset(offset int) IArtworkDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a artworkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IArtworkDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a artworkDo) Unscoped() IArtworkDo {
	return a.withDO(a.DO.Unscoped())
}

func (a artworkDo) Create(values ...*model.Artwork) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a artworkDo) CreateInBatches(values []*model.Artwork, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a artworkDo) Save(values ...*model.Artwork) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a artworkDo) First() (*model.Artwork, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Artwork), nil
	}
}

func (a artworkDo) Take() (*model.Artwork, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Artwork), nil
	}
}

func (a artworkDo) Last() (*model.Artwork, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Artwork), nil
	}
}

func (a artworkDo) Find() ([]*model.Artwork, error) {
	result, err := a.DO.Find()
	return result.([]*model.Artwork), err
}

func (a artworkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Artwork, err error) {
	buf := make([]*model.Artwork, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a artworkDo) FindInBatches(result *[]*model.Artwork, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a artworkDo) Attrs(attrs ...field.AssignExpr) IArtworkDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a artworkDo) Assign(attrs ...field.AssignExpr) IArtworkDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a artworkDo) Joins(fields ...field.RelationField) IArtworkDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a artworkDo) Preload(fields ...field.RelationField) IArtworkDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a artworkDo) FirstOrInit() (*model.Artwork, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Artwork), nil
	}
}

func (a artworkDo) FirstOrCreate() (*model.Artwork, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Artwork), nil
	}
}

func (a artworkDo) FindByPage(offset int, limit int) (result []*model.Artwork, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a artworkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a artworkDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a artworkDo) Delete(models ...*model.Artwork) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *artworkDo) withDO(do gen.Dao) *artworkDo {
	a.DO = *do.(*gen.DO)
	return a
}
