// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newCollectionMember(db *gorm.DB, opts ...gen.DOOption) collectionMember {
	_collectionMember := collectionMember{}

	_collectionMember.collectionMemberDo.UseDB(db, opts...)
	_collectionMember.collectionMemberDo.UseModel(&model.CollectionMember{})

	tableName := _collectionMember.collectionMemberDo.TableName()
	_collectionMember.ALL = field.NewAsterisk(tableName)
	_collectionMember.CollectionID = field.NewField(tableName, "collection_id")
	_collectionMember.ItemID = field.NewField(tableName, "item_id")
	_collectionMember.Position = field.NewInt(tableName, "position")

	_collectionMember.fillFieldMap()

	return _collectionMember
}

type collectionMember struct {
	collectionMemberDo collectionMemberDo

	ALL          field.Asterisk
	CollectionID field.Field
	ItemID       field.Field
	Position     field.Int

	fieldMap map[string]field.Expr
}

func (c collectionMember) Table(newTableName string) *collectionMember {
	c.collectionMemberDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c collectionMember) As(alias string) *collectionMember {
	c.collectionMemberDo.DO = *(c.collectionMemberDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *collectionMember) updateTableName(table string) *collectionMember {
	c.ALL = field.NewAsterisk(table)
	c.CollectionID = field.NewField(table, "collection_id")
	c.ItemID = field.NewField(table, "item_id")
	c.Position = field.NewInt(table, "position")

	c.fillFieldMap()

	return c
}

func (c *collectionMember) WithContext(ctx context.Context) ICollectionMemberDo {
	return c.collectionMemberDo.WithContext(ctx)
}

func (c collectionMember) TableName() string { return c.collectionMemberDo.TableName() }

func (c collectionMember) Alias() string { return c.collectionMemberDo.Alias() }

func (c collectionMember) Columns(cols ...field.Expr) gen.Columns {
	return c.collectionMemberDo.Columns(cols...)
}

func (c *collectionMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *collectionMember) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["collection_id"] = c.CollectionID
	c.fieldMap["item_id"] = c.ItemID
	c.fieldMap["position"] = c.Position
}

func (c collectionMember) clone(db *gorm.DB) collectionMember {
	c.collectionMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c collectionMember) replaceDB(db *gorm.DB) collectionMember {
	c.collectionMemberDo.ReplaceDB(db)
	return c
}

type collectionMemberDo struct{ gen.DO }

type ICollectionMemberDo interface {
	gen.SubQuery
	Debug() ICollectionMemberDo
	WithContext(ctx context.Context) ICollectionMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICollectionMemberDo
	WriteDB() ICollectionMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICollectionMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICollectionMemberDo
	Not(conds ...gen.Condition) ICollectionMemberDo
	Or(conds ...gen.Condition) ICollectionMemberDo
	Select(conds ...field.Expr) ICollectionMemberDo
	Where(conds ...gen.Condition) ICollectionMemberDo
	Order(conds ...field.Expr) ICollectionMemberDo
	Distinct(cols ...field.Expr) ICollectionMemberDo
	Omit(cols ...field.Expr) ICollectionMemberDo
	Join(table schema.Tabler, on ...field.Expr) ICollectionMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICollectionMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICollectionMemberDo
	Group(cols ...field.Expr) ICollectionMemberDo
	Having(conds ...gen.Condition) ICollectionMemberDo
	Limit(limit int) ICollectionMemberDo
	Offset(offset int) ICollectionMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICollectionMemberDo
	Unscoped() ICollectionMemberDo
	Create(values ...*model.CollectionMember) error
	CreateInBatches(values []*model.CollectionMember, batchSize int) error
	Save(values ...*model.CollectionMember) error
	First() (*model.CollectionMember, error)
	Take() (*model.CollectionMember, error)
	Last() (*model.CollectionMember, error)
	Find() ([]*model.CollectionMember, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CollectionMember, err error)
	FindInBatches(result *[]*model.CollectionMember, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CollectionMember) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICollectionMemberDo
	Assign(attrs ...field.AssignExpr) ICollectionMemberDo
	Joins(fields ...field.RelationField) ICollectionMemberDo
	Preload(fields ...field.RelationField) ICollectionMemberDo
	FirstOrInit() (*model.CollectionMember, error)
	FirstOrCreate() (*model.CollectionMember, error)
	FindByPage(offset int, limit int) (result []*model.CollectionMember, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICollectionMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c collectionMemberDo) Debug() ICollectionMemberDo {
	return c.withDO(c.DO.Debug())
}

func (c collectionMemberDo) WithContext(ctx context.Context) ICollectionMemberDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c collectionMemberDo) ReadDB() ICollectionMemberDo {
	return c.Clauses(dbresolver.Read)
}

func (c collectionMemberDo) WriteDB() ICollectionMemberDo {
	return c.Clauses(dbresolver.Write)
}

func (c collectionMemberDo) Session(config *gorm.Session) ICollectionMemberDo {
	return c.withDO(c.DO.Session(config))
}

func (c collectionMemberDo) Clauses(conds ...clause.Expression) ICollectionMemberDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c collectionMemberDo) Returning(value interface{}, columns ...string) ICollectionMemberDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c collectionMemberDo) Not(conds ...gen.Condition) ICollectionMemberDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c collectionMemberDo) Or(conds ...gen.Condition) ICollectionMemberDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c collectionMemberDo) Select(conds ...field.Expr) ICollectionMemberDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c collectionMemberDo) Where(conds ...gen.Condition) ICollectionMemberDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c collectionMemberDo) Order(conds ...field.Expr) ICollectionMemberDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c collectionMemberDo) Distinct(cols ...field.Expr) ICollectionMemberDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c collectionMemberDo) Omit(cols ...field.Expr) ICollectionMemberDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c collectionMemberDo) Join(table schema.Tabler, on ...field.Expr) ICollectionMemberDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c collectionMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICollectionMemberDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c collectionMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) ICollectionMemberDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c collectionMemberDo) Group(cols ...field.Expr) ICollectionMemberDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c collectionMemberDo) Having(conds ...gen.Condition) ICollectionMemberDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c collectionMemberDo) Limit(limit int) ICollectionMemberDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c collectionMemberDo) Offset(offset int) ICollectionMemberDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c collectionMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICollectionMemberDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c collectionMemberDo) Unscoped() ICollectionMemberDo {
	return c.withDO(c.DO.Unscoped())
}

func (c collectionMemberDo) Create(values ...*model.CollectionMember) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c collectionMemberDo) CreateInBatches(values []*model.CollectionMember, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c collectionMemberDo) Save(values ...*model.CollectionMember) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c collectionMemberDo) First() (*model.CollectionMember, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CollectionMember), nil
	}
}

func (c collectionMemberDo) Take() (*model.CollectionMember, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CollectionMember), nil
	}
}

func (c collectionMemberDo) Last() (*model.CollectionMember, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CollectionMember), nil
	}
}

func (c collectionMemberDo) Find() ([]*model.CollectionMember, error) {
	result, err := c.DO.Find()
	return result.([]*model.CollectionMember), err
}

func (c collectionMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CollectionMember, err error) {
	buf := make([]*model.CollectionMember, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c collectionMemberDo) FindInBatches(result *[]*model.CollectionMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c collectionMemberDo) Attrs(attrs ...field.AssignExpr) ICollectionMemberDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c collectionMemberDo) Assign(attrs ...field.AssignExpr) ICollectionMemberDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c collectionMemberDo) Joins(fields ...field.RelationField) ICollectionMemberDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c collectionMemberDo) Preload(fields ...field.RelationField) ICollectionMemberDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c collectionMemberDo) FirstOrInit() (*model.CollectionMember, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CollectionMember), nil
	}
}

func (c collectionMemberDo) FirstOrCreate() (*model.CollectionMember, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CollectionMember), nil
	}
}

func (c collectionMemberDo) FindByPage(offset int, limit int) (result []*model.CollectionMember, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c collectionMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c collectionMemberDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c collectionMemberDo) Delete(models ...*model.CollectionMember) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *collectionMemberDo) withDO(do gen.Dao) *collectionMemberDo {
	c.DO = *do.(*gen.DO)
	return c
}
