// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newConversion(db *gorm.DB, opts ...gen.DOOption) conversion {
	_conversion := conversion{}

	_conversion.conversionDo.UseDB(db, opts...)
	_conversion.conversionDo.UseModel(&model.Conversion{})

	tableName := _conversion.conversionDo.TableName()
	_conversion.ALL = field.NewAsterisk(tableName)
	_conversion.ID = field.NewField(tableName, "id")
	_conversion.PartID = field.NewField(tableName, "part_id")
	_conversion.MaxBitrateKbps = field.NewInt(tableName, "max_bitrate_kbps")
	_conversion.MaxWidth = field.NewInt(tableName, "max_width")
	_conversion.VideoCodec = field.NewString(tableName, "video_codec")
	_conversion.VideoRange = field.NewString(tableName, "video_range")
	_conversion.State = field.NewString(tableName, "state")
	_conversion.Progress = field.NewFloat64(tableName, "progress")
	_conversion.SizeBytes = field.NewInt64(tableName, "size_bytes")
	_conversion.Error = field.NewString(tableName, "error")
	_conversion.NodeID = field.NewField(tableName, "node_id")
	_conversion.FinishedAt = field.NewTime(tableName, "finished_at")

	_conversion.fillFieldMap()

	return _conversion
}

type conversion struct {
	conversionDo conversionDo

	ALL            field.Asterisk
	ID             field.Field
	PartID         field.Field
	MaxBitrateKbps field.Int
	MaxWidth       field.Int
	VideoCodec     field.String
	VideoRange     field.String
	State          field.String
	Progress       field.Float64
	SizeBytes      field.Int64
	Error          field.String
	NodeID         field.Field
	FinishedAt     field.Time

	fieldMap map[string]field.Expr
}

func (c conversion) Table(newTableName string) *conversion {
	c.conversionDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c conversion) As(alias string) *conversion {
	c.conversionDo.DO = *(c.conversionDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *conversion) updateTableName(table string) *conversion {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewField(table, "id")
	c.PartID = field.NewField(table, "part_id")
	c.MaxBitrateKbps = field.NewInt(table, "max_bitrate_kbps")
	c.MaxWidth = field.NewInt(table, "max_width")
	c.VideoCodec = field.NewString(table, "video_codec")
	c.VideoRange = field.NewString(table, "video_range")
	c.State = field.NewString(table, "state")
	c.Progress = field.NewFloat64(table, "progress")
	c.SizeBytes = field.NewInt64(table, "size_bytes")
	c.Error = field.NewString(table, "error")
	c.NodeID = field.NewField(table, "node_id")
	c.FinishedAt = field.NewTime(table, "finished_at")

	c.fillFieldMap()

	return c
}

func (c *conversion) WithContext(ctx context.Context) IConversionDo {
	return c.conversionDo.WithContext(ctx)
}

func (c conversion) TableName() string { return c.conversionDo.TableName() }

func (c conversion) Alias() string { return c.conversionDo.Alias() }

func (c conversion) Columns(cols ...field.Expr) gen.Columns { return c.conversionDo.Columns(cols...) }

func (c *conversion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *conversion) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 12)
	c.fieldMap["id"] = c.ID
	c.fieldMap["part_id"] = c.PartID
	c.fieldMap["max_bitrate_kbps"] = c.MaxBitrateKbps
	c.fieldMap["max_width"] = c.MaxWidth
	c.fieldMap["video_codec"] = c.VideoCodec
	c.fieldMap["video_range"] = c.VideoRange
	c.fieldMap["state"] = c.State
	c.fieldMap["progress"] = c.Progress
	c.fieldMap["size_bytes"] = c.SizeBytes
	c.fieldMap["error"] = c.Error
	c.fieldMap["node_id"] = c.NodeID
	c.fieldMap["finished_at"] = c.FinishedAt
}

func (c conversion) clone(db *gorm.DB) conversion {
	c.conversionDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c conversion) replaceDB(db *gorm.DB) conversion {
	c.conversionDo.ReplaceDB(db)
	return c
}

type conversionDo struct{ gen.DO }

type IConversionDo interface {
	gen.SubQuery
	Debug() IConversionDo
	WithContext(ctx context.Context) IConversionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConversionDo
	WriteDB() IConversionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConversionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConversionDo
	Not(conds ...gen.Condition) IConversionDo
	Or(conds ...gen.Condition) IConversionDo
	Select(conds ...field.Expr) IConversionDo
	Where(conds ...gen.Condition) IConversionDo
	Order(conds ...field.Expr) IConversionDo
	Distinct(cols ...field.Expr) IConversionDo
	Omit(cols ...field.Expr) IConversionDo
	Join(table schema.Tabler, on ...field.Expr) IConversionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConversionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConversionDo
	Group(cols ...field.Expr) IConversionDo
	Having(conds ...gen.Condition) IConversionDo
	Limit(limit int) IConversionDo
	Offset(offset int) IConversionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConversionDo
	Unscoped() IConversionDo
	Create(values ...*model.Conversion) error
	CreateInBatches(values []*model.Conversion, batchSize int) error
	Save(values ...*model.Conversion) error
	First() (*model.Conversion, error)
	Take() (*model.Conversion, error)
	Last() (*model.Conversion, error)
	Find() ([]*model.Conversion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Conversion, err error)
	FindInBatches(result *[]*model.Conversion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Conversion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConversionDo
	Assign(attrs ...field.AssignExpr) IConversionDo
	Joins(fields ...field.RelationField) IConversionDo
	Preload(fields ...field.RelationField) IConversionDo
	FirstOrInit() (*model.Conversion, error)
	FirstOrCreate() (*model.Conversion, error)
	FindByPage(offset int, limit int) (result []*model.Conversion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConversionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c conversionDo) Debug() IConversionDo {
	return c.withDO(c.DO.Debug())
}

func (c conversionDo) WithContext(ctx context.Context) IConversionDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c conversionDo) ReadDB() IConversionDo {
	return c.Clauses(dbresolver.Read)
}

func (c conversionDo) WriteDB() IConversionDo {
	return c.Clauses(dbresolver.Write)
}

func (c conversionDo) Session(config *gorm.Session) IConversionDo {
	return c.withDO(c.DO.Session(config))
}

func (c conversionDo) Clauses(conds ...clause.Expression) IConversionDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c conversionDo) Returning(value interface{}, columns ...string) IConversionDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c conversionDo) Not(conds ...gen.Condition) IConversionDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c conversionDo) Or(conds ...gen.Condition) IConversionDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c conversionDo) Select(conds ...field.Expr) IConversionDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c conversionDo) Where(conds ...gen.Condition) IConversionDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c conversionDo) Order(conds ...field.Expr) IConversionDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c conversionDo) Distinct(cols ...field.Expr) IConversionDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c conversionDo) Omit(cols ...field.Expr) IConversionDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c conversionDo) Join(table schema.Tabler, on ...field.Expr) IConversionDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c conversionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConversionDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c conversionDo) RightJoin(table schema.Tabler, on ...field.Expr) IConversionDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c conversionDo) Group(cols ...field.Expr) IConversionDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c conversionDo) Having(conds ...gen.Condition) IConversionDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c conversionDo) Limit(limit int) IConversionDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c conversionDo) Offset(offset int) IConversionDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c conversionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConversionDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c conversionDo) Unscoped() IConversionDo {
	return c.withDO(c.DO.Unscoped())
}

func (c conversionDo) Create(values ...*model.Conversion) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c conversionDo) CreateInBatches(values []*model.Conversion, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c conversionDo) Save(values ...*model.Conversion) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c conversionDo) First() (*model.Conversion, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Conversion), nil
	}
}

func (c conversionDo) Take() (*model.Conversion, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Conversion), nil
	}
}

func (c conversionDo) Last() (*model.Conversion, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Conversion), nil
	}
}

func (c conversionDo) Find() ([]*model.Conversion, error) {
	result, err := c.DO.Find()
	return result.([]*model.Conversion), err
}

func (c conversionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Conversion, err error) {
	buf := make([]*model.Conversion, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c conversionDo) FindInBatches(result *[]*model.Conversion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c conversionDo) Attrs(attrs ...field.AssignExpr) IConversionDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c conversionDo) Assign(attrs ...field.AssignExpr) IConversionDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c conversionDo) Joins(fields ...field.RelationField) IConversionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c conversionDo) Preload(fields ...field.RelationField) IConversionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c conversionDo) FirstOrInit() (*model.Conversion, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Conversion), nil
	}
}

func (c conversionDo) FirstOrCreate() (*model.Conversion, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Conversion), nil
	}
}

func (c conversionDo) FindByPage(offset int, limit int) (result []*model.Conversion, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c conversionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c conversionDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c conversionDo) Delete(models ...*model.Conversion) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *conversionDo) withDO(do gen.Dao) *conversionDo {
	c.DO = *do.(*gen.DO)
	return c
}
