// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newDeviceSession(db *gorm.DB, opts ...gen.DOOption) deviceSession {
	_deviceSession := deviceSession{}

	_deviceSession.deviceSessionDo.UseDB(db, opts...)
	_deviceSession.deviceSessionDo.UseModel(&model.DeviceSession{})

	tableName := _deviceSession.deviceSessionDo.TableName()
	_deviceSession.ALL = field.NewAsterisk(tableName)
	_deviceSession.ID = field.NewField(tableName, "id")
	_deviceSession.TokenHash = field.NewBytes(tableName, "token_hash")
	_deviceSession.ProfileID = field.NewField(tableName, "profile_id")
	_deviceSession.DeviceName = field.NewString(tableName, "device_name")
	_deviceSession.Client = field.NewString(tableName, "client")
	_deviceSession.CreatedAt = field.NewTime(tableName, "created_at")
	_deviceSession.LastSeenAt = field.NewTime(tableName, "last_seen_at")
	_deviceSession.ExpiresAt = field.NewTime(tableName, "expires_at")

	_deviceSession.fillFieldMap()

	return _deviceSession
}

type deviceSession struct {
	deviceSessionDo deviceSessionDo

	ALL        field.Asterisk
	ID         field.Field
	TokenHash  field.Bytes
	ProfileID  field.Field
	DeviceName field.String
	Client     field.String
	CreatedAt  field.Time
	LastSeenAt field.Time
	ExpiresAt  field.Time

	fieldMap map[string]field.Expr
}

func (d deviceSession) Table(newTableName string) *deviceSession {
	d.deviceSessionDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceSession) As(alias string) *deviceSession {
	d.deviceSessionDo.DO = *(d.deviceSessionDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceSession) updateTableName(table string) *deviceSession {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewField(table, "id")
	d.TokenHash = field.NewBytes(table, "token_hash")
	d.ProfileID = field.NewField(table, "profile_id")
	d.DeviceName = field.NewString(table, "device_name")
	d.Client = field.NewString(table, "client")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.LastSeenAt = field.NewTime(table, "last_seen_at")
	d.ExpiresAt = field.NewTime(table, "expires_at")

	d.fillFieldMap()

	return d
}

func (d *deviceSession) WithContext(ctx context.Context) IDeviceSessionDo {
	return d.deviceSessionDo.WithContext(ctx)
}

func (d deviceSession) TableName() string { return d.deviceSessionDo.TableName() }

func (d deviceSession) Alias() string { return d.deviceSessionDo.Alias() }

func (d deviceSession) Columns(cols ...field.Expr) gen.Columns {
	return d.deviceSessionDo.Columns(cols...)
}

func (d *deviceSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceSession) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 8)
	d.fieldMap["id"] = d.ID
	d.fieldMap["token_hash"] = d.TokenHash
	d.fieldMap["profile_id"] = d.ProfileID
	d.fieldMap["device_name"] = d.DeviceName
	d.fieldMap["client"] = d.Client
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["last_seen_at"] = d.LastSeenAt
	d.fieldMap["expires_at"] = d.ExpiresAt
}

func (d deviceSession) clone(db *gorm.DB) deviceSession {
	d.deviceSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceSession) replaceDB(db *gorm.DB) deviceSession {
	d.deviceSessionDo.ReplaceDB(db)
	return d
}

type deviceSessionDo struct{ gen.DO }

type IDeviceSessionDo interface {
	gen.SubQuery
	Debug() IDeviceSessionDo
	WithContext(ctx context.Context) IDeviceSessionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceSessionDo
	WriteDB() IDeviceSessionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceSessionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceSessionDo
	Not(conds ...gen.Condition) IDeviceSessionDo
	Or(conds ...gen.Condition) IDeviceSessionDo
	Select(conds ...field.Expr) IDeviceSessionDo
	Where(conds ...gen.Condition) IDeviceSessionDo
	Order(conds ...field.Expr) IDeviceSessionDo
	Distinct(cols ...field.Expr) IDeviceSessionDo
	Omit(cols ...field.Expr) IDeviceSessionDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceSessionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceSessionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceSessionDo
	Group(cols ...field.Expr) IDeviceSessionDo
	Having(conds ...gen.Condition) IDeviceSessionDo
	Limit(limit int) IDeviceSessionDo
	Offset(offset int) IDeviceSessionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceSessionDo
	Unscoped() IDeviceSessionDo
	Create(values ...*model.DeviceSession) error
	CreateInBatches(values []*model.DeviceSession, batchSize int) error
	Save(values ...*model.DeviceSession) error
	First() (*model.DeviceSession, error)
	Take() (*model.DeviceSession, error)
	Last() (*model.DeviceSession, error)
	Find() ([]*model.DeviceSession, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceSession, err error)
	FindInBatches(result *[]*model.DeviceSession, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceSession) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceSessionDo
	Assign(attrs ...field.AssignExpr) IDeviceSessionDo
	Joins(fields ...field.RelationField) IDeviceSessionDo
	Preload(fields ...field.RelationField) IDeviceSessionDo
	FirstOrInit() (*model.DeviceSession, error)
	FirstOrCreate() (*model.DeviceSession, error)
	FindByPage(offset int, limit int) (result []*model.DeviceSession, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceSessionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceSessionDo) Debug() IDeviceSessionDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceSessionDo) WithContext(ctx context.Context) IDeviceSessionDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceSessionDo) ReadDB() IDeviceSessionDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceSessionDo) WriteDB() IDeviceSessionDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceSessionDo) Session(config *gorm.Session) IDeviceSessionDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceSessionDo) Clauses(conds ...clause.Expression) IDeviceSessionDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceSessionDo) Returning(value interface{}, columns ...string) IDeviceSessionDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceSessionDo) Not(conds ...gen.Condition) IDeviceSessionDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceSessionDo) Or(conds ...gen.Condition) IDeviceSessionDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceSessionDo) Select(conds ...field.Expr) IDeviceSessionDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceSessionDo) Where(conds ...gen.Condition) IDeviceSessionDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceSessionDo) Order(conds ...field.Expr) IDeviceSessionDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceSessionDo) Distinct(cols ...field.Expr) IDeviceSessionDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceSessionDo) Omit(cols ...field.Expr) IDeviceSessionDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceSessionDo) Join(table schema.Tabler, on ...field.Expr) IDeviceSessionDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceSessionDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceSessionDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceSessionDo) Group(cols ...field.Expr) IDeviceSessionDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceSessionDo) Having(conds ...gen.Condition) IDeviceSessionDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceSessionDo) Limit(limit int) IDeviceSessionDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceSessionDo) Offset(offset int) IDeviceSessionDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceSessionDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceSessionDo) Unscoped() IDeviceSessionDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceSessionDo) Create(values ...*model.DeviceSession) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceSessionDo) CreateInBatches(values []*model.DeviceSession, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceSessionDo) Save(values ...*model.DeviceSession) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceSessionDo) First() (*model.DeviceSession, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceSession), nil
	}
}

func (d deviceSessionDo) Take() (*model.DeviceSession, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceSession), nil
	}
}

func (d deviceSessionDo) Last() (*model.DeviceSession, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceSession), nil
	}
}

func (d deviceSessionDo) Find() ([]*model.DeviceSession, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceSession), err
}

func (d deviceSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceSession, err error) {
	buf := make([]*model.DeviceSession, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceSessionDo) FindInBatches(result *[]*model.DeviceSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceSessionDo) Attrs(attrs ...field.AssignExpr) IDeviceSessionDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceSessionDo) Assign(attrs ...field.AssignExpr) IDeviceSessionDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceSessionDo) Joins(fields ...field.RelationField) IDeviceSessionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceSessionDo) Preload(fields ...field.RelationField) IDeviceSessionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceSessionDo) FirstOrInit() (*model.DeviceSession, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceSession), nil
	}
}

func (d deviceSessionDo) FirstOrCreate() (*model.DeviceSession, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceSession), nil
	}
}

func (d deviceSessionDo) FindByPage(offset int, limit int) (result []*model.DeviceSession, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceSessionDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceSessionDo) Delete(models ...*model.DeviceSession) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceSessionDo) withDO(do gen.Dao) *deviceSessionDo {
	d.DO = *do.(*gen.DO)
	return d
}
