// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newExternalID(db *gorm.DB, opts ...gen.DOOption) externalID {
	_externalID := externalID{}

	_externalID.externalIDDo.UseDB(db, opts...)
	_externalID.externalIDDo.UseModel(&model.ExternalID{})

	tableName := _externalID.externalIDDo.TableName()
	_externalID.ALL = field.NewAsterisk(tableName)
	_externalID.ItemID = field.NewField(tableName, "item_id")
	_externalID.Provider = field.NewString(tableName, "provider")
	_externalID.Value = field.NewString(tableName, "value")
	_externalID.Source = field.NewString(tableName, "source")

	_externalID.fillFieldMap()

	return _externalID
}

type externalID struct {
	externalIDDo externalIDDo

	ALL      field.Asterisk
	ItemID   field.Field
	Provider field.String
	Value    field.String
	Source   field.String

	fieldMap map[string]field.Expr
}

func (e externalID) Table(newTableName string) *externalID {
	e.externalIDDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e externalID) As(alias string) *externalID {
	e.externalIDDo.DO = *(e.externalIDDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *externalID) updateTableName(table string) *externalID {
	e.ALL = field.NewAsterisk(table)
	e.ItemID = field.NewField(table, "item_id")
	e.Provider = field.NewString(table, "provider")
	e.Value = field.NewString(table, "value")
	e.Source = field.NewString(table, "source")

	e.fillFieldMap()

	return e
}

func (e *externalID) WithContext(ctx context.Context) IExternalIDDo {
	return e.externalIDDo.WithContext(ctx)
}

func (e externalID) TableName() string { return e.externalIDDo.TableName() }

func (e externalID) Alias() string { return e.externalIDDo.Alias() }

func (e externalID) Columns(cols ...field.Expr) gen.Columns { return e.externalIDDo.Columns(cols...) }

func (e *externalID) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *externalID) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 4)
	e.fieldMap["item_id"] = e.ItemID
	e.fieldMap["provider"] = e.Provider
	e.fieldMap["value"] = e.Value
	e.fieldMap["source"] = e.Source
}

func (e externalID) clone(db *gorm.DB) externalID {
	e.externalIDDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e externalID) replaceDB(db *gorm.DB) externalID {
	e.externalIDDo.ReplaceDB(db)
	return e
}

type externalIDDo struct{ gen.DO }

type IExternalIDDo interface {
	gen.SubQuery
	Debug() IExternalIDDo
	WithContext(ctx context.Context) IExternalIDDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IExternalIDDo
	WriteDB() IExternalIDDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IExternalIDDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IExternalIDDo
	Not(conds ...gen.Condition) IExternalIDDo
	Or(conds ...gen.Condition) IExternalIDDo
	Select(conds ...field.Expr) IExternalIDDo
	Where(conds ...gen.Condition) IExternalIDDo
	Order(conds ...field.Expr) IExternalIDDo
	Distinct(cols ...field.Expr) IExternalIDDo
	Omit(cols ...field.Expr) IExternalIDDo
	Join(table schema.Tabler, on ...field.Expr) IExternalIDDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IExternalIDDo
	RightJoin(table schema.Tabler, on ...field.Expr) IExternalIDDo
	Group(cols ...field.Expr) IExternalIDDo
	Having(conds ...gen.Condition) IExternalIDDo
	Limit(limit int) IExternalIDDo
	Offset(offset int) IExternalIDDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IExternalIDDo
	Unscoped() IExternalIDDo
	Create(values ...*model.ExternalID) error
	CreateInBatches(values []*model.ExternalID, batchSize int) error
	Save(values ...*model.ExternalID) error
	First() (*model.ExternalID, error)
	Take() (*model.ExternalID, error)
	Last() (*model.ExternalID, error)
	Find() ([]*model.ExternalID, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ExternalID, err error)
	FindInBatches(result *[]*model.ExternalID, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ExternalID) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IExternalIDDo
	Assign(attrs ...field.AssignExpr) IExternalIDDo
	Joins(fields ...field.RelationField) IExternalIDDo
	Preload(fields ...field.RelationField) IExternalIDDo
	FirstOrInit() (*model.ExternalID, error)
	FirstOrCreate() (*model.ExternalID, error)
	FindByPage(offset int, limit int) (result []*model.ExternalID, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IExternalIDDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e externalIDDo) Debug() IExternalIDDo {
	return e.withDO(e.DO.Debug())
}

func (e externalIDDo) WithContext(ctx context.Context) IExternalIDDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e externalIDDo) ReadDB() IExternalIDDo {
	return e.Clauses(dbresolver.Read)
}

func (e externalIDDo) WriteDB() IExternalIDDo {
	return e.Clauses(dbresolver.Write)
}

func (e externalIDDo) Session(config *gorm.Session) IExternalIDDo {
	return e.withDO(e.DO.Session(config))
}

func (e externalIDDo) Clauses(conds ...clause.Expression) IExternalIDDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e externalIDDo) Returning(value interface{}, columns ...string) IExternalIDDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e externalIDDo) Not(conds ...gen.Condition) IExternalIDDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e externalIDDo) Or(conds ...gen.Condition) IExternalIDDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e externalIDDo) Select(conds ...field.Expr) IExternalIDDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e externalIDDo) Where(conds ...gen.Condition) IExternalIDDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e externalIDDo) Order(conds ...field.Expr) IExternalIDDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e externalIDDo) Distinct(cols ...field.Expr) IExternalIDDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e externalIDDo) Omit(cols ...field.Expr) IExternalIDDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e externalIDDo) Join(table schema.Tabler, on ...field.Expr) IExternalIDDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e externalIDDo) LeftJoin(table schema.Tabler, on ...field.Expr) IExternalIDDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e externalIDDo) RightJoin(table schema.Tabler, on ...field.Expr) IExternalIDDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e externalIDDo) Group(cols ...field.Expr) IExternalIDDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e externalIDDo) Having(conds ...gen.Condition) IExternalIDDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e externalIDDo) Limit(limit int) IExternalIDDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e externalIDDo) Offset(offset int) IExternalIDDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e externalIDDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IExternalIDDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e externalIDDo) Unscoped() IExternalIDDo {
	return e.withDO(e.DO.Unscoped())
}

func (e externalIDDo) Create(values ...*model.ExternalID) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e externalIDDo) CreateInBatches(values []*model.ExternalID, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e externalIDDo) Save(values ...*model.ExternalID) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e externalIDDo) First() (*model.ExternalID, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalID), nil
	}
}

func (e externalIDDo) Take() (*model.ExternalID, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalID), nil
	}
}

func (e externalIDDo) Last() (*model.ExternalID, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalID), nil
	}
}

func (e externalIDDo) Find() ([]*model.ExternalID, error) {
	result, err := e.DO.Find()
	return result.([]*model.ExternalID), err
}

func (e externalIDDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ExternalID, err error) {
	buf := make([]*model.ExternalID, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e externalIDDo) FindInBatches(result *[]*model.ExternalID, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e externalIDDo) Attrs(attrs ...field.AssignExpr) IExternalIDDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e externalIDDo) Assign(attrs ...field.AssignExpr) IExternalIDDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e externalIDDo) Joins(fields ...field.RelationField) IExternalIDDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e externalIDDo) Preload(fields ...field.RelationField) IExternalIDDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e externalIDDo) FirstOrInit() (*model.ExternalID, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalID), nil
	}
}

func (e externalIDDo) FirstOrCreate() (*model.ExternalID, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalID), nil
	}
}

func (e externalIDDo) FindByPage(offset int, limit int) (result []*model.ExternalID, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e externalIDDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e externalIDDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e externalIDDo) Delete(models ...*model.ExternalID) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *externalIDDo) withDO(do gen.Dao) *externalIDDo {
	e.DO = *do.(*gen.DO)
	return e
}
