// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newFavourite(db *gorm.DB, opts ...gen.DOOption) favourite {
	_favourite := favourite{}

	_favourite.favouriteDo.UseDB(db, opts...)
	_favourite.favouriteDo.UseModel(&model.Favourite{})

	tableName := _favourite.favouriteDo.TableName()
	_favourite.ALL = field.NewAsterisk(tableName)
	_favourite.ProfileID = field.NewField(tableName, "profile_id")
	_favourite.ItemID = field.NewField(tableName, "item_id")
	_favourite.AddedAt = field.NewTime(tableName, "added_at")

	_favourite.fillFieldMap()

	return _favourite
}

type favourite struct {
	favouriteDo favouriteDo

	ALL       field.Asterisk
	ProfileID field.Field
	ItemID    field.Field
	AddedAt   field.Time

	fieldMap map[string]field.Expr
}

func (f favourite) Table(newTableName string) *favourite {
	f.favouriteDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f favourite) As(alias string) *favourite {
	f.favouriteDo.DO = *(f.favouriteDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *favourite) updateTableName(table string) *favourite {
	f.ALL = field.NewAsterisk(table)
	f.ProfileID = field.NewField(table, "profile_id")
	f.ItemID = field.NewField(table, "item_id")
	f.AddedAt = field.NewTime(table, "added_at")

	f.fillFieldMap()

	return f
}

func (f *favourite) WithContext(ctx context.Context) IFavouriteDo {
	return f.favouriteDo.WithContext(ctx)
}

func (f favourite) TableName() string { return f.favouriteDo.TableName() }

func (f favourite) Alias() string { return f.favouriteDo.Alias() }

func (f favourite) Columns(cols ...field.Expr) gen.Columns { return f.favouriteDo.Columns(cols...) }

func (f *favourite) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *favourite) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 3)
	f.fieldMap["profile_id"] = f.ProfileID
	f.fieldMap["item_id"] = f.ItemID
	f.fieldMap["added_at"] = f.AddedAt
}

func (f favourite) clone(db *gorm.DB) favourite {
	f.favouriteDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f favourite) replaceDB(db *gorm.DB) favourite {
	f.favouriteDo.ReplaceDB(db)
	return f
}

type favouriteDo struct{ gen.DO }

type IFavouriteDo interface {
	gen.SubQuery
	Debug() IFavouriteDo
	WithContext(ctx context.Context) IFavouriteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFavouriteDo
	WriteDB() IFavouriteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFavouriteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFavouriteDo
	Not(conds ...gen.Condition) IFavouriteDo
	Or(conds ...gen.Condition) IFavouriteDo
	Select(conds ...field.Expr) IFavouriteDo
	Where(conds ...gen.Condition) IFavouriteDo
	Order(conds ...field.Expr) IFavouriteDo
	Distinct(cols ...field.Expr) IFavouriteDo
	Omit(cols ...field.Expr) IFavouriteDo
	Join(table schema.Tabler, on ...field.Expr) IFavouriteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFavouriteDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFavouriteDo
	Group(cols ...field.Expr) IFavouriteDo
	Having(conds ...gen.Condition) IFavouriteDo
	Limit(limit int) IFavouriteDo
	Offset(offset int) IFavouriteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFavouriteDo
	Unscoped() IFavouriteDo
	Create(values ...*model.Favourite) error
	CreateInBatches(values []*model.Favourite, batchSize int) error
	Save(values ...*model.Favourite) error
	First() (*model.Favourite, error)
	Take() (*model.Favourite, error)
	Last() (*model.Favourite, error)
	Find() ([]*model.Favourite, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Favourite, err error)
	FindInBatches(result *[]*model.Favourite, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Favourite) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFavouriteDo
	Assign(attrs ...field.AssignExpr) IFavouriteDo
	Joins(fields ...field.RelationField) IFavouriteDo
	Preload(fields ...field.RelationField) IFavouriteDo
	FirstOrInit() (*model.Favourite, error)
	FirstOrCreate() (*model.Favourite, error)
	FindByPage(offset int, limit int) (result []*model.Favourite, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFavouriteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f favouriteDo) Debug() IFavouriteDo {
	return f.withDO(f.DO.Debug())
}

func (f favouriteDo) WithContext(ctx context.Context) IFavouriteDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f favouriteDo) ReadDB() IFavouriteDo {
	return f.Clauses(dbresolver.Read)
}

func (f favouriteDo) WriteDB() IFavouriteDo {
	return f.Clauses(dbresolver.Write)
}

func (f favouriteDo) Session(config *gorm.Session) IFavouriteDo {
	return f.withDO(f.DO.Session(config))
}

func (f favouriteDo) Clauses(conds ...clause.Expression) IFavouriteDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f favouriteDo) Returning(value interface{}, columns ...string) IFavouriteDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f favouriteDo) Not(conds ...gen.Condition) IFavouriteDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f favouriteDo) Or(conds ...gen.Condition) IFavouriteDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f favouriteDo) Select(conds ...field.Expr) IFavouriteDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f favouriteDo) Where(conds ...gen.Condition) IFavouriteDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f favouriteDo) Order(conds ...field.Expr) IFavouriteDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f favouriteDo) Distinct(cols ...field.Expr) IFavouriteDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f favouriteDo) Omit(cols ...field.Expr) IFavouriteDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f favouriteDo) Join(table schema.Tabler, on ...field.Expr) IFavouriteDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f favouriteDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFavouriteDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f favouriteDo) RightJoin(table schema.Tabler, on ...field.Expr) IFavouriteDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f favouriteDo) Group(cols ...field.Expr) IFavouriteDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f favouriteDo) Having(conds ...gen.Condition) IFavouriteDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f favouriteDo) Limit(limit int) IFavouriteDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f favouriteDo) Offset(offset int) IFavouriteDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f favouriteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFavouriteDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f favouriteDo) Unscoped() IFavouriteDo {
	return f.withDO(f.DO.Unscoped())
}

func (f favouriteDo) Create(values ...*model.Favourite) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f favouriteDo) CreateInBatches(values []*model.Favourite, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f favouriteDo) Save(values ...*model.Favourite) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f favouriteDo) First() (*model.Favourite, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Favourite), nil
	}
}

func (f favouriteDo) Take() (*model.Favourite, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Favourite), nil
	}
}

func (f favouriteDo) Last() (*model.Favourite, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Favourite), nil
	}
}

func (f favouriteDo) Find() ([]*model.Favourite, error) {
	result, err := f.DO.Find()
	return result.([]*model.Favourite), err
}

func (f favouriteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Favourite, err error) {
	buf := make([]*model.Favourite, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f favouriteDo) FindInBatches(result *[]*model.Favourite, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f favouriteDo) Attrs(attrs ...field.AssignExpr) IFavouriteDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f favouriteDo) Assign(attrs ...field.AssignExpr) IFavouriteDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f favouriteDo) Joins(fields ...field.RelationField) IFavouriteDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f favouriteDo) Preload(fields ...field.RelationField) IFavouriteDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f favouriteDo) FirstOrInit() (*model.Favourite, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Favourite), nil
	}
}

func (f favouriteDo) FirstOrCreate() (*model.Favourite, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Favourite), nil
	}
}

func (f favouriteDo) FindByPage(offset int, limit int) (result []*model.Favourite, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f favouriteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f favouriteDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f favouriteDo) Delete(models ...*model.Favourite) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *favouriteDo) withDO(do gen.Dao) *favouriteDo {
	f.DO = *do.(*gen.DO)
	return f
}
