// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newFolder(db *gorm.DB, opts ...gen.DOOption) folder {
	_folder := folder{}

	_folder.folderDo.UseDB(db, opts...)
	_folder.folderDo.UseModel(&model.Folder{})

	tableName := _folder.folderDo.TableName()
	_folder.ALL = field.NewAsterisk(tableName)
	_folder.LibraryID = field.NewField(tableName, "library_id")
	_folder.Path = field.NewString(tableName, "path")
	_folder.Fingerprint = field.NewBytes(tableName, "fingerprint")

	_folder.fillFieldMap()

	return _folder
}

type folder struct {
	folderDo folderDo

	ALL         field.Asterisk
	LibraryID   field.Field
	Path        field.String
	Fingerprint field.Bytes

	fieldMap map[string]field.Expr
}

func (f folder) Table(newTableName string) *folder {
	f.folderDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f folder) As(alias string) *folder {
	f.folderDo.DO = *(f.folderDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *folder) updateTableName(table string) *folder {
	f.ALL = field.NewAsterisk(table)
	f.LibraryID = field.NewField(table, "library_id")
	f.Path = field.NewString(table, "path")
	f.Fingerprint = field.NewBytes(table, "fingerprint")

	f.fillFieldMap()

	return f
}

func (f *folder) WithContext(ctx context.Context) IFolderDo { return f.folderDo.WithContext(ctx) }

func (f folder) TableName() string { return f.folderDo.TableName() }

func (f folder) Alias() string { return f.folderDo.Alias() }

func (f folder) Columns(cols ...field.Expr) gen.Columns { return f.folderDo.Columns(cols...) }

func (f *folder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *folder) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 3)
	f.fieldMap["library_id"] = f.LibraryID
	f.fieldMap["path"] = f.Path
	f.fieldMap["fingerprint"] = f.Fingerprint
}

func (f folder) clone(db *gorm.DB) folder {
	f.folderDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f folder) replaceDB(db *gorm.DB) folder {
	f.folderDo.ReplaceDB(db)
	return f
}

type folderDo struct{ gen.DO }

type IFolderDo interface {
	gen.SubQuery
	Debug() IFolderDo
	WithContext(ctx context.Context) IFolderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFolderDo
	WriteDB() IFolderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFolderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFolderDo
	Not(conds ...gen.Condition) IFolderDo
	Or(conds ...gen.Condition) IFolderDo
	Select(conds ...field.Expr) IFolderDo
	Where(conds ...gen.Condition) IFolderDo
	Order(conds ...field.Expr) IFolderDo
	Distinct(cols ...field.Expr) IFolderDo
	Omit(cols ...field.Expr) IFolderDo
	Join(table schema.Tabler, on ...field.Expr) IFolderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFolderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFolderDo
	Group(cols ...field.Expr) IFolderDo
	Having(conds ...gen.Condition) IFolderDo
	Limit(limit int) IFolderDo
	Offset(offset int) IFolderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFolderDo
	Unscoped() IFolderDo
	Create(values ...*model.Folder) error
	CreateInBatches(values []*model.Folder, batchSize int) error
	Save(values ...*model.Folder) error
	First() (*model.Folder, error)
	Take() (*model.Folder, error)
	Last() (*model.Folder, error)
	Find() ([]*model.Folder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Folder, err error)
	FindInBatches(result *[]*model.Folder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Folder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFolderDo
	Assign(attrs ...field.AssignExpr) IFolderDo
	Joins(fields ...field.RelationField) IFolderDo
	Preload(fields ...field.RelationField) IFolderDo
	FirstOrInit() (*model.Folder, error)
	FirstOrCreate() (*model.Folder, error)
	FindByPage(offset int, limit int) (result []*model.Folder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFolderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f folderDo) Debug() IFolderDo {
	return f.withDO(f.DO.Debug())
}

func (f folderDo) WithContext(ctx context.Context) IFolderDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f folderDo) ReadDB() IFolderDo {
	return f.Clauses(dbresolver.Read)
}

func (f folderDo) WriteDB() IFolderDo {
	return f.Clauses(dbresolver.Write)
}

func (f folderDo) Session(config *gorm.Session) IFolderDo {
	return f.withDO(f.DO.Session(config))
}

func (f folderDo) Clauses(conds ...clause.Expression) IFolderDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f folderDo) Returning(value interface{}, columns ...string) IFolderDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f folderDo) Not(conds ...gen.Condition) IFolderDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f folderDo) Or(conds ...gen.Condition) IFolderDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f folderDo) Select(conds ...field.Expr) IFolderDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f folderDo) Where(conds ...gen.Condition) IFolderDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f folderDo) Order(conds ...field.Expr) IFolderDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f folderDo) Distinct(cols ...field.Expr) IFolderDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f folderDo) Omit(cols ...field.Expr) IFolderDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f folderDo) Join(table schema.Tabler, on ...field.Expr) IFolderDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f folderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFolderDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f folderDo) RightJoin(table schema.Tabler, on ...field.Expr) IFolderDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f folderDo) Group(cols ...field.Expr) IFolderDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f folderDo) Having(conds ...gen.Condition) IFolderDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f folderDo) Limit(limit int) IFolderDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f folderDo) Offset(offset int) IFolderDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f folderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFolderDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f folderDo) Unscoped() IFolderDo {
	return f.withDO(f.DO.Unscoped())
}

func (f folderDo) Create(values ...*model.Folder) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f folderDo) CreateInBatches(values []*model.Folder, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f folderDo) Save(values ...*model.Folder) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f folderDo) First() (*model.Folder, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Folder), nil
	}
}

func (f folderDo) Take() (*model.Folder, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Folder), nil
	}
}

func (f folderDo) Last() (*model.Folder, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Folder), nil
	}
}

func (f folderDo) Find() ([]*model.Folder, error) {
	result, err := f.DO.Find()
	return result.([]*model.Folder), err
}

func (f folderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Folder, err error) {
	buf := make([]*model.Folder, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f folderDo) FindInBatches(result *[]*model.Folder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f folderDo) Attrs(attrs ...field.AssignExpr) IFolderDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f folderDo) Assign(attrs ...field.AssignExpr) IFolderDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f folderDo) Joins(fields ...field.RelationField) IFolderDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f folderDo) Preload(fields ...field.RelationField) IFolderDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f folderDo) FirstOrInit() (*model.Folder, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Folder), nil
	}
}

func (f folderDo) FirstOrCreate() (*model.Folder, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Folder), nil
	}
}

func (f folderDo) FindByPage(offset int, limit int) (result []*model.Folder, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f folderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f folderDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f folderDo) Delete(models ...*model.Folder) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *folderDo) withDO(do gen.Dao) *folderDo {
	f.DO = *do.(*gen.DO)
	return f
}
