// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		Activity:           newActivity(db, opts...),
		Artwork:            newArtwork(db, opts...),
		Chapter:            newChapter(db, opts...),
		Collection:         newCollection(db, opts...),
		CollectionMember:   newCollectionMember(db, opts...),
		Conversion:         newConversion(db, opts...),
		Credit:             newCredit(db, opts...),
		DeviceSession:      newDeviceSession(db, opts...),
		Download:           newDownload(db, opts...),
		ExternalID:         newExternalID(db, opts...),
		Favourite:          newFavourite(db, opts...),
		Folder:             newFolder(db, opts...),
		HomeSection:        newHomeSection(db, opts...),
		Item:               newItem(db, opts...),
		ItemField:          newItemField(db, opts...),
		Job:                newJob(db, opts...),
		Library:            newLibrary(db, opts...),
		LibraryRemoteExtra: newLibraryRemoteExtra(db, opts...),
		LibrarySource:      newLibrarySource(db, opts...),
		Marker:             newMarker(db, opts...),
		Part:               newPart(db, opts...),
		PartFile:           newPartFile(db, opts...),
		Person:             newPerson(db, opts...),
		PersonExternalID:   newPersonExternalID(db, opts...),
		Play:               newPlay(db, opts...),
		Playlist:           newPlaylist(db, opts...),
		PlaylistEntry:      newPlaylistEntry(db, opts...),
		Plugin:             newPlugin(db, opts...),
		Profile:            newProfile(db, opts...),
		ProfileLibrary:     newProfileLibrary(db, opts...),
		ProfilePreference:  newProfilePreference(db, opts...),
		Provider:           newProvider(db, opts...),
		Rating:             newRating(db, opts...),
		RemoteVideo:        newRemoteVideo(db, opts...),
		Server:             newServer(db, opts...),
		Stream:             newStream(db, opts...),
		SubtitleFile:       newSubtitleFile(db, opts...),
		TaskState:          newTaskState(db, opts...),
		Version:            newVersion(db, opts...),
		WatchState:         newWatchState(db, opts...),
		Webhook:            newWebhook(db, opts...),
		WebhookDelivery:    newWebhookDelivery(db, opts...),
		WebhookEvent:       newWebhookEvent(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Activity           activity
	Artwork            artwork
	Chapter            chapter
	Collection         collection
	CollectionMember   collectionMember
	Conversion         conversion
	Credit             credit
	DeviceSession      deviceSession
	Download           download
	ExternalID         externalID
	Favourite          favourite
	Folder             folder
	HomeSection        homeSection
	Item               item
	ItemField          itemField
	Job                job
	Library            library
	LibraryRemoteExtra libraryRemoteExtra
	LibrarySource      librarySource
	Marker             marker
	Part               part
	PartFile           partFile
	Person             person
	PersonExternalID   personExternalID
	Play               play
	Playlist           playlist
	PlaylistEntry      playlistEntry
	Plugin             plugin
	Profile            profile
	ProfileLibrary     profileLibrary
	ProfilePreference  profilePreference
	Provider           provider
	Rating             rating
	RemoteVideo        remoteVideo
	Server             server
	Stream             stream
	SubtitleFile       subtitleFile
	TaskState          taskState
	Version            version
	WatchState         watchState
	Webhook            webhook
	WebhookDelivery    webhookDelivery
	WebhookEvent       webhookEvent
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Activity:           q.Activity.clone(db),
		Artwork:            q.Artwork.clone(db),
		Chapter:            q.Chapter.clone(db),
		Collection:         q.Collection.clone(db),
		CollectionMember:   q.CollectionMember.clone(db),
		Conversion:         q.Conversion.clone(db),
		Credit:             q.Credit.clone(db),
		DeviceSession:      q.DeviceSession.clone(db),
		Download:           q.Download.clone(db),
		ExternalID:         q.ExternalID.clone(db),
		Favourite:          q.Favourite.clone(db),
		Folder:             q.Folder.clone(db),
		HomeSection:        q.HomeSection.clone(db),
		Item:               q.Item.clone(db),
		ItemField:          q.ItemField.clone(db),
		Job:                q.Job.clone(db),
		Library:            q.Library.clone(db),
		LibraryRemoteExtra: q.LibraryRemoteExtra.clone(db),
		LibrarySource:      q.LibrarySource.clone(db),
		Marker:             q.Marker.clone(db),
		Part:               q.Part.clone(db),
		PartFile:           q.PartFile.clone(db),
		Person:             q.Person.clone(db),
		PersonExternalID:   q.PersonExternalID.clone(db),
		Play:               q.Play.clone(db),
		Playlist:           q.Playlist.clone(db),
		PlaylistEntry:      q.PlaylistEntry.clone(db),
		Plugin:             q.Plugin.clone(db),
		Profile:            q.Profile.clone(db),
		ProfileLibrary:     q.ProfileLibrary.clone(db),
		ProfilePreference:  q.ProfilePreference.clone(db),
		Provider:           q.Provider.clone(db),
		Rating:             q.Rating.clone(db),
		RemoteVideo:        q.RemoteVideo.clone(db),
		Server:             q.Server.clone(db),
		Stream:             q.Stream.clone(db),
		SubtitleFile:       q.SubtitleFile.clone(db),
		TaskState:          q.TaskState.clone(db),
		Version:            q.Version.clone(db),
		WatchState:         q.WatchState.clone(db),
		Webhook:            q.Webhook.clone(db),
		WebhookDelivery:    q.WebhookDelivery.clone(db),
		WebhookEvent:       q.WebhookEvent.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Activity:           q.Activity.replaceDB(db),
		Artwork:            q.Artwork.replaceDB(db),
		Chapter:            q.Chapter.replaceDB(db),
		Collection:         q.Collection.replaceDB(db),
		CollectionMember:   q.CollectionMember.replaceDB(db),
		Conversion:         q.Conversion.replaceDB(db),
		Credit:             q.Credit.replaceDB(db),
		DeviceSession:      q.DeviceSession.replaceDB(db),
		Download:           q.Download.replaceDB(db),
		ExternalID:         q.ExternalID.replaceDB(db),
		Favourite:          q.Favourite.replaceDB(db),
		Folder:             q.Folder.replaceDB(db),
		HomeSection:        q.HomeSection.replaceDB(db),
		Item:               q.Item.replaceDB(db),
		ItemField:          q.ItemField.replaceDB(db),
		Job:                q.Job.replaceDB(db),
		Library:            q.Library.replaceDB(db),
		LibraryRemoteExtra: q.LibraryRemoteExtra.replaceDB(db),
		LibrarySource:      q.LibrarySource.replaceDB(db),
		Marker:             q.Marker.replaceDB(db),
		Part:               q.Part.replaceDB(db),
		PartFile:           q.PartFile.replaceDB(db),
		Person:             q.Person.replaceDB(db),
		PersonExternalID:   q.PersonExternalID.replaceDB(db),
		Play:               q.Play.replaceDB(db),
		Playlist:           q.Playlist.replaceDB(db),
		PlaylistEntry:      q.PlaylistEntry.replaceDB(db),
		Plugin:             q.Plugin.replaceDB(db),
		Profile:            q.Profile.replaceDB(db),
		ProfileLibrary:     q.ProfileLibrary.replaceDB(db),
		ProfilePreference:  q.ProfilePreference.replaceDB(db),
		Provider:           q.Provider.replaceDB(db),
		Rating:             q.Rating.replaceDB(db),
		RemoteVideo:        q.RemoteVideo.replaceDB(db),
		Server:             q.Server.replaceDB(db),
		Stream:             q.Stream.replaceDB(db),
		SubtitleFile:       q.SubtitleFile.replaceDB(db),
		TaskState:          q.TaskState.replaceDB(db),
		Version:            q.Version.replaceDB(db),
		WatchState:         q.WatchState.replaceDB(db),
		Webhook:            q.Webhook.replaceDB(db),
		WebhookDelivery:    q.WebhookDelivery.replaceDB(db),
		WebhookEvent:       q.WebhookEvent.replaceDB(db),
	}
}

type queryCtx struct {
	Activity           IActivityDo
	Artwork            IArtworkDo
	Chapter            IChapterDo
	Collection         ICollectionDo
	CollectionMember   ICollectionMemberDo
	Conversion         IConversionDo
	Credit             ICreditDo
	DeviceSession      IDeviceSessionDo
	Download           IDownloadDo
	ExternalID         IExternalIDDo
	Favourite          IFavouriteDo
	Folder             IFolderDo
	HomeSection        IHomeSectionDo
	Item               IItemDo
	ItemField          IItemFieldDo
	Job                IJobDo
	Library            ILibraryDo
	LibraryRemoteExtra ILibraryRemoteExtraDo
	LibrarySource      ILibrarySourceDo
	Marker             IMarkerDo
	Part               IPartDo
	PartFile           IPartFileDo
	Person             IPersonDo
	PersonExternalID   IPersonExternalIDDo
	Play               IPlayDo
	Playlist           IPlaylistDo
	PlaylistEntry      IPlaylistEntryDo
	Plugin             IPluginDo
	Profile            IProfileDo
	ProfileLibrary     IProfileLibraryDo
	ProfilePreference  IProfilePreferenceDo
	Provider           IProviderDo
	Rating             IRatingDo
	RemoteVideo        IRemoteVideoDo
	Server             IServerDo
	Stream             IStreamDo
	SubtitleFile       ISubtitleFileDo
	TaskState          ITaskStateDo
	Version            IVersionDo
	WatchState         IWatchStateDo
	Webhook            IWebhookDo
	WebhookDelivery    IWebhookDeliveryDo
	WebhookEvent       IWebhookEventDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Activity:           q.Activity.WithContext(ctx),
		Artwork:            q.Artwork.WithContext(ctx),
		Chapter:            q.Chapter.WithContext(ctx),
		Collection:         q.Collection.WithContext(ctx),
		CollectionMember:   q.CollectionMember.WithContext(ctx),
		Conversion:         q.Conversion.WithContext(ctx),
		Credit:             q.Credit.WithContext(ctx),
		DeviceSession:      q.DeviceSession.WithContext(ctx),
		Download:           q.Download.WithContext(ctx),
		ExternalID:         q.ExternalID.WithContext(ctx),
		Favourite:          q.Favourite.WithContext(ctx),
		Folder:             q.Folder.WithContext(ctx),
		HomeSection:        q.HomeSection.WithContext(ctx),
		Item:               q.Item.WithContext(ctx),
		ItemField:          q.ItemField.WithContext(ctx),
		Job:                q.Job.WithContext(ctx),
		Library:            q.Library.WithContext(ctx),
		LibraryRemoteExtra: q.LibraryRemoteExtra.WithContext(ctx),
		LibrarySource:      q.LibrarySource.WithContext(ctx),
		Marker:             q.Marker.WithContext(ctx),
		Part:               q.Part.WithContext(ctx),
		PartFile:           q.PartFile.WithContext(ctx),
		Person:             q.Person.WithContext(ctx),
		PersonExternalID:   q.PersonExternalID.WithContext(ctx),
		Play:               q.Play.WithContext(ctx),
		Playlist:           q.Playlist.WithContext(ctx),
		PlaylistEntry:      q.PlaylistEntry.WithContext(ctx),
		Plugin:             q.Plugin.WithContext(ctx),
		Profile:            q.Profile.WithContext(ctx),
		ProfileLibrary:     q.ProfileLibrary.WithContext(ctx),
		ProfilePreference:  q.ProfilePreference.WithContext(ctx),
		Provider:           q.Provider.WithContext(ctx),
		Rating:             q.Rating.WithContext(ctx),
		RemoteVideo:        q.RemoteVideo.WithContext(ctx),
		Server:             q.Server.WithContext(ctx),
		Stream:             q.Stream.WithContext(ctx),
		SubtitleFile:       q.SubtitleFile.WithContext(ctx),
		TaskState:          q.TaskState.WithContext(ctx),
		Version:            q.Version.WithContext(ctx),
		WatchState:         q.WatchState.WithContext(ctx),
		Webhook:            q.Webhook.WithContext(ctx),
		WebhookDelivery:    q.WebhookDelivery.WithContext(ctx),
		WebhookEvent:       q.WebhookEvent.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
