// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		Artwork:            newArtwork(db, opts...),
		Chapter:            newChapter(db, opts...),
		Collection:         newCollection(db, opts...),
		CollectionMember:   newCollectionMember(db, opts...),
		DeviceSession:      newDeviceSession(db, opts...),
		ExternalID:         newExternalID(db, opts...),
		Favourite:          newFavourite(db, opts...),
		Folder:             newFolder(db, opts...),
		Item:               newItem(db, opts...),
		ItemField:          newItemField(db, opts...),
		Job:                newJob(db, opts...),
		Library:            newLibrary(db, opts...),
		LibraryRemoteExtra: newLibraryRemoteExtra(db, opts...),
		LibrarySource:      newLibrarySource(db, opts...),
		Part:               newPart(db, opts...),
		PartFile:           newPartFile(db, opts...),
		Playlist:           newPlaylist(db, opts...),
		PlaylistEntry:      newPlaylistEntry(db, opts...),
		Profile:            newProfile(db, opts...),
		Provider:           newProvider(db, opts...),
		Rating:             newRating(db, opts...),
		RemoteVideo:        newRemoteVideo(db, opts...),
		Server:             newServer(db, opts...),
		Stream:             newStream(db, opts...),
		SubtitleFile:       newSubtitleFile(db, opts...),
		TaskState:          newTaskState(db, opts...),
		Version:            newVersion(db, opts...),
		WatchState:         newWatchState(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Artwork            artwork
	Chapter            chapter
	Collection         collection
	CollectionMember   collectionMember
	DeviceSession      deviceSession
	ExternalID         externalID
	Favourite          favourite
	Folder             folder
	Item               item
	ItemField          itemField
	Job                job
	Library            library
	LibraryRemoteExtra libraryRemoteExtra
	LibrarySource      librarySource
	Part               part
	PartFile           partFile
	Playlist           playlist
	PlaylistEntry      playlistEntry
	Profile            profile
	Provider           provider
	Rating             rating
	RemoteVideo        remoteVideo
	Server             server
	Stream             stream
	SubtitleFile       subtitleFile
	TaskState          taskState
	Version            version
	WatchState         watchState
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Artwork:            q.Artwork.clone(db),
		Chapter:            q.Chapter.clone(db),
		Collection:         q.Collection.clone(db),
		CollectionMember:   q.CollectionMember.clone(db),
		DeviceSession:      q.DeviceSession.clone(db),
		ExternalID:         q.ExternalID.clone(db),
		Favourite:          q.Favourite.clone(db),
		Folder:             q.Folder.clone(db),
		Item:               q.Item.clone(db),
		ItemField:          q.ItemField.clone(db),
		Job:                q.Job.clone(db),
		Library:            q.Library.clone(db),
		LibraryRemoteExtra: q.LibraryRemoteExtra.clone(db),
		LibrarySource:      q.LibrarySource.clone(db),
		Part:               q.Part.clone(db),
		PartFile:           q.PartFile.clone(db),
		Playlist:           q.Playlist.clone(db),
		PlaylistEntry:      q.PlaylistEntry.clone(db),
		Profile:            q.Profile.clone(db),
		Provider:           q.Provider.clone(db),
		Rating:             q.Rating.clone(db),
		RemoteVideo:        q.RemoteVideo.clone(db),
		Server:             q.Server.clone(db),
		Stream:             q.Stream.clone(db),
		SubtitleFile:       q.SubtitleFile.clone(db),
		TaskState:          q.TaskState.clone(db),
		Version:            q.Version.clone(db),
		WatchState:         q.WatchState.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Artwork:            q.Artwork.replaceDB(db),
		Chapter:            q.Chapter.replaceDB(db),
		Collection:         q.Collection.replaceDB(db),
		CollectionMember:   q.CollectionMember.replaceDB(db),
		DeviceSession:      q.DeviceSession.replaceDB(db),
		ExternalID:         q.ExternalID.replaceDB(db),
		Favourite:          q.Favourite.replaceDB(db),
		Folder:             q.Folder.replaceDB(db),
		Item:               q.Item.replaceDB(db),
		ItemField:          q.ItemField.replaceDB(db),
		Job:                q.Job.replaceDB(db),
		Library:            q.Library.replaceDB(db),
		LibraryRemoteExtra: q.LibraryRemoteExtra.replaceDB(db),
		LibrarySource:      q.LibrarySource.replaceDB(db),
		Part:               q.Part.replaceDB(db),
		PartFile:           q.PartFile.replaceDB(db),
		Playlist:           q.Playlist.replaceDB(db),
		PlaylistEntry:      q.PlaylistEntry.replaceDB(db),
		Profile:            q.Profile.replaceDB(db),
		Provider:           q.Provider.replaceDB(db),
		Rating:             q.Rating.replaceDB(db),
		RemoteVideo:        q.RemoteVideo.replaceDB(db),
		Server:             q.Server.replaceDB(db),
		Stream:             q.Stream.replaceDB(db),
		SubtitleFile:       q.SubtitleFile.replaceDB(db),
		TaskState:          q.TaskState.replaceDB(db),
		Version:            q.Version.replaceDB(db),
		WatchState:         q.WatchState.replaceDB(db),
	}
}

type queryCtx struct {
	Artwork            IArtworkDo
	Chapter            IChapterDo
	Collection         ICollectionDo
	CollectionMember   ICollectionMemberDo
	DeviceSession      IDeviceSessionDo
	ExternalID         IExternalIDDo
	Favourite          IFavouriteDo
	Folder             IFolderDo
	Item               IItemDo
	ItemField          IItemFieldDo
	Job                IJobDo
	Library            ILibraryDo
	LibraryRemoteExtra ILibraryRemoteExtraDo
	LibrarySource      ILibrarySourceDo
	Part               IPartDo
	PartFile           IPartFileDo
	Playlist           IPlaylistDo
	PlaylistEntry      IPlaylistEntryDo
	Profile            IProfileDo
	Provider           IProviderDo
	Rating             IRatingDo
	RemoteVideo        IRemoteVideoDo
	Server             IServerDo
	Stream             IStreamDo
	SubtitleFile       ISubtitleFileDo
	TaskState          ITaskStateDo
	Version            IVersionDo
	WatchState         IWatchStateDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Artwork:            q.Artwork.WithContext(ctx),
		Chapter:            q.Chapter.WithContext(ctx),
		Collection:         q.Collection.WithContext(ctx),
		CollectionMember:   q.CollectionMember.WithContext(ctx),
		DeviceSession:      q.DeviceSession.WithContext(ctx),
		ExternalID:         q.ExternalID.WithContext(ctx),
		Favourite:          q.Favourite.WithContext(ctx),
		Folder:             q.Folder.WithContext(ctx),
		Item:               q.Item.WithContext(ctx),
		ItemField:          q.ItemField.WithContext(ctx),
		Job:                q.Job.WithContext(ctx),
		Library:            q.Library.WithContext(ctx),
		LibraryRemoteExtra: q.LibraryRemoteExtra.WithContext(ctx),
		LibrarySource:      q.LibrarySource.WithContext(ctx),
		Part:               q.Part.WithContext(ctx),
		PartFile:           q.PartFile.WithContext(ctx),
		Playlist:           q.Playlist.WithContext(ctx),
		PlaylistEntry:      q.PlaylistEntry.WithContext(ctx),
		Profile:            q.Profile.WithContext(ctx),
		Provider:           q.Provider.WithContext(ctx),
		Rating:             q.Rating.WithContext(ctx),
		RemoteVideo:        q.RemoteVideo.WithContext(ctx),
		Server:             q.Server.WithContext(ctx),
		Stream:             q.Stream.WithContext(ctx),
		SubtitleFile:       q.SubtitleFile.WithContext(ctx),
		TaskState:          q.TaskState.WithContext(ctx),
		Version:            q.Version.WithContext(ctx),
		WatchState:         q.WatchState.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
