// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		Artwork:            newArtwork(db, opts...),
		Chapter:            newChapter(db, opts...),
		DeviceSession:      newDeviceSession(db, opts...),
		ExternalID:         newExternalID(db, opts...),
		Folder:             newFolder(db, opts...),
		Item:               newItem(db, opts...),
		ItemField:          newItemField(db, opts...),
		Job:                newJob(db, opts...),
		Library:            newLibrary(db, opts...),
		LibraryRemoteExtra: newLibraryRemoteExtra(db, opts...),
		LibrarySource:      newLibrarySource(db, opts...),
		Part:               newPart(db, opts...),
		PartFile:           newPartFile(db, opts...),
		Profile:            newProfile(db, opts...),
		RemoteVideo:        newRemoteVideo(db, opts...),
		Server:             newServer(db, opts...),
		Stream:             newStream(db, opts...),
		SubtitleFile:       newSubtitleFile(db, opts...),
		TaskState:          newTaskState(db, opts...),
		Version:            newVersion(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Artwork            artwork
	Chapter            chapter
	DeviceSession      deviceSession
	ExternalID         externalID
	Folder             folder
	Item               item
	ItemField          itemField
	Job                job
	Library            library
	LibraryRemoteExtra libraryRemoteExtra
	LibrarySource      librarySource
	Part               part
	PartFile           partFile
	Profile            profile
	RemoteVideo        remoteVideo
	Server             server
	Stream             stream
	SubtitleFile       subtitleFile
	TaskState          taskState
	Version            version
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Artwork:            q.Artwork.clone(db),
		Chapter:            q.Chapter.clone(db),
		DeviceSession:      q.DeviceSession.clone(db),
		ExternalID:         q.ExternalID.clone(db),
		Folder:             q.Folder.clone(db),
		Item:               q.Item.clone(db),
		ItemField:          q.ItemField.clone(db),
		Job:                q.Job.clone(db),
		Library:            q.Library.clone(db),
		LibraryRemoteExtra: q.LibraryRemoteExtra.clone(db),
		LibrarySource:      q.LibrarySource.clone(db),
		Part:               q.Part.clone(db),
		PartFile:           q.PartFile.clone(db),
		Profile:            q.Profile.clone(db),
		RemoteVideo:        q.RemoteVideo.clone(db),
		Server:             q.Server.clone(db),
		Stream:             q.Stream.clone(db),
		SubtitleFile:       q.SubtitleFile.clone(db),
		TaskState:          q.TaskState.clone(db),
		Version:            q.Version.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Artwork:            q.Artwork.replaceDB(db),
		Chapter:            q.Chapter.replaceDB(db),
		DeviceSession:      q.DeviceSession.replaceDB(db),
		ExternalID:         q.ExternalID.replaceDB(db),
		Folder:             q.Folder.replaceDB(db),
		Item:               q.Item.replaceDB(db),
		ItemField:          q.ItemField.replaceDB(db),
		Job:                q.Job.replaceDB(db),
		Library:            q.Library.replaceDB(db),
		LibraryRemoteExtra: q.LibraryRemoteExtra.replaceDB(db),
		LibrarySource:      q.LibrarySource.replaceDB(db),
		Part:               q.Part.replaceDB(db),
		PartFile:           q.PartFile.replaceDB(db),
		Profile:            q.Profile.replaceDB(db),
		RemoteVideo:        q.RemoteVideo.replaceDB(db),
		Server:             q.Server.replaceDB(db),
		Stream:             q.Stream.replaceDB(db),
		SubtitleFile:       q.SubtitleFile.replaceDB(db),
		TaskState:          q.TaskState.replaceDB(db),
		Version:            q.Version.replaceDB(db),
	}
}

type queryCtx struct {
	Artwork            IArtworkDo
	Chapter            IChapterDo
	DeviceSession      IDeviceSessionDo
	ExternalID         IExternalIDDo
	Folder             IFolderDo
	Item               IItemDo
	ItemField          IItemFieldDo
	Job                IJobDo
	Library            ILibraryDo
	LibraryRemoteExtra ILibraryRemoteExtraDo
	LibrarySource      ILibrarySourceDo
	Part               IPartDo
	PartFile           IPartFileDo
	Profile            IProfileDo
	RemoteVideo        IRemoteVideoDo
	Server             IServerDo
	Stream             IStreamDo
	SubtitleFile       ISubtitleFileDo
	TaskState          ITaskStateDo
	Version            IVersionDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Artwork:            q.Artwork.WithContext(ctx),
		Chapter:            q.Chapter.WithContext(ctx),
		DeviceSession:      q.DeviceSession.WithContext(ctx),
		ExternalID:         q.ExternalID.WithContext(ctx),
		Folder:             q.Folder.WithContext(ctx),
		Item:               q.Item.WithContext(ctx),
		ItemField:          q.ItemField.WithContext(ctx),
		Job:                q.Job.WithContext(ctx),
		Library:            q.Library.WithContext(ctx),
		LibraryRemoteExtra: q.LibraryRemoteExtra.WithContext(ctx),
		LibrarySource:      q.LibrarySource.WithContext(ctx),
		Part:               q.Part.WithContext(ctx),
		PartFile:           q.PartFile.WithContext(ctx),
		Profile:            q.Profile.WithContext(ctx),
		RemoteVideo:        q.RemoteVideo.WithContext(ctx),
		Server:             q.Server.WithContext(ctx),
		Stream:             q.Stream.WithContext(ctx),
		SubtitleFile:       q.SubtitleFile.WithContext(ctx),
		TaskState:          q.TaskState.WithContext(ctx),
		Version:            q.Version.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
