// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newHomeSection(db *gorm.DB, opts ...gen.DOOption) homeSection {
	_homeSection := homeSection{}

	_homeSection.homeSectionDo.UseDB(db, opts...)
	_homeSection.homeSectionDo.UseModel(&model.HomeSection{})

	tableName := _homeSection.homeSectionDo.TableName()
	_homeSection.ALL = field.NewAsterisk(tableName)
	_homeSection.ProfileID = field.NewField(tableName, "profile_id")
	_homeSection.HomeRow = field.NewString(tableName, "home_row")
	_homeSection.Position = field.NewInt16(tableName, "position")
	_homeSection.Visibility = field.NewString(tableName, "visibility")

	_homeSection.fillFieldMap()

	return _homeSection
}

type homeSection struct {
	homeSectionDo homeSectionDo

	ALL        field.Asterisk
	ProfileID  field.Field
	HomeRow    field.String
	Position   field.Int16
	Visibility field.String

	fieldMap map[string]field.Expr
}

func (h homeSection) Table(newTableName string) *homeSection {
	h.homeSectionDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h homeSection) As(alias string) *homeSection {
	h.homeSectionDo.DO = *(h.homeSectionDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *homeSection) updateTableName(table string) *homeSection {
	h.ALL = field.NewAsterisk(table)
	h.ProfileID = field.NewField(table, "profile_id")
	h.HomeRow = field.NewString(table, "home_row")
	h.Position = field.NewInt16(table, "position")
	h.Visibility = field.NewString(table, "visibility")

	h.fillFieldMap()

	return h
}

func (h *homeSection) WithContext(ctx context.Context) IHomeSectionDo {
	return h.homeSectionDo.WithContext(ctx)
}

func (h homeSection) TableName() string { return h.homeSectionDo.TableName() }

func (h homeSection) Alias() string { return h.homeSectionDo.Alias() }

func (h homeSection) Columns(cols ...field.Expr) gen.Columns { return h.homeSectionDo.Columns(cols...) }

func (h *homeSection) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *homeSection) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 4)
	h.fieldMap["profile_id"] = h.ProfileID
	h.fieldMap["home_row"] = h.HomeRow
	h.fieldMap["position"] = h.Position
	h.fieldMap["visibility"] = h.Visibility
}

func (h homeSection) clone(db *gorm.DB) homeSection {
	h.homeSectionDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h homeSection) replaceDB(db *gorm.DB) homeSection {
	h.homeSectionDo.ReplaceDB(db)
	return h
}

type homeSectionDo struct{ gen.DO }

type IHomeSectionDo interface {
	gen.SubQuery
	Debug() IHomeSectionDo
	WithContext(ctx context.Context) IHomeSectionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHomeSectionDo
	WriteDB() IHomeSectionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHomeSectionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHomeSectionDo
	Not(conds ...gen.Condition) IHomeSectionDo
	Or(conds ...gen.Condition) IHomeSectionDo
	Select(conds ...field.Expr) IHomeSectionDo
	Where(conds ...gen.Condition) IHomeSectionDo
	Order(conds ...field.Expr) IHomeSectionDo
	Distinct(cols ...field.Expr) IHomeSectionDo
	Omit(cols ...field.Expr) IHomeSectionDo
	Join(table schema.Tabler, on ...field.Expr) IHomeSectionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHomeSectionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHomeSectionDo
	Group(cols ...field.Expr) IHomeSectionDo
	Having(conds ...gen.Condition) IHomeSectionDo
	Limit(limit int) IHomeSectionDo
	Offset(offset int) IHomeSectionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHomeSectionDo
	Unscoped() IHomeSectionDo
	Create(values ...*model.HomeSection) error
	CreateInBatches(values []*model.HomeSection, batchSize int) error
	Save(values ...*model.HomeSection) error
	First() (*model.HomeSection, error)
	Take() (*model.HomeSection, error)
	Last() (*model.HomeSection, error)
	Find() ([]*model.HomeSection, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HomeSection, err error)
	FindInBatches(result *[]*model.HomeSection, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HomeSection) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHomeSectionDo
	Assign(attrs ...field.AssignExpr) IHomeSectionDo
	Joins(fields ...field.RelationField) IHomeSectionDo
	Preload(fields ...field.RelationField) IHomeSectionDo
	FirstOrInit() (*model.HomeSection, error)
	FirstOrCreate() (*model.HomeSection, error)
	FindByPage(offset int, limit int) (result []*model.HomeSection, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHomeSectionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h homeSectionDo) Debug() IHomeSectionDo {
	return h.withDO(h.DO.Debug())
}

func (h homeSectionDo) WithContext(ctx context.Context) IHomeSectionDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h homeSectionDo) ReadDB() IHomeSectionDo {
	return h.Clauses(dbresolver.Read)
}

func (h homeSectionDo) WriteDB() IHomeSectionDo {
	return h.Clauses(dbresolver.Write)
}

func (h homeSectionDo) Session(config *gorm.Session) IHomeSectionDo {
	return h.withDO(h.DO.Session(config))
}

func (h homeSectionDo) Clauses(conds ...clause.Expression) IHomeSectionDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h homeSectionDo) Returning(value interface{}, columns ...string) IHomeSectionDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h homeSectionDo) Not(conds ...gen.Condition) IHomeSectionDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h homeSectionDo) Or(conds ...gen.Condition) IHomeSectionDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h homeSectionDo) Select(conds ...field.Expr) IHomeSectionDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h homeSectionDo) Where(conds ...gen.Condition) IHomeSectionDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h homeSectionDo) Order(conds ...field.Expr) IHomeSectionDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h homeSectionDo) Distinct(cols ...field.Expr) IHomeSectionDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h homeSectionDo) Omit(cols ...field.Expr) IHomeSectionDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h homeSectionDo) Join(table schema.Tabler, on ...field.Expr) IHomeSectionDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h homeSectionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHomeSectionDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h homeSectionDo) RightJoin(table schema.Tabler, on ...field.Expr) IHomeSectionDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h homeSectionDo) Group(cols ...field.Expr) IHomeSectionDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h homeSectionDo) Having(conds ...gen.Condition) IHomeSectionDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h homeSectionDo) Limit(limit int) IHomeSectionDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h homeSectionDo) Offset(offset int) IHomeSectionDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h homeSectionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHomeSectionDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h homeSectionDo) Unscoped() IHomeSectionDo {
	return h.withDO(h.DO.Unscoped())
}

func (h homeSectionDo) Create(values ...*model.HomeSection) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h homeSectionDo) CreateInBatches(values []*model.HomeSection, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h homeSectionDo) Save(values ...*model.HomeSection) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h homeSectionDo) First() (*model.HomeSection, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HomeSection), nil
	}
}

func (h homeSectionDo) Take() (*model.HomeSection, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HomeSection), nil
	}
}

func (h homeSectionDo) Last() (*model.HomeSection, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HomeSection), nil
	}
}

func (h homeSectionDo) Find() ([]*model.HomeSection, error) {
	result, err := h.DO.Find()
	return result.([]*model.HomeSection), err
}

func (h homeSectionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HomeSection, err error) {
	buf := make([]*model.HomeSection, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h homeSectionDo) FindInBatches(result *[]*model.HomeSection, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h homeSectionDo) Attrs(attrs ...field.AssignExpr) IHomeSectionDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h homeSectionDo) Assign(attrs ...field.AssignExpr) IHomeSectionDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h homeSectionDo) Joins(fields ...field.RelationField) IHomeSectionDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h homeSectionDo) Preload(fields ...field.RelationField) IHomeSectionDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h homeSectionDo) FirstOrInit() (*model.HomeSection, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HomeSection), nil
	}
}

func (h homeSectionDo) FirstOrCreate() (*model.HomeSection, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HomeSection), nil
	}
}

func (h homeSectionDo) FindByPage(offset int, limit int) (result []*model.HomeSection, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h homeSectionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h homeSectionDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h homeSectionDo) Delete(models ...*model.HomeSection) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *homeSectionDo) withDO(do gen.Dao) *homeSectionDo {
	h.DO = *do.(*gen.DO)
	return h
}
