// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newItemField(db *gorm.DB, opts ...gen.DOOption) itemField {
	_itemField := itemField{}

	_itemField.itemFieldDo.UseDB(db, opts...)
	_itemField.itemFieldDo.UseModel(&model.ItemField{})

	tableName := _itemField.itemFieldDo.TableName()
	_itemField.ALL = field.NewAsterisk(tableName)
	_itemField.ItemID = field.NewField(tableName, "item_id")
	_itemField.Field = field.NewString(tableName, "field")
	_itemField.Source = field.NewString(tableName, "source")
	_itemField.UpdatedAt = field.NewTime(tableName, "updated_at")

	_itemField.fillFieldMap()

	return _itemField
}

type itemField struct {
	itemFieldDo itemFieldDo

	ALL       field.Asterisk
	ItemID    field.Field
	Field     field.String
	Source    field.String
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (i itemField) Table(newTableName string) *itemField {
	i.itemFieldDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i itemField) As(alias string) *itemField {
	i.itemFieldDo.DO = *(i.itemFieldDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *itemField) updateTableName(table string) *itemField {
	i.ALL = field.NewAsterisk(table)
	i.ItemID = field.NewField(table, "item_id")
	i.Field = field.NewString(table, "field")
	i.Source = field.NewString(table, "source")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *itemField) WithContext(ctx context.Context) IItemFieldDo {
	return i.itemFieldDo.WithContext(ctx)
}

func (i itemField) TableName() string { return i.itemFieldDo.TableName() }

func (i itemField) Alias() string { return i.itemFieldDo.Alias() }

func (i itemField) Columns(cols ...field.Expr) gen.Columns { return i.itemFieldDo.Columns(cols...) }

func (i *itemField) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *itemField) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 4)
	i.fieldMap["item_id"] = i.ItemID
	i.fieldMap["field"] = i.Field
	i.fieldMap["source"] = i.Source
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i itemField) clone(db *gorm.DB) itemField {
	i.itemFieldDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i itemField) replaceDB(db *gorm.DB) itemField {
	i.itemFieldDo.ReplaceDB(db)
	return i
}

type itemFieldDo struct{ gen.DO }

type IItemFieldDo interface {
	gen.SubQuery
	Debug() IItemFieldDo
	WithContext(ctx context.Context) IItemFieldDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IItemFieldDo
	WriteDB() IItemFieldDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IItemFieldDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IItemFieldDo
	Not(conds ...gen.Condition) IItemFieldDo
	Or(conds ...gen.Condition) IItemFieldDo
	Select(conds ...field.Expr) IItemFieldDo
	Where(conds ...gen.Condition) IItemFieldDo
	Order(conds ...field.Expr) IItemFieldDo
	Distinct(cols ...field.Expr) IItemFieldDo
	Omit(cols ...field.Expr) IItemFieldDo
	Join(table schema.Tabler, on ...field.Expr) IItemFieldDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IItemFieldDo
	RightJoin(table schema.Tabler, on ...field.Expr) IItemFieldDo
	Group(cols ...field.Expr) IItemFieldDo
	Having(conds ...gen.Condition) IItemFieldDo
	Limit(limit int) IItemFieldDo
	Offset(offset int) IItemFieldDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IItemFieldDo
	Unscoped() IItemFieldDo
	Create(values ...*model.ItemField) error
	CreateInBatches(values []*model.ItemField, batchSize int) error
	Save(values ...*model.ItemField) error
	First() (*model.ItemField, error)
	Take() (*model.ItemField, error)
	Last() (*model.ItemField, error)
	Find() ([]*model.ItemField, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ItemField, err error)
	FindInBatches(result *[]*model.ItemField, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ItemField) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IItemFieldDo
	Assign(attrs ...field.AssignExpr) IItemFieldDo
	Joins(fields ...field.RelationField) IItemFieldDo
	Preload(fields ...field.RelationField) IItemFieldDo
	FirstOrInit() (*model.ItemField, error)
	FirstOrCreate() (*model.ItemField, error)
	FindByPage(offset int, limit int) (result []*model.ItemField, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IItemFieldDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i itemFieldDo) Debug() IItemFieldDo {
	return i.withDO(i.DO.Debug())
}

func (i itemFieldDo) WithContext(ctx context.Context) IItemFieldDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i itemFieldDo) ReadDB() IItemFieldDo {
	return i.Clauses(dbresolver.Read)
}

func (i itemFieldDo) WriteDB() IItemFieldDo {
	return i.Clauses(dbresolver.Write)
}

func (i itemFieldDo) Session(config *gorm.Session) IItemFieldDo {
	return i.withDO(i.DO.Session(config))
}

func (i itemFieldDo) Clauses(conds ...clause.Expression) IItemFieldDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i itemFieldDo) Returning(value interface{}, columns ...string) IItemFieldDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i itemFieldDo) Not(conds ...gen.Condition) IItemFieldDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i itemFieldDo) Or(conds ...gen.Condition) IItemFieldDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i itemFieldDo) Select(conds ...field.Expr) IItemFieldDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i itemFieldDo) Where(conds ...gen.Condition) IItemFieldDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i itemFieldDo) Order(conds ...field.Expr) IItemFieldDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i itemFieldDo) Distinct(cols ...field.Expr) IItemFieldDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i itemFieldDo) Omit(cols ...field.Expr) IItemFieldDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i itemFieldDo) Join(table schema.Tabler, on ...field.Expr) IItemFieldDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i itemFieldDo) LeftJoin(table schema.Tabler, on ...field.Expr) IItemFieldDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i itemFieldDo) RightJoin(table schema.Tabler, on ...field.Expr) IItemFieldDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i itemFieldDo) Group(cols ...field.Expr) IItemFieldDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i itemFieldDo) Having(conds ...gen.Condition) IItemFieldDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i itemFieldDo) Limit(limit int) IItemFieldDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i itemFieldDo) Offset(offset int) IItemFieldDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i itemFieldDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IItemFieldDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i itemFieldDo) Unscoped() IItemFieldDo {
	return i.withDO(i.DO.Unscoped())
}

func (i itemFieldDo) Create(values ...*model.ItemField) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i itemFieldDo) CreateInBatches(values []*model.ItemField, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i itemFieldDo) Save(values ...*model.ItemField) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i itemFieldDo) First() (*model.ItemField, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemField), nil
	}
}

func (i itemFieldDo) Take() (*model.ItemField, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemField), nil
	}
}

func (i itemFieldDo) Last() (*model.ItemField, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemField), nil
	}
}

func (i itemFieldDo) Find() ([]*model.ItemField, error) {
	result, err := i.DO.Find()
	return result.([]*model.ItemField), err
}

func (i itemFieldDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ItemField, err error) {
	buf := make([]*model.ItemField, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i itemFieldDo) FindInBatches(result *[]*model.ItemField, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i itemFieldDo) Attrs(attrs ...field.AssignExpr) IItemFieldDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i itemFieldDo) Assign(attrs ...field.AssignExpr) IItemFieldDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i itemFieldDo) Joins(fields ...field.RelationField) IItemFieldDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i itemFieldDo) Preload(fields ...field.RelationField) IItemFieldDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i itemFieldDo) FirstOrInit() (*model.ItemField, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemField), nil
	}
}

func (i itemFieldDo) FirstOrCreate() (*model.ItemField, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemField), nil
	}
}

func (i itemFieldDo) FindByPage(offset int, limit int) (result []*model.ItemField, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i itemFieldDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i itemFieldDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i itemFieldDo) Delete(models ...*model.ItemField) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *itemFieldDo) withDO(do gen.Dao) *itemFieldDo {
	i.DO = *do.(*gen.DO)
	return i
}
