// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newLibraryRemoteExtra(db *gorm.DB, opts ...gen.DOOption) libraryRemoteExtra {
	_libraryRemoteExtra := libraryRemoteExtra{}

	_libraryRemoteExtra.libraryRemoteExtraDo.UseDB(db, opts...)
	_libraryRemoteExtra.libraryRemoteExtraDo.UseModel(&model.LibraryRemoteExtra{})

	tableName := _libraryRemoteExtra.libraryRemoteExtraDo.TableName()
	_libraryRemoteExtra.ALL = field.NewAsterisk(tableName)
	_libraryRemoteExtra.LibraryID = field.NewField(tableName, "library_id")
	_libraryRemoteExtra.Kind = field.NewString(tableName, "kind")

	_libraryRemoteExtra.fillFieldMap()

	return _libraryRemoteExtra
}

type libraryRemoteExtra struct {
	libraryRemoteExtraDo libraryRemoteExtraDo

	ALL       field.Asterisk
	LibraryID field.Field
	Kind      field.String

	fieldMap map[string]field.Expr
}

func (l libraryRemoteExtra) Table(newTableName string) *libraryRemoteExtra {
	l.libraryRemoteExtraDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l libraryRemoteExtra) As(alias string) *libraryRemoteExtra {
	l.libraryRemoteExtraDo.DO = *(l.libraryRemoteExtraDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *libraryRemoteExtra) updateTableName(table string) *libraryRemoteExtra {
	l.ALL = field.NewAsterisk(table)
	l.LibraryID = field.NewField(table, "library_id")
	l.Kind = field.NewString(table, "kind")

	l.fillFieldMap()

	return l
}

func (l *libraryRemoteExtra) WithContext(ctx context.Context) ILibraryRemoteExtraDo {
	return l.libraryRemoteExtraDo.WithContext(ctx)
}

func (l libraryRemoteExtra) TableName() string { return l.libraryRemoteExtraDo.TableName() }

func (l libraryRemoteExtra) Alias() string { return l.libraryRemoteExtraDo.Alias() }

func (l libraryRemoteExtra) Columns(cols ...field.Expr) gen.Columns {
	return l.libraryRemoteExtraDo.Columns(cols...)
}

func (l *libraryRemoteExtra) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *libraryRemoteExtra) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 2)
	l.fieldMap["library_id"] = l.LibraryID
	l.fieldMap["kind"] = l.Kind
}

func (l libraryRemoteExtra) clone(db *gorm.DB) libraryRemoteExtra {
	l.libraryRemoteExtraDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l libraryRemoteExtra) replaceDB(db *gorm.DB) libraryRemoteExtra {
	l.libraryRemoteExtraDo.ReplaceDB(db)
	return l
}

type libraryRemoteExtraDo struct{ gen.DO }

type ILibraryRemoteExtraDo interface {
	gen.SubQuery
	Debug() ILibraryRemoteExtraDo
	WithContext(ctx context.Context) ILibraryRemoteExtraDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILibraryRemoteExtraDo
	WriteDB() ILibraryRemoteExtraDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILibraryRemoteExtraDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILibraryRemoteExtraDo
	Not(conds ...gen.Condition) ILibraryRemoteExtraDo
	Or(conds ...gen.Condition) ILibraryRemoteExtraDo
	Select(conds ...field.Expr) ILibraryRemoteExtraDo
	Where(conds ...gen.Condition) ILibraryRemoteExtraDo
	Order(conds ...field.Expr) ILibraryRemoteExtraDo
	Distinct(cols ...field.Expr) ILibraryRemoteExtraDo
	Omit(cols ...field.Expr) ILibraryRemoteExtraDo
	Join(table schema.Tabler, on ...field.Expr) ILibraryRemoteExtraDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILibraryRemoteExtraDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILibraryRemoteExtraDo
	Group(cols ...field.Expr) ILibraryRemoteExtraDo
	Having(conds ...gen.Condition) ILibraryRemoteExtraDo
	Limit(limit int) ILibraryRemoteExtraDo
	Offset(offset int) ILibraryRemoteExtraDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILibraryRemoteExtraDo
	Unscoped() ILibraryRemoteExtraDo
	Create(values ...*model.LibraryRemoteExtra) error
	CreateInBatches(values []*model.LibraryRemoteExtra, batchSize int) error
	Save(values ...*model.LibraryRemoteExtra) error
	First() (*model.LibraryRemoteExtra, error)
	Take() (*model.LibraryRemoteExtra, error)
	Last() (*model.LibraryRemoteExtra, error)
	Find() ([]*model.LibraryRemoteExtra, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LibraryRemoteExtra, err error)
	FindInBatches(result *[]*model.LibraryRemoteExtra, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LibraryRemoteExtra) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILibraryRemoteExtraDo
	Assign(attrs ...field.AssignExpr) ILibraryRemoteExtraDo
	Joins(fields ...field.RelationField) ILibraryRemoteExtraDo
	Preload(fields ...field.RelationField) ILibraryRemoteExtraDo
	FirstOrInit() (*model.LibraryRemoteExtra, error)
	FirstOrCreate() (*model.LibraryRemoteExtra, error)
	FindByPage(offset int, limit int) (result []*model.LibraryRemoteExtra, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILibraryRemoteExtraDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l libraryRemoteExtraDo) Debug() ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Debug())
}

func (l libraryRemoteExtraDo) WithContext(ctx context.Context) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l libraryRemoteExtraDo) ReadDB() ILibraryRemoteExtraDo {
	return l.Clauses(dbresolver.Read)
}

func (l libraryRemoteExtraDo) WriteDB() ILibraryRemoteExtraDo {
	return l.Clauses(dbresolver.Write)
}

func (l libraryRemoteExtraDo) Session(config *gorm.Session) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Session(config))
}

func (l libraryRemoteExtraDo) Clauses(conds ...clause.Expression) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l libraryRemoteExtraDo) Returning(value interface{}, columns ...string) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l libraryRemoteExtraDo) Not(conds ...gen.Condition) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l libraryRemoteExtraDo) Or(conds ...gen.Condition) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l libraryRemoteExtraDo) Select(conds ...field.Expr) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l libraryRemoteExtraDo) Where(conds ...gen.Condition) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l libraryRemoteExtraDo) Order(conds ...field.Expr) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l libraryRemoteExtraDo) Distinct(cols ...field.Expr) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l libraryRemoteExtraDo) Omit(cols ...field.Expr) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l libraryRemoteExtraDo) Join(table schema.Tabler, on ...field.Expr) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l libraryRemoteExtraDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l libraryRemoteExtraDo) RightJoin(table schema.Tabler, on ...field.Expr) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l libraryRemoteExtraDo) Group(cols ...field.Expr) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l libraryRemoteExtraDo) Having(conds ...gen.Condition) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l libraryRemoteExtraDo) Limit(limit int) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l libraryRemoteExtraDo) Offset(offset int) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l libraryRemoteExtraDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l libraryRemoteExtraDo) Unscoped() ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Unscoped())
}

func (l libraryRemoteExtraDo) Create(values ...*model.LibraryRemoteExtra) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l libraryRemoteExtraDo) CreateInBatches(values []*model.LibraryRemoteExtra, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l libraryRemoteExtraDo) Save(values ...*model.LibraryRemoteExtra) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l libraryRemoteExtraDo) First() (*model.LibraryRemoteExtra, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LibraryRemoteExtra), nil
	}
}

func (l libraryRemoteExtraDo) Take() (*model.LibraryRemoteExtra, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LibraryRemoteExtra), nil
	}
}

func (l libraryRemoteExtraDo) Last() (*model.LibraryRemoteExtra, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LibraryRemoteExtra), nil
	}
}

func (l libraryRemoteExtraDo) Find() ([]*model.LibraryRemoteExtra, error) {
	result, err := l.DO.Find()
	return result.([]*model.LibraryRemoteExtra), err
}

func (l libraryRemoteExtraDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LibraryRemoteExtra, err error) {
	buf := make([]*model.LibraryRemoteExtra, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l libraryRemoteExtraDo) FindInBatches(result *[]*model.LibraryRemoteExtra, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l libraryRemoteExtraDo) Attrs(attrs ...field.AssignExpr) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l libraryRemoteExtraDo) Assign(attrs ...field.AssignExpr) ILibraryRemoteExtraDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l libraryRemoteExtraDo) Joins(fields ...field.RelationField) ILibraryRemoteExtraDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l libraryRemoteExtraDo) Preload(fields ...field.RelationField) ILibraryRemoteExtraDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l libraryRemoteExtraDo) FirstOrInit() (*model.LibraryRemoteExtra, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LibraryRemoteExtra), nil
	}
}

func (l libraryRemoteExtraDo) FirstOrCreate() (*model.LibraryRemoteExtra, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LibraryRemoteExtra), nil
	}
}

func (l libraryRemoteExtraDo) FindByPage(offset int, limit int) (result []*model.LibraryRemoteExtra, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l libraryRemoteExtraDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l libraryRemoteExtraDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l libraryRemoteExtraDo) Delete(models ...*model.LibraryRemoteExtra) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *libraryRemoteExtraDo) withDO(do gen.Dao) *libraryRemoteExtraDo {
	l.DO = *do.(*gen.DO)
	return l
}
