// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newLibrarySource(db *gorm.DB, opts ...gen.DOOption) librarySource {
	_librarySource := librarySource{}

	_librarySource.librarySourceDo.UseDB(db, opts...)
	_librarySource.librarySourceDo.UseModel(&model.LibrarySource{})

	tableName := _librarySource.librarySourceDo.TableName()
	_librarySource.ALL = field.NewAsterisk(tableName)
	_librarySource.LibraryID = field.NewField(tableName, "library_id")
	_librarySource.Source = field.NewString(tableName, "source")
	_librarySource.Position = field.NewInt(tableName, "position")

	_librarySource.fillFieldMap()

	return _librarySource
}

type librarySource struct {
	librarySourceDo librarySourceDo

	ALL       field.Asterisk
	LibraryID field.Field
	Source    field.String
	Position  field.Int

	fieldMap map[string]field.Expr
}

func (l librarySource) Table(newTableName string) *librarySource {
	l.librarySourceDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l librarySource) As(alias string) *librarySource {
	l.librarySourceDo.DO = *(l.librarySourceDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *librarySource) updateTableName(table string) *librarySource {
	l.ALL = field.NewAsterisk(table)
	l.LibraryID = field.NewField(table, "library_id")
	l.Source = field.NewString(table, "source")
	l.Position = field.NewInt(table, "position")

	l.fillFieldMap()

	return l
}

func (l *librarySource) WithContext(ctx context.Context) ILibrarySourceDo {
	return l.librarySourceDo.WithContext(ctx)
}

func (l librarySource) TableName() string { return l.librarySourceDo.TableName() }

func (l librarySource) Alias() string { return l.librarySourceDo.Alias() }

func (l librarySource) Columns(cols ...field.Expr) gen.Columns {
	return l.librarySourceDo.Columns(cols...)
}

func (l *librarySource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *librarySource) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 3)
	l.fieldMap["library_id"] = l.LibraryID
	l.fieldMap["source"] = l.Source
	l.fieldMap["position"] = l.Position
}

func (l librarySource) clone(db *gorm.DB) librarySource {
	l.librarySourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l librarySource) replaceDB(db *gorm.DB) librarySource {
	l.librarySourceDo.ReplaceDB(db)
	return l
}

type librarySourceDo struct{ gen.DO }

type ILibrarySourceDo interface {
	gen.SubQuery
	Debug() ILibrarySourceDo
	WithContext(ctx context.Context) ILibrarySourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILibrarySourceDo
	WriteDB() ILibrarySourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILibrarySourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILibrarySourceDo
	Not(conds ...gen.Condition) ILibrarySourceDo
	Or(conds ...gen.Condition) ILibrarySourceDo
	Select(conds ...field.Expr) ILibrarySourceDo
	Where(conds ...gen.Condition) ILibrarySourceDo
	Order(conds ...field.Expr) ILibrarySourceDo
	Distinct(cols ...field.Expr) ILibrarySourceDo
	Omit(cols ...field.Expr) ILibrarySourceDo
	Join(table schema.Tabler, on ...field.Expr) ILibrarySourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILibrarySourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILibrarySourceDo
	Group(cols ...field.Expr) ILibrarySourceDo
	Having(conds ...gen.Condition) ILibrarySourceDo
	Limit(limit int) ILibrarySourceDo
	Offset(offset int) ILibrarySourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILibrarySourceDo
	Unscoped() ILibrarySourceDo
	Create(values ...*model.LibrarySource) error
	CreateInBatches(values []*model.LibrarySource, batchSize int) error
	Save(values ...*model.LibrarySource) error
	First() (*model.LibrarySource, error)
	Take() (*model.LibrarySource, error)
	Last() (*model.LibrarySource, error)
	Find() ([]*model.LibrarySource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LibrarySource, err error)
	FindInBatches(result *[]*model.LibrarySource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LibrarySource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILibrarySourceDo
	Assign(attrs ...field.AssignExpr) ILibrarySourceDo
	Joins(fields ...field.RelationField) ILibrarySourceDo
	Preload(fields ...field.RelationField) ILibrarySourceDo
	FirstOrInit() (*model.LibrarySource, error)
	FirstOrCreate() (*model.LibrarySource, error)
	FindByPage(offset int, limit int) (result []*model.LibrarySource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILibrarySourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l librarySourceDo) Debug() ILibrarySourceDo {
	return l.withDO(l.DO.Debug())
}

func (l librarySourceDo) WithContext(ctx context.Context) ILibrarySourceDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l librarySourceDo) ReadDB() ILibrarySourceDo {
	return l.Clauses(dbresolver.Read)
}

func (l librarySourceDo) WriteDB() ILibrarySourceDo {
	return l.Clauses(dbresolver.Write)
}

func (l librarySourceDo) Session(config *gorm.Session) ILibrarySourceDo {
	return l.withDO(l.DO.Session(config))
}

func (l librarySourceDo) Clauses(conds ...clause.Expression) ILibrarySourceDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l librarySourceDo) Returning(value interface{}, columns ...string) ILibrarySourceDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l librarySourceDo) Not(conds ...gen.Condition) ILibrarySourceDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l librarySourceDo) Or(conds ...gen.Condition) ILibrarySourceDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l librarySourceDo) Select(conds ...field.Expr) ILibrarySourceDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l librarySourceDo) Where(conds ...gen.Condition) ILibrarySourceDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l librarySourceDo) Order(conds ...field.Expr) ILibrarySourceDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l librarySourceDo) Distinct(cols ...field.Expr) ILibrarySourceDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l librarySourceDo) Omit(cols ...field.Expr) ILibrarySourceDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l librarySourceDo) Join(table schema.Tabler, on ...field.Expr) ILibrarySourceDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l librarySourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILibrarySourceDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l librarySourceDo) RightJoin(table schema.Tabler, on ...field.Expr) ILibrarySourceDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l librarySourceDo) Group(cols ...field.Expr) ILibrarySourceDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l librarySourceDo) Having(conds ...gen.Condition) ILibrarySourceDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l librarySourceDo) Limit(limit int) ILibrarySourceDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l librarySourceDo) Offset(offset int) ILibrarySourceDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l librarySourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILibrarySourceDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l librarySourceDo) Unscoped() ILibrarySourceDo {
	return l.withDO(l.DO.Unscoped())
}

func (l librarySourceDo) Create(values ...*model.LibrarySource) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l librarySourceDo) CreateInBatches(values []*model.LibrarySource, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l librarySourceDo) Save(values ...*model.LibrarySource) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l librarySourceDo) First() (*model.LibrarySource, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LibrarySource), nil
	}
}

func (l librarySourceDo) Take() (*model.LibrarySource, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LibrarySource), nil
	}
}

func (l librarySourceDo) Last() (*model.LibrarySource, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LibrarySource), nil
	}
}

func (l librarySourceDo) Find() ([]*model.LibrarySource, error) {
	result, err := l.DO.Find()
	return result.([]*model.LibrarySource), err
}

func (l librarySourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LibrarySource, err error) {
	buf := make([]*model.LibrarySource, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l librarySourceDo) FindInBatches(result *[]*model.LibrarySource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l librarySourceDo) Attrs(attrs ...field.AssignExpr) ILibrarySourceDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l librarySourceDo) Assign(attrs ...field.AssignExpr) ILibrarySourceDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l librarySourceDo) Joins(fields ...field.RelationField) ILibrarySourceDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l librarySourceDo) Preload(fields ...field.RelationField) ILibrarySourceDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l librarySourceDo) FirstOrInit() (*model.LibrarySource, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LibrarySource), nil
	}
}

func (l librarySourceDo) FirstOrCreate() (*model.LibrarySource, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LibrarySource), nil
	}
}

func (l librarySourceDo) FindByPage(offset int, limit int) (result []*model.LibrarySource, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l librarySourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l librarySourceDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l librarySourceDo) Delete(models ...*model.LibrarySource) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *librarySourceDo) withDO(do gen.Dao) *librarySourceDo {
	l.DO = *do.(*gen.DO)
	return l
}
