// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newPartFile(db *gorm.DB, opts ...gen.DOOption) partFile {
	_partFile := partFile{}

	_partFile.partFileDo.UseDB(db, opts...)
	_partFile.partFileDo.UseModel(&model.PartFile{})

	tableName := _partFile.partFileDo.TableName()
	_partFile.ALL = field.NewAsterisk(tableName)
	_partFile.PartID = field.NewField(tableName, "part_id")
	_partFile.LibraryID = field.NewField(tableName, "library_id")
	_partFile.RelPath = field.NewString(tableName, "rel_path")
	_partFile.SizeBytes = field.NewInt64(tableName, "size_bytes")
	_partFile.MtimeNS = field.NewInt64(tableName, "mtime_ns")

	_partFile.fillFieldMap()

	return _partFile
}

type partFile struct {
	partFileDo partFileDo

	ALL       field.Asterisk
	PartID    field.Field
	LibraryID field.Field
	RelPath   field.String
	SizeBytes field.Int64
	MtimeNS   field.Int64

	fieldMap map[string]field.Expr
}

func (p partFile) Table(newTableName string) *partFile {
	p.partFileDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p partFile) As(alias string) *partFile {
	p.partFileDo.DO = *(p.partFileDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *partFile) updateTableName(table string) *partFile {
	p.ALL = field.NewAsterisk(table)
	p.PartID = field.NewField(table, "part_id")
	p.LibraryID = field.NewField(table, "library_id")
	p.RelPath = field.NewString(table, "rel_path")
	p.SizeBytes = field.NewInt64(table, "size_bytes")
	p.MtimeNS = field.NewInt64(table, "mtime_ns")

	p.fillFieldMap()

	return p
}

func (p *partFile) WithContext(ctx context.Context) IPartFileDo { return p.partFileDo.WithContext(ctx) }

func (p partFile) TableName() string { return p.partFileDo.TableName() }

func (p partFile) Alias() string { return p.partFileDo.Alias() }

func (p partFile) Columns(cols ...field.Expr) gen.Columns { return p.partFileDo.Columns(cols...) }

func (p *partFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *partFile) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["part_id"] = p.PartID
	p.fieldMap["library_id"] = p.LibraryID
	p.fieldMap["rel_path"] = p.RelPath
	p.fieldMap["size_bytes"] = p.SizeBytes
	p.fieldMap["mtime_ns"] = p.MtimeNS
}

func (p partFile) clone(db *gorm.DB) partFile {
	p.partFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p partFile) replaceDB(db *gorm.DB) partFile {
	p.partFileDo.ReplaceDB(db)
	return p
}

type partFileDo struct{ gen.DO }

type IPartFileDo interface {
	gen.SubQuery
	Debug() IPartFileDo
	WithContext(ctx context.Context) IPartFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPartFileDo
	WriteDB() IPartFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPartFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPartFileDo
	Not(conds ...gen.Condition) IPartFileDo
	Or(conds ...gen.Condition) IPartFileDo
	Select(conds ...field.Expr) IPartFileDo
	Where(conds ...gen.Condition) IPartFileDo
	Order(conds ...field.Expr) IPartFileDo
	Distinct(cols ...field.Expr) IPartFileDo
	Omit(cols ...field.Expr) IPartFileDo
	Join(table schema.Tabler, on ...field.Expr) IPartFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPartFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPartFileDo
	Group(cols ...field.Expr) IPartFileDo
	Having(conds ...gen.Condition) IPartFileDo
	Limit(limit int) IPartFileDo
	Offset(offset int) IPartFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPartFileDo
	Unscoped() IPartFileDo
	Create(values ...*model.PartFile) error
	CreateInBatches(values []*model.PartFile, batchSize int) error
	Save(values ...*model.PartFile) error
	First() (*model.PartFile, error)
	Take() (*model.PartFile, error)
	Last() (*model.PartFile, error)
	Find() ([]*model.PartFile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PartFile, err error)
	FindInBatches(result *[]*model.PartFile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PartFile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPartFileDo
	Assign(attrs ...field.AssignExpr) IPartFileDo
	Joins(fields ...field.RelationField) IPartFileDo
	Preload(fields ...field.RelationField) IPartFileDo
	FirstOrInit() (*model.PartFile, error)
	FirstOrCreate() (*model.PartFile, error)
	FindByPage(offset int, limit int) (result []*model.PartFile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPartFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p partFileDo) Debug() IPartFileDo {
	return p.withDO(p.DO.Debug())
}

func (p partFileDo) WithContext(ctx context.Context) IPartFileDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p partFileDo) ReadDB() IPartFileDo {
	return p.Clauses(dbresolver.Read)
}

func (p partFileDo) WriteDB() IPartFileDo {
	return p.Clauses(dbresolver.Write)
}

func (p partFileDo) Session(config *gorm.Session) IPartFileDo {
	return p.withDO(p.DO.Session(config))
}

func (p partFileDo) Clauses(conds ...clause.Expression) IPartFileDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p partFileDo) Returning(value interface{}, columns ...string) IPartFileDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p partFileDo) Not(conds ...gen.Condition) IPartFileDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p partFileDo) Or(conds ...gen.Condition) IPartFileDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p partFileDo) Select(conds ...field.Expr) IPartFileDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p partFileDo) Where(conds ...gen.Condition) IPartFileDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p partFileDo) Order(conds ...field.Expr) IPartFileDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p partFileDo) Distinct(cols ...field.Expr) IPartFileDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p partFileDo) Omit(cols ...field.Expr) IPartFileDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p partFileDo) Join(table schema.Tabler, on ...field.Expr) IPartFileDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p partFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPartFileDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p partFileDo) RightJoin(table schema.Tabler, on ...field.Expr) IPartFileDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p partFileDo) Group(cols ...field.Expr) IPartFileDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p partFileDo) Having(conds ...gen.Condition) IPartFileDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p partFileDo) Limit(limit int) IPartFileDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p partFileDo) Offset(offset int) IPartFileDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p partFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPartFileDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p partFileDo) Unscoped() IPartFileDo {
	return p.withDO(p.DO.Unscoped())
}

func (p partFileDo) Create(values ...*model.PartFile) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p partFileDo) CreateInBatches(values []*model.PartFile, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p partFileDo) Save(values ...*model.PartFile) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p partFileDo) First() (*model.PartFile, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PartFile), nil
	}
}

func (p partFileDo) Take() (*model.PartFile, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PartFile), nil
	}
}

func (p partFileDo) Last() (*model.PartFile, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PartFile), nil
	}
}

func (p partFileDo) Find() ([]*model.PartFile, error) {
	result, err := p.DO.Find()
	return result.([]*model.PartFile), err
}

func (p partFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PartFile, err error) {
	buf := make([]*model.PartFile, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p partFileDo) FindInBatches(result *[]*model.PartFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p partFileDo) Attrs(attrs ...field.AssignExpr) IPartFileDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p partFileDo) Assign(attrs ...field.AssignExpr) IPartFileDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p partFileDo) Joins(fields ...field.RelationField) IPartFileDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p partFileDo) Preload(fields ...field.RelationField) IPartFileDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p partFileDo) FirstOrInit() (*model.PartFile, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PartFile), nil
	}
}

func (p partFileDo) FirstOrCreate() (*model.PartFile, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PartFile), nil
	}
}

func (p partFileDo) FindByPage(offset int, limit int) (result []*model.PartFile, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p partFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p partFileDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p partFileDo) Delete(models ...*model.PartFile) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *partFileDo) withDO(do gen.Dao) *partFileDo {
	p.DO = *do.(*gen.DO)
	return p
}
