// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newPersonExternalID(db *gorm.DB, opts ...gen.DOOption) personExternalID {
	_personExternalID := personExternalID{}

	_personExternalID.personExternalIDDo.UseDB(db, opts...)
	_personExternalID.personExternalIDDo.UseModel(&model.PersonExternalID{})

	tableName := _personExternalID.personExternalIDDo.TableName()
	_personExternalID.ALL = field.NewAsterisk(tableName)
	_personExternalID.PersonID = field.NewField(tableName, "person_id")
	_personExternalID.Provider = field.NewString(tableName, "provider")
	_personExternalID.Value = field.NewString(tableName, "value")

	_personExternalID.fillFieldMap()

	return _personExternalID
}

type personExternalID struct {
	personExternalIDDo personExternalIDDo

	ALL      field.Asterisk
	PersonID field.Field
	Provider field.String
	Value    field.String

	fieldMap map[string]field.Expr
}

func (p personExternalID) Table(newTableName string) *personExternalID {
	p.personExternalIDDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p personExternalID) As(alias string) *personExternalID {
	p.personExternalIDDo.DO = *(p.personExternalIDDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *personExternalID) updateTableName(table string) *personExternalID {
	p.ALL = field.NewAsterisk(table)
	p.PersonID = field.NewField(table, "person_id")
	p.Provider = field.NewString(table, "provider")
	p.Value = field.NewString(table, "value")

	p.fillFieldMap()

	return p
}

func (p *personExternalID) WithContext(ctx context.Context) IPersonExternalIDDo {
	return p.personExternalIDDo.WithContext(ctx)
}

func (p personExternalID) TableName() string { return p.personExternalIDDo.TableName() }

func (p personExternalID) Alias() string { return p.personExternalIDDo.Alias() }

func (p personExternalID) Columns(cols ...field.Expr) gen.Columns {
	return p.personExternalIDDo.Columns(cols...)
}

func (p *personExternalID) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *personExternalID) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["person_id"] = p.PersonID
	p.fieldMap["provider"] = p.Provider
	p.fieldMap["value"] = p.Value
}

func (p personExternalID) clone(db *gorm.DB) personExternalID {
	p.personExternalIDDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p personExternalID) replaceDB(db *gorm.DB) personExternalID {
	p.personExternalIDDo.ReplaceDB(db)
	return p
}

type personExternalIDDo struct{ gen.DO }

type IPersonExternalIDDo interface {
	gen.SubQuery
	Debug() IPersonExternalIDDo
	WithContext(ctx context.Context) IPersonExternalIDDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPersonExternalIDDo
	WriteDB() IPersonExternalIDDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPersonExternalIDDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPersonExternalIDDo
	Not(conds ...gen.Condition) IPersonExternalIDDo
	Or(conds ...gen.Condition) IPersonExternalIDDo
	Select(conds ...field.Expr) IPersonExternalIDDo
	Where(conds ...gen.Condition) IPersonExternalIDDo
	Order(conds ...field.Expr) IPersonExternalIDDo
	Distinct(cols ...field.Expr) IPersonExternalIDDo
	Omit(cols ...field.Expr) IPersonExternalIDDo
	Join(table schema.Tabler, on ...field.Expr) IPersonExternalIDDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPersonExternalIDDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPersonExternalIDDo
	Group(cols ...field.Expr) IPersonExternalIDDo
	Having(conds ...gen.Condition) IPersonExternalIDDo
	Limit(limit int) IPersonExternalIDDo
	Offset(offset int) IPersonExternalIDDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPersonExternalIDDo
	Unscoped() IPersonExternalIDDo
	Create(values ...*model.PersonExternalID) error
	CreateInBatches(values []*model.PersonExternalID, batchSize int) error
	Save(values ...*model.PersonExternalID) error
	First() (*model.PersonExternalID, error)
	Take() (*model.PersonExternalID, error)
	Last() (*model.PersonExternalID, error)
	Find() ([]*model.PersonExternalID, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PersonExternalID, err error)
	FindInBatches(result *[]*model.PersonExternalID, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PersonExternalID) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPersonExternalIDDo
	Assign(attrs ...field.AssignExpr) IPersonExternalIDDo
	Joins(fields ...field.RelationField) IPersonExternalIDDo
	Preload(fields ...field.RelationField) IPersonExternalIDDo
	FirstOrInit() (*model.PersonExternalID, error)
	FirstOrCreate() (*model.PersonExternalID, error)
	FindByPage(offset int, limit int) (result []*model.PersonExternalID, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPersonExternalIDDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p personExternalIDDo) Debug() IPersonExternalIDDo {
	return p.withDO(p.DO.Debug())
}

func (p personExternalIDDo) WithContext(ctx context.Context) IPersonExternalIDDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p personExternalIDDo) ReadDB() IPersonExternalIDDo {
	return p.Clauses(dbresolver.Read)
}

func (p personExternalIDDo) WriteDB() IPersonExternalIDDo {
	return p.Clauses(dbresolver.Write)
}

func (p personExternalIDDo) Session(config *gorm.Session) IPersonExternalIDDo {
	return p.withDO(p.DO.Session(config))
}

func (p personExternalIDDo) Clauses(conds ...clause.Expression) IPersonExternalIDDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p personExternalIDDo) Returning(value interface{}, columns ...string) IPersonExternalIDDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p personExternalIDDo) Not(conds ...gen.Condition) IPersonExternalIDDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p personExternalIDDo) Or(conds ...gen.Condition) IPersonExternalIDDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p personExternalIDDo) Select(conds ...field.Expr) IPersonExternalIDDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p personExternalIDDo) Where(conds ...gen.Condition) IPersonExternalIDDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p personExternalIDDo) Order(conds ...field.Expr) IPersonExternalIDDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p personExternalIDDo) Distinct(cols ...field.Expr) IPersonExternalIDDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p personExternalIDDo) Omit(cols ...field.Expr) IPersonExternalIDDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p personExternalIDDo) Join(table schema.Tabler, on ...field.Expr) IPersonExternalIDDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p personExternalIDDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPersonExternalIDDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p personExternalIDDo) RightJoin(table schema.Tabler, on ...field.Expr) IPersonExternalIDDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p personExternalIDDo) Group(cols ...field.Expr) IPersonExternalIDDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p personExternalIDDo) Having(conds ...gen.Condition) IPersonExternalIDDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p personExternalIDDo) Limit(limit int) IPersonExternalIDDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p personExternalIDDo) Offset(offset int) IPersonExternalIDDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p personExternalIDDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPersonExternalIDDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p personExternalIDDo) Unscoped() IPersonExternalIDDo {
	return p.withDO(p.DO.Unscoped())
}

func (p personExternalIDDo) Create(values ...*model.PersonExternalID) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p personExternalIDDo) CreateInBatches(values []*model.PersonExternalID, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p personExternalIDDo) Save(values ...*model.PersonExternalID) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p personExternalIDDo) First() (*model.PersonExternalID, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersonExternalID), nil
	}
}

func (p personExternalIDDo) Take() (*model.PersonExternalID, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersonExternalID), nil
	}
}

func (p personExternalIDDo) Last() (*model.PersonExternalID, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersonExternalID), nil
	}
}

func (p personExternalIDDo) Find() ([]*model.PersonExternalID, error) {
	result, err := p.DO.Find()
	return result.([]*model.PersonExternalID), err
}

func (p personExternalIDDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PersonExternalID, err error) {
	buf := make([]*model.PersonExternalID, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p personExternalIDDo) FindInBatches(result *[]*model.PersonExternalID, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p personExternalIDDo) Attrs(attrs ...field.AssignExpr) IPersonExternalIDDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p personExternalIDDo) Assign(attrs ...field.AssignExpr) IPersonExternalIDDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p personExternalIDDo) Joins(fields ...field.RelationField) IPersonExternalIDDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p personExternalIDDo) Preload(fields ...field.RelationField) IPersonExternalIDDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p personExternalIDDo) FirstOrInit() (*model.PersonExternalID, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersonExternalID), nil
	}
}

func (p personExternalIDDo) FirstOrCreate() (*model.PersonExternalID, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersonExternalID), nil
	}
}

func (p personExternalIDDo) FindByPage(offset int, limit int) (result []*model.PersonExternalID, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p personExternalIDDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p personExternalIDDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p personExternalIDDo) Delete(models ...*model.PersonExternalID) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *personExternalIDDo) withDO(do gen.Dao) *personExternalIDDo {
	p.DO = *do.(*gen.DO)
	return p
}
