// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newPlay(db *gorm.DB, opts ...gen.DOOption) play {
	_play := play{}

	_play.playDo.UseDB(db, opts...)
	_play.playDo.UseModel(&model.Play{})

	tableName := _play.playDo.TableName()
	_play.ALL = field.NewAsterisk(tableName)
	_play.ID = field.NewField(tableName, "id")
	_play.ProfileID = field.NewField(tableName, "profile_id")
	_play.ItemID = field.NewField(tableName, "item_id")
	_play.VersionID = field.NewField(tableName, "version_id")
	_play.Method = field.NewString(tableName, "method")
	_play.StartedAt = field.NewTime(tableName, "started_at")
	_play.StoppedAt = field.NewTime(tableName, "stopped_at")
	_play.PositionMS = field.NewInt64(tableName, "position_ms")

	_play.fillFieldMap()

	return _play
}

type play struct {
	playDo playDo

	ALL        field.Asterisk
	ID         field.Field
	ProfileID  field.Field
	ItemID     field.Field
	VersionID  field.Field
	Method     field.String
	StartedAt  field.Time
	StoppedAt  field.Time
	PositionMS field.Int64

	fieldMap map[string]field.Expr
}

func (p play) Table(newTableName string) *play {
	p.playDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p play) As(alias string) *play {
	p.playDo.DO = *(p.playDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *play) updateTableName(table string) *play {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.ProfileID = field.NewField(table, "profile_id")
	p.ItemID = field.NewField(table, "item_id")
	p.VersionID = field.NewField(table, "version_id")
	p.Method = field.NewString(table, "method")
	p.StartedAt = field.NewTime(table, "started_at")
	p.StoppedAt = field.NewTime(table, "stopped_at")
	p.PositionMS = field.NewInt64(table, "position_ms")

	p.fillFieldMap()

	return p
}

func (p *play) WithContext(ctx context.Context) IPlayDo { return p.playDo.WithContext(ctx) }

func (p play) TableName() string { return p.playDo.TableName() }

func (p play) Alias() string { return p.playDo.Alias() }

func (p play) Columns(cols ...field.Expr) gen.Columns { return p.playDo.Columns(cols...) }

func (p *play) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *play) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["id"] = p.ID
	p.fieldMap["profile_id"] = p.ProfileID
	p.fieldMap["item_id"] = p.ItemID
	p.fieldMap["version_id"] = p.VersionID
	p.fieldMap["method"] = p.Method
	p.fieldMap["started_at"] = p.StartedAt
	p.fieldMap["stopped_at"] = p.StoppedAt
	p.fieldMap["position_ms"] = p.PositionMS
}

func (p play) clone(db *gorm.DB) play {
	p.playDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p play) replaceDB(db *gorm.DB) play {
	p.playDo.ReplaceDB(db)
	return p
}

type playDo struct{ gen.DO }

type IPlayDo interface {
	gen.SubQuery
	Debug() IPlayDo
	WithContext(ctx context.Context) IPlayDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPlayDo
	WriteDB() IPlayDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPlayDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPlayDo
	Not(conds ...gen.Condition) IPlayDo
	Or(conds ...gen.Condition) IPlayDo
	Select(conds ...field.Expr) IPlayDo
	Where(conds ...gen.Condition) IPlayDo
	Order(conds ...field.Expr) IPlayDo
	Distinct(cols ...field.Expr) IPlayDo
	Omit(cols ...field.Expr) IPlayDo
	Join(table schema.Tabler, on ...field.Expr) IPlayDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPlayDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPlayDo
	Group(cols ...field.Expr) IPlayDo
	Having(conds ...gen.Condition) IPlayDo
	Limit(limit int) IPlayDo
	Offset(offset int) IPlayDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPlayDo
	Unscoped() IPlayDo
	Create(values ...*model.Play) error
	CreateInBatches(values []*model.Play, batchSize int) error
	Save(values ...*model.Play) error
	First() (*model.Play, error)
	Take() (*model.Play, error)
	Last() (*model.Play, error)
	Find() ([]*model.Play, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Play, err error)
	FindInBatches(result *[]*model.Play, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Play) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPlayDo
	Assign(attrs ...field.AssignExpr) IPlayDo
	Joins(fields ...field.RelationField) IPlayDo
	Preload(fields ...field.RelationField) IPlayDo
	FirstOrInit() (*model.Play, error)
	FirstOrCreate() (*model.Play, error)
	FindByPage(offset int, limit int) (result []*model.Play, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPlayDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p playDo) Debug() IPlayDo {
	return p.withDO(p.DO.Debug())
}

func (p playDo) WithContext(ctx context.Context) IPlayDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p playDo) ReadDB() IPlayDo {
	return p.Clauses(dbresolver.Read)
}

func (p playDo) WriteDB() IPlayDo {
	return p.Clauses(dbresolver.Write)
}

func (p playDo) Session(config *gorm.Session) IPlayDo {
	return p.withDO(p.DO.Session(config))
}

func (p playDo) Clauses(conds ...clause.Expression) IPlayDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p playDo) Returning(value interface{}, columns ...string) IPlayDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p playDo) Not(conds ...gen.Condition) IPlayDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p playDo) Or(conds ...gen.Condition) IPlayDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p playDo) Select(conds ...field.Expr) IPlayDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p playDo) Where(conds ...gen.Condition) IPlayDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p playDo) Order(conds ...field.Expr) IPlayDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p playDo) Distinct(cols ...field.Expr) IPlayDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p playDo) Omit(cols ...field.Expr) IPlayDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p playDo) Join(table schema.Tabler, on ...field.Expr) IPlayDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p playDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPlayDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p playDo) RightJoin(table schema.Tabler, on ...field.Expr) IPlayDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p playDo) Group(cols ...field.Expr) IPlayDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p playDo) Having(conds ...gen.Condition) IPlayDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p playDo) Limit(limit int) IPlayDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p playDo) Offset(offset int) IPlayDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p playDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPlayDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p playDo) Unscoped() IPlayDo {
	return p.withDO(p.DO.Unscoped())
}

func (p playDo) Create(values ...*model.Play) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p playDo) CreateInBatches(values []*model.Play, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p playDo) Save(values ...*model.Play) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p playDo) First() (*model.Play, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Play), nil
	}
}

func (p playDo) Take() (*model.Play, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Play), nil
	}
}

func (p playDo) Last() (*model.Play, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Play), nil
	}
}

func (p playDo) Find() ([]*model.Play, error) {
	result, err := p.DO.Find()
	return result.([]*model.Play), err
}

func (p playDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Play, err error) {
	buf := make([]*model.Play, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p playDo) FindInBatches(result *[]*model.Play, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p playDo) Attrs(attrs ...field.AssignExpr) IPlayDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p playDo) Assign(attrs ...field.AssignExpr) IPlayDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p playDo) Joins(fields ...field.RelationField) IPlayDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p playDo) Preload(fields ...field.RelationField) IPlayDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p playDo) FirstOrInit() (*model.Play, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Play), nil
	}
}

func (p playDo) FirstOrCreate() (*model.Play, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Play), nil
	}
}

func (p playDo) FindByPage(offset int, limit int) (result []*model.Play, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p playDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p playDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p playDo) Delete(models ...*model.Play) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *playDo) withDO(do gen.Dao) *playDo {
	p.DO = *do.(*gen.DO)
	return p
}
