// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newPlaylistEntry(db *gorm.DB, opts ...gen.DOOption) playlistEntry {
	_playlistEntry := playlistEntry{}

	_playlistEntry.playlistEntryDo.UseDB(db, opts...)
	_playlistEntry.playlistEntryDo.UseModel(&model.PlaylistEntry{})

	tableName := _playlistEntry.playlistEntryDo.TableName()
	_playlistEntry.ALL = field.NewAsterisk(tableName)
	_playlistEntry.ID = field.NewField(tableName, "id")
	_playlistEntry.PlaylistID = field.NewField(tableName, "playlist_id")
	_playlistEntry.ItemID = field.NewField(tableName, "item_id")
	_playlistEntry.Position = field.NewInt(tableName, "position")

	_playlistEntry.fillFieldMap()

	return _playlistEntry
}

type playlistEntry struct {
	playlistEntryDo playlistEntryDo

	ALL        field.Asterisk
	ID         field.Field
	PlaylistID field.Field
	ItemID     field.Field
	Position   field.Int

	fieldMap map[string]field.Expr
}

func (p playlistEntry) Table(newTableName string) *playlistEntry {
	p.playlistEntryDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p playlistEntry) As(alias string) *playlistEntry {
	p.playlistEntryDo.DO = *(p.playlistEntryDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *playlistEntry) updateTableName(table string) *playlistEntry {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.PlaylistID = field.NewField(table, "playlist_id")
	p.ItemID = field.NewField(table, "item_id")
	p.Position = field.NewInt(table, "position")

	p.fillFieldMap()

	return p
}

func (p *playlistEntry) WithContext(ctx context.Context) IPlaylistEntryDo {
	return p.playlistEntryDo.WithContext(ctx)
}

func (p playlistEntry) TableName() string { return p.playlistEntryDo.TableName() }

func (p playlistEntry) Alias() string { return p.playlistEntryDo.Alias() }

func (p playlistEntry) Columns(cols ...field.Expr) gen.Columns {
	return p.playlistEntryDo.Columns(cols...)
}

func (p *playlistEntry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *playlistEntry) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["id"] = p.ID
	p.fieldMap["playlist_id"] = p.PlaylistID
	p.fieldMap["item_id"] = p.ItemID
	p.fieldMap["position"] = p.Position
}

func (p playlistEntry) clone(db *gorm.DB) playlistEntry {
	p.playlistEntryDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p playlistEntry) replaceDB(db *gorm.DB) playlistEntry {
	p.playlistEntryDo.ReplaceDB(db)
	return p
}

type playlistEntryDo struct{ gen.DO }

type IPlaylistEntryDo interface {
	gen.SubQuery
	Debug() IPlaylistEntryDo
	WithContext(ctx context.Context) IPlaylistEntryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPlaylistEntryDo
	WriteDB() IPlaylistEntryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPlaylistEntryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPlaylistEntryDo
	Not(conds ...gen.Condition) IPlaylistEntryDo
	Or(conds ...gen.Condition) IPlaylistEntryDo
	Select(conds ...field.Expr) IPlaylistEntryDo
	Where(conds ...gen.Condition) IPlaylistEntryDo
	Order(conds ...field.Expr) IPlaylistEntryDo
	Distinct(cols ...field.Expr) IPlaylistEntryDo
	Omit(cols ...field.Expr) IPlaylistEntryDo
	Join(table schema.Tabler, on ...field.Expr) IPlaylistEntryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPlaylistEntryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPlaylistEntryDo
	Group(cols ...field.Expr) IPlaylistEntryDo
	Having(conds ...gen.Condition) IPlaylistEntryDo
	Limit(limit int) IPlaylistEntryDo
	Offset(offset int) IPlaylistEntryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPlaylistEntryDo
	Unscoped() IPlaylistEntryDo
	Create(values ...*model.PlaylistEntry) error
	CreateInBatches(values []*model.PlaylistEntry, batchSize int) error
	Save(values ...*model.PlaylistEntry) error
	First() (*model.PlaylistEntry, error)
	Take() (*model.PlaylistEntry, error)
	Last() (*model.PlaylistEntry, error)
	Find() ([]*model.PlaylistEntry, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlaylistEntry, err error)
	FindInBatches(result *[]*model.PlaylistEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PlaylistEntry) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPlaylistEntryDo
	Assign(attrs ...field.AssignExpr) IPlaylistEntryDo
	Joins(fields ...field.RelationField) IPlaylistEntryDo
	Preload(fields ...field.RelationField) IPlaylistEntryDo
	FirstOrInit() (*model.PlaylistEntry, error)
	FirstOrCreate() (*model.PlaylistEntry, error)
	FindByPage(offset int, limit int) (result []*model.PlaylistEntry, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPlaylistEntryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p playlistEntryDo) Debug() IPlaylistEntryDo {
	return p.withDO(p.DO.Debug())
}

func (p playlistEntryDo) WithContext(ctx context.Context) IPlaylistEntryDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p playlistEntryDo) ReadDB() IPlaylistEntryDo {
	return p.Clauses(dbresolver.Read)
}

func (p playlistEntryDo) WriteDB() IPlaylistEntryDo {
	return p.Clauses(dbresolver.Write)
}

func (p playlistEntryDo) Session(config *gorm.Session) IPlaylistEntryDo {
	return p.withDO(p.DO.Session(config))
}

func (p playlistEntryDo) Clauses(conds ...clause.Expression) IPlaylistEntryDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p playlistEntryDo) Returning(value interface{}, columns ...string) IPlaylistEntryDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p playlistEntryDo) Not(conds ...gen.Condition) IPlaylistEntryDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p playlistEntryDo) Or(conds ...gen.Condition) IPlaylistEntryDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p playlistEntryDo) Select(conds ...field.Expr) IPlaylistEntryDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p playlistEntryDo) Where(conds ...gen.Condition) IPlaylistEntryDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p playlistEntryDo) Order(conds ...field.Expr) IPlaylistEntryDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p playlistEntryDo) Distinct(cols ...field.Expr) IPlaylistEntryDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p playlistEntryDo) Omit(cols ...field.Expr) IPlaylistEntryDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p playlistEntryDo) Join(table schema.Tabler, on ...field.Expr) IPlaylistEntryDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p playlistEntryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPlaylistEntryDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p playlistEntryDo) RightJoin(table schema.Tabler, on ...field.Expr) IPlaylistEntryDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p playlistEntryDo) Group(cols ...field.Expr) IPlaylistEntryDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p playlistEntryDo) Having(conds ...gen.Condition) IPlaylistEntryDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p playlistEntryDo) Limit(limit int) IPlaylistEntryDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p playlistEntryDo) Offset(offset int) IPlaylistEntryDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p playlistEntryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPlaylistEntryDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p playlistEntryDo) Unscoped() IPlaylistEntryDo {
	return p.withDO(p.DO.Unscoped())
}

func (p playlistEntryDo) Create(values ...*model.PlaylistEntry) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p playlistEntryDo) CreateInBatches(values []*model.PlaylistEntry, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p playlistEntryDo) Save(values ...*model.PlaylistEntry) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p playlistEntryDo) First() (*model.PlaylistEntry, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaylistEntry), nil
	}
}

func (p playlistEntryDo) Take() (*model.PlaylistEntry, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaylistEntry), nil
	}
}

func (p playlistEntryDo) Last() (*model.PlaylistEntry, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaylistEntry), nil
	}
}

func (p playlistEntryDo) Find() ([]*model.PlaylistEntry, error) {
	result, err := p.DO.Find()
	return result.([]*model.PlaylistEntry), err
}

func (p playlistEntryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlaylistEntry, err error) {
	buf := make([]*model.PlaylistEntry, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p playlistEntryDo) FindInBatches(result *[]*model.PlaylistEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p playlistEntryDo) Attrs(attrs ...field.AssignExpr) IPlaylistEntryDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p playlistEntryDo) Assign(attrs ...field.AssignExpr) IPlaylistEntryDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p playlistEntryDo) Joins(fields ...field.RelationField) IPlaylistEntryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p playlistEntryDo) Preload(fields ...field.RelationField) IPlaylistEntryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p playlistEntryDo) FirstOrInit() (*model.PlaylistEntry, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaylistEntry), nil
	}
}

func (p playlistEntryDo) FirstOrCreate() (*model.PlaylistEntry, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaylistEntry), nil
	}
}

func (p playlistEntryDo) FindByPage(offset int, limit int) (result []*model.PlaylistEntry, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p playlistEntryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p playlistEntryDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p playlistEntryDo) Delete(models ...*model.PlaylistEntry) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *playlistEntryDo) withDO(do gen.Dao) *playlistEntryDo {
	p.DO = *do.(*gen.DO)
	return p
}
