// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newProfile(db *gorm.DB, opts ...gen.DOOption) profile {
	_profile := profile{}

	_profile.profileDo.UseDB(db, opts...)
	_profile.profileDo.UseModel(&model.Profile{})

	tableName := _profile.profileDo.TableName()
	_profile.ALL = field.NewAsterisk(tableName)
	_profile.ID = field.NewField(tableName, "id")
	_profile.Name = field.NewString(tableName, "name")
	_profile.Role = field.NewString(tableName, "role")
	_profile.PasswordHash = field.NewString(tableName, "password_hash")
	_profile.PinHash = field.NewString(tableName, "pin_hash")
	_profile.CreatedAt = field.NewTime(tableName, "created_at")
	_profile.MaxAge = field.NewInt16(tableName, "max_age")
	_profile.Unrated = field.NewString(tableName, "unrated")
	_profile.AvatarID = field.NewField(tableName, "avatar_id")

	_profile.fillFieldMap()

	return _profile
}

type profile struct {
	profileDo profileDo

	ALL          field.Asterisk
	ID           field.Field
	Name         field.String
	Role         field.String
	PasswordHash field.String
	PinHash      field.String
	CreatedAt    field.Time
	MaxAge       field.Int16
	Unrated      field.String
	AvatarID     field.Field

	fieldMap map[string]field.Expr
}

func (p profile) Table(newTableName string) *profile {
	p.profileDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p profile) As(alias string) *profile {
	p.profileDo.DO = *(p.profileDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *profile) updateTableName(table string) *profile {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.Name = field.NewString(table, "name")
	p.Role = field.NewString(table, "role")
	p.PasswordHash = field.NewString(table, "password_hash")
	p.PinHash = field.NewString(table, "pin_hash")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.MaxAge = field.NewInt16(table, "max_age")
	p.Unrated = field.NewString(table, "unrated")
	p.AvatarID = field.NewField(table, "avatar_id")

	p.fillFieldMap()

	return p
}

func (p *profile) WithContext(ctx context.Context) IProfileDo { return p.profileDo.WithContext(ctx) }

func (p profile) TableName() string { return p.profileDo.TableName() }

func (p profile) Alias() string { return p.profileDo.Alias() }

func (p profile) Columns(cols ...field.Expr) gen.Columns { return p.profileDo.Columns(cols...) }

func (p *profile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *profile) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["role"] = p.Role
	p.fieldMap["password_hash"] = p.PasswordHash
	p.fieldMap["pin_hash"] = p.PinHash
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["max_age"] = p.MaxAge
	p.fieldMap["unrated"] = p.Unrated
	p.fieldMap["avatar_id"] = p.AvatarID
}

func (p profile) clone(db *gorm.DB) profile {
	p.profileDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p profile) replaceDB(db *gorm.DB) profile {
	p.profileDo.ReplaceDB(db)
	return p
}

type profileDo struct{ gen.DO }

type IProfileDo interface {
	gen.SubQuery
	Debug() IProfileDo
	WithContext(ctx context.Context) IProfileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProfileDo
	WriteDB() IProfileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProfileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProfileDo
	Not(conds ...gen.Condition) IProfileDo
	Or(conds ...gen.Condition) IProfileDo
	Select(conds ...field.Expr) IProfileDo
	Where(conds ...gen.Condition) IProfileDo
	Order(conds ...field.Expr) IProfileDo
	Distinct(cols ...field.Expr) IProfileDo
	Omit(cols ...field.Expr) IProfileDo
	Join(table schema.Tabler, on ...field.Expr) IProfileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProfileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProfileDo
	Group(cols ...field.Expr) IProfileDo
	Having(conds ...gen.Condition) IProfileDo
	Limit(limit int) IProfileDo
	Offset(offset int) IProfileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProfileDo
	Unscoped() IProfileDo
	Create(values ...*model.Profile) error
	CreateInBatches(values []*model.Profile, batchSize int) error
	Save(values ...*model.Profile) error
	First() (*model.Profile, error)
	Take() (*model.Profile, error)
	Last() (*model.Profile, error)
	Find() ([]*model.Profile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Profile, err error)
	FindInBatches(result *[]*model.Profile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Profile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProfileDo
	Assign(attrs ...field.AssignExpr) IProfileDo
	Joins(fields ...field.RelationField) IProfileDo
	Preload(fields ...field.RelationField) IProfileDo
	FirstOrInit() (*model.Profile, error)
	FirstOrCreate() (*model.Profile, error)
	FindByPage(offset int, limit int) (result []*model.Profile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProfileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p profileDo) Debug() IProfileDo {
	return p.withDO(p.DO.Debug())
}

func (p profileDo) WithContext(ctx context.Context) IProfileDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p profileDo) ReadDB() IProfileDo {
	return p.Clauses(dbresolver.Read)
}

func (p profileDo) WriteDB() IProfileDo {
	return p.Clauses(dbresolver.Write)
}

func (p profileDo) Session(config *gorm.Session) IProfileDo {
	return p.withDO(p.DO.Session(config))
}

func (p profileDo) Clauses(conds ...clause.Expression) IProfileDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p profileDo) Returning(value interface{}, columns ...string) IProfileDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p profileDo) Not(conds ...gen.Condition) IProfileDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p profileDo) Or(conds ...gen.Condition) IProfileDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p profileDo) Select(conds ...field.Expr) IProfileDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p profileDo) Where(conds ...gen.Condition) IProfileDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p profileDo) Order(conds ...field.Expr) IProfileDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p profileDo) Distinct(cols ...field.Expr) IProfileDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p profileDo) Omit(cols ...field.Expr) IProfileDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p profileDo) Join(table schema.Tabler, on ...field.Expr) IProfileDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p profileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProfileDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p profileDo) RightJoin(table schema.Tabler, on ...field.Expr) IProfileDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p profileDo) Group(cols ...field.Expr) IProfileDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p profileDo) Having(conds ...gen.Condition) IProfileDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p profileDo) Limit(limit int) IProfileDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p profileDo) Offset(offset int) IProfileDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p profileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProfileDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p profileDo) Unscoped() IProfileDo {
	return p.withDO(p.DO.Unscoped())
}

func (p profileDo) Create(values ...*model.Profile) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p profileDo) CreateInBatches(values []*model.Profile, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p profileDo) Save(values ...*model.Profile) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p profileDo) First() (*model.Profile, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Profile), nil
	}
}

func (p profileDo) Take() (*model.Profile, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Profile), nil
	}
}

func (p profileDo) Last() (*model.Profile, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Profile), nil
	}
}

func (p profileDo) Find() ([]*model.Profile, error) {
	result, err := p.DO.Find()
	return result.([]*model.Profile), err
}

func (p profileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Profile, err error) {
	buf := make([]*model.Profile, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p profileDo) FindInBatches(result *[]*model.Profile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p profileDo) Attrs(attrs ...field.AssignExpr) IProfileDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p profileDo) Assign(attrs ...field.AssignExpr) IProfileDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p profileDo) Joins(fields ...field.RelationField) IProfileDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p profileDo) Preload(fields ...field.RelationField) IProfileDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p profileDo) FirstOrInit() (*model.Profile, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Profile), nil
	}
}

func (p profileDo) FirstOrCreate() (*model.Profile, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Profile), nil
	}
}

func (p profileDo) FindByPage(offset int, limit int) (result []*model.Profile, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p profileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p profileDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p profileDo) Delete(models ...*model.Profile) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *profileDo) withDO(do gen.Dao) *profileDo {
	p.DO = *do.(*gen.DO)
	return p
}
