// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newProfileLibrary(db *gorm.DB, opts ...gen.DOOption) profileLibrary {
	_profileLibrary := profileLibrary{}

	_profileLibrary.profileLibraryDo.UseDB(db, opts...)
	_profileLibrary.profileLibraryDo.UseModel(&model.ProfileLibrary{})

	tableName := _profileLibrary.profileLibraryDo.TableName()
	_profileLibrary.ALL = field.NewAsterisk(tableName)
	_profileLibrary.ProfileID = field.NewField(tableName, "profile_id")
	_profileLibrary.LibraryID = field.NewField(tableName, "library_id")

	_profileLibrary.fillFieldMap()

	return _profileLibrary
}

type profileLibrary struct {
	profileLibraryDo profileLibraryDo

	ALL       field.Asterisk
	ProfileID field.Field
	LibraryID field.Field

	fieldMap map[string]field.Expr
}

func (p profileLibrary) Table(newTableName string) *profileLibrary {
	p.profileLibraryDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p profileLibrary) As(alias string) *profileLibrary {
	p.profileLibraryDo.DO = *(p.profileLibraryDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *profileLibrary) updateTableName(table string) *profileLibrary {
	p.ALL = field.NewAsterisk(table)
	p.ProfileID = field.NewField(table, "profile_id")
	p.LibraryID = field.NewField(table, "library_id")

	p.fillFieldMap()

	return p
}

func (p *profileLibrary) WithContext(ctx context.Context) IProfileLibraryDo {
	return p.profileLibraryDo.WithContext(ctx)
}

func (p profileLibrary) TableName() string { return p.profileLibraryDo.TableName() }

func (p profileLibrary) Alias() string { return p.profileLibraryDo.Alias() }

func (p profileLibrary) Columns(cols ...field.Expr) gen.Columns {
	return p.profileLibraryDo.Columns(cols...)
}

func (p *profileLibrary) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *profileLibrary) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["profile_id"] = p.ProfileID
	p.fieldMap["library_id"] = p.LibraryID
}

func (p profileLibrary) clone(db *gorm.DB) profileLibrary {
	p.profileLibraryDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p profileLibrary) replaceDB(db *gorm.DB) profileLibrary {
	p.profileLibraryDo.ReplaceDB(db)
	return p
}

type profileLibraryDo struct{ gen.DO }

type IProfileLibraryDo interface {
	gen.SubQuery
	Debug() IProfileLibraryDo
	WithContext(ctx context.Context) IProfileLibraryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProfileLibraryDo
	WriteDB() IProfileLibraryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProfileLibraryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProfileLibraryDo
	Not(conds ...gen.Condition) IProfileLibraryDo
	Or(conds ...gen.Condition) IProfileLibraryDo
	Select(conds ...field.Expr) IProfileLibraryDo
	Where(conds ...gen.Condition) IProfileLibraryDo
	Order(conds ...field.Expr) IProfileLibraryDo
	Distinct(cols ...field.Expr) IProfileLibraryDo
	Omit(cols ...field.Expr) IProfileLibraryDo
	Join(table schema.Tabler, on ...field.Expr) IProfileLibraryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProfileLibraryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProfileLibraryDo
	Group(cols ...field.Expr) IProfileLibraryDo
	Having(conds ...gen.Condition) IProfileLibraryDo
	Limit(limit int) IProfileLibraryDo
	Offset(offset int) IProfileLibraryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProfileLibraryDo
	Unscoped() IProfileLibraryDo
	Create(values ...*model.ProfileLibrary) error
	CreateInBatches(values []*model.ProfileLibrary, batchSize int) error
	Save(values ...*model.ProfileLibrary) error
	First() (*model.ProfileLibrary, error)
	Take() (*model.ProfileLibrary, error)
	Last() (*model.ProfileLibrary, error)
	Find() ([]*model.ProfileLibrary, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProfileLibrary, err error)
	FindInBatches(result *[]*model.ProfileLibrary, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProfileLibrary) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProfileLibraryDo
	Assign(attrs ...field.AssignExpr) IProfileLibraryDo
	Joins(fields ...field.RelationField) IProfileLibraryDo
	Preload(fields ...field.RelationField) IProfileLibraryDo
	FirstOrInit() (*model.ProfileLibrary, error)
	FirstOrCreate() (*model.ProfileLibrary, error)
	FindByPage(offset int, limit int) (result []*model.ProfileLibrary, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProfileLibraryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p profileLibraryDo) Debug() IProfileLibraryDo {
	return p.withDO(p.DO.Debug())
}

func (p profileLibraryDo) WithContext(ctx context.Context) IProfileLibraryDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p profileLibraryDo) ReadDB() IProfileLibraryDo {
	return p.Clauses(dbresolver.Read)
}

func (p profileLibraryDo) WriteDB() IProfileLibraryDo {
	return p.Clauses(dbresolver.Write)
}

func (p profileLibraryDo) Session(config *gorm.Session) IProfileLibraryDo {
	return p.withDO(p.DO.Session(config))
}

func (p profileLibraryDo) Clauses(conds ...clause.Expression) IProfileLibraryDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p profileLibraryDo) Returning(value interface{}, columns ...string) IProfileLibraryDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p profileLibraryDo) Not(conds ...gen.Condition) IProfileLibraryDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p profileLibraryDo) Or(conds ...gen.Condition) IProfileLibraryDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p profileLibraryDo) Select(conds ...field.Expr) IProfileLibraryDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p profileLibraryDo) Where(conds ...gen.Condition) IProfileLibraryDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p profileLibraryDo) Order(conds ...field.Expr) IProfileLibraryDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p profileLibraryDo) Distinct(cols ...field.Expr) IProfileLibraryDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p profileLibraryDo) Omit(cols ...field.Expr) IProfileLibraryDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p profileLibraryDo) Join(table schema.Tabler, on ...field.Expr) IProfileLibraryDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p profileLibraryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProfileLibraryDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p profileLibraryDo) RightJoin(table schema.Tabler, on ...field.Expr) IProfileLibraryDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p profileLibraryDo) Group(cols ...field.Expr) IProfileLibraryDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p profileLibraryDo) Having(conds ...gen.Condition) IProfileLibraryDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p profileLibraryDo) Limit(limit int) IProfileLibraryDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p profileLibraryDo) Offset(offset int) IProfileLibraryDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p profileLibraryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProfileLibraryDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p profileLibraryDo) Unscoped() IProfileLibraryDo {
	return p.withDO(p.DO.Unscoped())
}

func (p profileLibraryDo) Create(values ...*model.ProfileLibrary) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p profileLibraryDo) CreateInBatches(values []*model.ProfileLibrary, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p profileLibraryDo) Save(values ...*model.ProfileLibrary) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p profileLibraryDo) First() (*model.ProfileLibrary, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfileLibrary), nil
	}
}

func (p profileLibraryDo) Take() (*model.ProfileLibrary, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfileLibrary), nil
	}
}

func (p profileLibraryDo) Last() (*model.ProfileLibrary, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfileLibrary), nil
	}
}

func (p profileLibraryDo) Find() ([]*model.ProfileLibrary, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProfileLibrary), err
}

func (p profileLibraryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProfileLibrary, err error) {
	buf := make([]*model.ProfileLibrary, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p profileLibraryDo) FindInBatches(result *[]*model.ProfileLibrary, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p profileLibraryDo) Attrs(attrs ...field.AssignExpr) IProfileLibraryDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p profileLibraryDo) Assign(attrs ...field.AssignExpr) IProfileLibraryDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p profileLibraryDo) Joins(fields ...field.RelationField) IProfileLibraryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p profileLibraryDo) Preload(fields ...field.RelationField) IProfileLibraryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p profileLibraryDo) FirstOrInit() (*model.ProfileLibrary, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfileLibrary), nil
	}
}

func (p profileLibraryDo) FirstOrCreate() (*model.ProfileLibrary, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfileLibrary), nil
	}
}

func (p profileLibraryDo) FindByPage(offset int, limit int) (result []*model.ProfileLibrary, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p profileLibraryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p profileLibraryDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p profileLibraryDo) Delete(models ...*model.ProfileLibrary) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *profileLibraryDo) withDO(do gen.Dao) *profileLibraryDo {
	p.DO = *do.(*gen.DO)
	return p
}
