// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newProfilePreference(db *gorm.DB, opts ...gen.DOOption) profilePreference {
	_profilePreference := profilePreference{}

	_profilePreference.profilePreferenceDo.UseDB(db, opts...)
	_profilePreference.profilePreferenceDo.UseModel(&model.ProfilePreference{})

	tableName := _profilePreference.profilePreferenceDo.TableName()
	_profilePreference.ALL = field.NewAsterisk(tableName)
	_profilePreference.ProfileID = field.NewField(tableName, "profile_id")
	_profilePreference.AudioLanguage = field.NewString(tableName, "audio_language")
	_profilePreference.AudioTrack = field.NewString(tableName, "audio_track")
	_profilePreference.SubtitleLanguage = field.NewString(tableName, "subtitle_language")
	_profilePreference.SubtitleMode = field.NewString(tableName, "subtitle_mode")
	_profilePreference.RememberAudio = field.NewString(tableName, "remember_audio")
	_profilePreference.RememberSubtitles = field.NewString(tableName, "remember_subtitles")
	_profilePreference.MaxBitrateKbps = field.NewInt32(tableName, "max_bitrate_kbps")
	_profilePreference.NextEpisode = field.NewString(tableName, "next_episode")
	_profilePreference.IntroAction = field.NewString(tableName, "intro_action")
	_profilePreference.CreditsAction = field.NewString(tableName, "credits_action")
	_profilePreference.SavedAt = field.NewTime(tableName, "saved_at")

	_profilePreference.fillFieldMap()

	return _profilePreference
}

type profilePreference struct {
	profilePreferenceDo profilePreferenceDo

	ALL               field.Asterisk
	ProfileID         field.Field
	AudioLanguage     field.String
	AudioTrack        field.String
	SubtitleLanguage  field.String
	SubtitleMode      field.String
	RememberAudio     field.String
	RememberSubtitles field.String
	MaxBitrateKbps    field.Int32
	NextEpisode       field.String
	IntroAction       field.String
	CreditsAction     field.String
	SavedAt           field.Time

	fieldMap map[string]field.Expr
}

func (p profilePreference) Table(newTableName string) *profilePreference {
	p.profilePreferenceDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p profilePreference) As(alias string) *profilePreference {
	p.profilePreferenceDo.DO = *(p.profilePreferenceDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *profilePreference) updateTableName(table string) *profilePreference {
	p.ALL = field.NewAsterisk(table)
	p.ProfileID = field.NewField(table, "profile_id")
	p.AudioLanguage = field.NewString(table, "audio_language")
	p.AudioTrack = field.NewString(table, "audio_track")
	p.SubtitleLanguage = field.NewString(table, "subtitle_language")
	p.SubtitleMode = field.NewString(table, "subtitle_mode")
	p.RememberAudio = field.NewString(table, "remember_audio")
	p.RememberSubtitles = field.NewString(table, "remember_subtitles")
	p.MaxBitrateKbps = field.NewInt32(table, "max_bitrate_kbps")
	p.NextEpisode = field.NewString(table, "next_episode")
	p.IntroAction = field.NewString(table, "intro_action")
	p.CreditsAction = field.NewString(table, "credits_action")
	p.SavedAt = field.NewTime(table, "saved_at")

	p.fillFieldMap()

	return p
}

func (p *profilePreference) WithContext(ctx context.Context) IProfilePreferenceDo {
	return p.profilePreferenceDo.WithContext(ctx)
}

func (p profilePreference) TableName() string { return p.profilePreferenceDo.TableName() }

func (p profilePreference) Alias() string { return p.profilePreferenceDo.Alias() }

func (p profilePreference) Columns(cols ...field.Expr) gen.Columns {
	return p.profilePreferenceDo.Columns(cols...)
}

func (p *profilePreference) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *profilePreference) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["profile_id"] = p.ProfileID
	p.fieldMap["audio_language"] = p.AudioLanguage
	p.fieldMap["audio_track"] = p.AudioTrack
	p.fieldMap["subtitle_language"] = p.SubtitleLanguage
	p.fieldMap["subtitle_mode"] = p.SubtitleMode
	p.fieldMap["remember_audio"] = p.RememberAudio
	p.fieldMap["remember_subtitles"] = p.RememberSubtitles
	p.fieldMap["max_bitrate_kbps"] = p.MaxBitrateKbps
	p.fieldMap["next_episode"] = p.NextEpisode
	p.fieldMap["intro_action"] = p.IntroAction
	p.fieldMap["credits_action"] = p.CreditsAction
	p.fieldMap["saved_at"] = p.SavedAt
}

func (p profilePreference) clone(db *gorm.DB) profilePreference {
	p.profilePreferenceDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p profilePreference) replaceDB(db *gorm.DB) profilePreference {
	p.profilePreferenceDo.ReplaceDB(db)
	return p
}

type profilePreferenceDo struct{ gen.DO }

type IProfilePreferenceDo interface {
	gen.SubQuery
	Debug() IProfilePreferenceDo
	WithContext(ctx context.Context) IProfilePreferenceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProfilePreferenceDo
	WriteDB() IProfilePreferenceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProfilePreferenceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProfilePreferenceDo
	Not(conds ...gen.Condition) IProfilePreferenceDo
	Or(conds ...gen.Condition) IProfilePreferenceDo
	Select(conds ...field.Expr) IProfilePreferenceDo
	Where(conds ...gen.Condition) IProfilePreferenceDo
	Order(conds ...field.Expr) IProfilePreferenceDo
	Distinct(cols ...field.Expr) IProfilePreferenceDo
	Omit(cols ...field.Expr) IProfilePreferenceDo
	Join(table schema.Tabler, on ...field.Expr) IProfilePreferenceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProfilePreferenceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProfilePreferenceDo
	Group(cols ...field.Expr) IProfilePreferenceDo
	Having(conds ...gen.Condition) IProfilePreferenceDo
	Limit(limit int) IProfilePreferenceDo
	Offset(offset int) IProfilePreferenceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProfilePreferenceDo
	Unscoped() IProfilePreferenceDo
	Create(values ...*model.ProfilePreference) error
	CreateInBatches(values []*model.ProfilePreference, batchSize int) error
	Save(values ...*model.ProfilePreference) error
	First() (*model.ProfilePreference, error)
	Take() (*model.ProfilePreference, error)
	Last() (*model.ProfilePreference, error)
	Find() ([]*model.ProfilePreference, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProfilePreference, err error)
	FindInBatches(result *[]*model.ProfilePreference, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProfilePreference) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProfilePreferenceDo
	Assign(attrs ...field.AssignExpr) IProfilePreferenceDo
	Joins(fields ...field.RelationField) IProfilePreferenceDo
	Preload(fields ...field.RelationField) IProfilePreferenceDo
	FirstOrInit() (*model.ProfilePreference, error)
	FirstOrCreate() (*model.ProfilePreference, error)
	FindByPage(offset int, limit int) (result []*model.ProfilePreference, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProfilePreferenceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p profilePreferenceDo) Debug() IProfilePreferenceDo {
	return p.withDO(p.DO.Debug())
}

func (p profilePreferenceDo) WithContext(ctx context.Context) IProfilePreferenceDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p profilePreferenceDo) ReadDB() IProfilePreferenceDo {
	return p.Clauses(dbresolver.Read)
}

func (p profilePreferenceDo) WriteDB() IProfilePreferenceDo {
	return p.Clauses(dbresolver.Write)
}

func (p profilePreferenceDo) Session(config *gorm.Session) IProfilePreferenceDo {
	return p.withDO(p.DO.Session(config))
}

func (p profilePreferenceDo) Clauses(conds ...clause.Expression) IProfilePreferenceDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p profilePreferenceDo) Returning(value interface{}, columns ...string) IProfilePreferenceDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p profilePreferenceDo) Not(conds ...gen.Condition) IProfilePreferenceDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p profilePreferenceDo) Or(conds ...gen.Condition) IProfilePreferenceDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p profilePreferenceDo) Select(conds ...field.Expr) IProfilePreferenceDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p profilePreferenceDo) Where(conds ...gen.Condition) IProfilePreferenceDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p profilePreferenceDo) Order(conds ...field.Expr) IProfilePreferenceDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p profilePreferenceDo) Distinct(cols ...field.Expr) IProfilePreferenceDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p profilePreferenceDo) Omit(cols ...field.Expr) IProfilePreferenceDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p profilePreferenceDo) Join(table schema.Tabler, on ...field.Expr) IProfilePreferenceDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p profilePreferenceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProfilePreferenceDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p profilePreferenceDo) RightJoin(table schema.Tabler, on ...field.Expr) IProfilePreferenceDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p profilePreferenceDo) Group(cols ...field.Expr) IProfilePreferenceDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p profilePreferenceDo) Having(conds ...gen.Condition) IProfilePreferenceDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p profilePreferenceDo) Limit(limit int) IProfilePreferenceDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p profilePreferenceDo) Offset(offset int) IProfilePreferenceDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p profilePreferenceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProfilePreferenceDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p profilePreferenceDo) Unscoped() IProfilePreferenceDo {
	return p.withDO(p.DO.Unscoped())
}

func (p profilePreferenceDo) Create(values ...*model.ProfilePreference) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p profilePreferenceDo) CreateInBatches(values []*model.ProfilePreference, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p profilePreferenceDo) Save(values ...*model.ProfilePreference) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p profilePreferenceDo) First() (*model.ProfilePreference, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfilePreference), nil
	}
}

func (p profilePreferenceDo) Take() (*model.ProfilePreference, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfilePreference), nil
	}
}

func (p profilePreferenceDo) Last() (*model.ProfilePreference, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfilePreference), nil
	}
}

func (p profilePreferenceDo) Find() ([]*model.ProfilePreference, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProfilePreference), err
}

func (p profilePreferenceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProfilePreference, err error) {
	buf := make([]*model.ProfilePreference, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p profilePreferenceDo) FindInBatches(result *[]*model.ProfilePreference, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p profilePreferenceDo) Attrs(attrs ...field.AssignExpr) IProfilePreferenceDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p profilePreferenceDo) Assign(attrs ...field.AssignExpr) IProfilePreferenceDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p profilePreferenceDo) Joins(fields ...field.RelationField) IProfilePreferenceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p profilePreferenceDo) Preload(fields ...field.RelationField) IProfilePreferenceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p profilePreferenceDo) FirstOrInit() (*model.ProfilePreference, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfilePreference), nil
	}
}

func (p profilePreferenceDo) FirstOrCreate() (*model.ProfilePreference, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfilePreference), nil
	}
}

func (p profilePreferenceDo) FindByPage(offset int, limit int) (result []*model.ProfilePreference, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p profilePreferenceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p profilePreferenceDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p profilePreferenceDo) Delete(models ...*model.ProfilePreference) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *profilePreferenceDo) withDO(do gen.Dao) *profilePreferenceDo {
	p.DO = *do.(*gen.DO)
	return p
}
