// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newRemoteVideo(db *gorm.DB, opts ...gen.DOOption) remoteVideo {
	_remoteVideo := remoteVideo{}

	_remoteVideo.remoteVideoDo.UseDB(db, opts...)
	_remoteVideo.remoteVideoDo.UseModel(&model.RemoteVideo{})

	tableName := _remoteVideo.remoteVideoDo.TableName()
	_remoteVideo.ALL = field.NewAsterisk(tableName)
	_remoteVideo.ItemID = field.NewField(tableName, "item_id")
	_remoteVideo.Source = field.NewString(tableName, "source")
	_remoteVideo.Position = field.NewInt(tableName, "position")
	_remoteVideo.Kind = field.NewString(tableName, "kind")
	_remoteVideo.Site = field.NewString(tableName, "site")
	_remoteVideo.Key = field.NewString(tableName, "key")
	_remoteVideo.Name = field.NewString(tableName, "name")
	_remoteVideo.Language = field.NewString(tableName, "language")
	_remoteVideo.PublishedAt = field.NewTime(tableName, "published_at")
	_remoteVideo.ThumbID = field.NewField(tableName, "thumb_id")

	_remoteVideo.fillFieldMap()

	return _remoteVideo
}

type remoteVideo struct {
	remoteVideoDo remoteVideoDo

	ALL         field.Asterisk
	ItemID      field.Field
	Source      field.String
	Position    field.Int
	Kind        field.String
	Site        field.String
	Key         field.String
	Name        field.String
	Language    field.String
	PublishedAt field.Time
	ThumbID     field.Field

	fieldMap map[string]field.Expr
}

func (r remoteVideo) Table(newTableName string) *remoteVideo {
	r.remoteVideoDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r remoteVideo) As(alias string) *remoteVideo {
	r.remoteVideoDo.DO = *(r.remoteVideoDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *remoteVideo) updateTableName(table string) *remoteVideo {
	r.ALL = field.NewAsterisk(table)
	r.ItemID = field.NewField(table, "item_id")
	r.Source = field.NewString(table, "source")
	r.Position = field.NewInt(table, "position")
	r.Kind = field.NewString(table, "kind")
	r.Site = field.NewString(table, "site")
	r.Key = field.NewString(table, "key")
	r.Name = field.NewString(table, "name")
	r.Language = field.NewString(table, "language")
	r.PublishedAt = field.NewTime(table, "published_at")
	r.ThumbID = field.NewField(table, "thumb_id")

	r.fillFieldMap()

	return r
}

func (r *remoteVideo) WithContext(ctx context.Context) IRemoteVideoDo {
	return r.remoteVideoDo.WithContext(ctx)
}

func (r remoteVideo) TableName() string { return r.remoteVideoDo.TableName() }

func (r remoteVideo) Alias() string { return r.remoteVideoDo.Alias() }

func (r remoteVideo) Columns(cols ...field.Expr) gen.Columns { return r.remoteVideoDo.Columns(cols...) }

func (r *remoteVideo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *remoteVideo) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 10)
	r.fieldMap["item_id"] = r.ItemID
	r.fieldMap["source"] = r.Source
	r.fieldMap["position"] = r.Position
	r.fieldMap["kind"] = r.Kind
	r.fieldMap["site"] = r.Site
	r.fieldMap["key"] = r.Key
	r.fieldMap["name"] = r.Name
	r.fieldMap["language"] = r.Language
	r.fieldMap["published_at"] = r.PublishedAt
	r.fieldMap["thumb_id"] = r.ThumbID
}

func (r remoteVideo) clone(db *gorm.DB) remoteVideo {
	r.remoteVideoDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r remoteVideo) replaceDB(db *gorm.DB) remoteVideo {
	r.remoteVideoDo.ReplaceDB(db)
	return r
}

type remoteVideoDo struct{ gen.DO }

type IRemoteVideoDo interface {
	gen.SubQuery
	Debug() IRemoteVideoDo
	WithContext(ctx context.Context) IRemoteVideoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRemoteVideoDo
	WriteDB() IRemoteVideoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRemoteVideoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRemoteVideoDo
	Not(conds ...gen.Condition) IRemoteVideoDo
	Or(conds ...gen.Condition) IRemoteVideoDo
	Select(conds ...field.Expr) IRemoteVideoDo
	Where(conds ...gen.Condition) IRemoteVideoDo
	Order(conds ...field.Expr) IRemoteVideoDo
	Distinct(cols ...field.Expr) IRemoteVideoDo
	Omit(cols ...field.Expr) IRemoteVideoDo
	Join(table schema.Tabler, on ...field.Expr) IRemoteVideoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRemoteVideoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRemoteVideoDo
	Group(cols ...field.Expr) IRemoteVideoDo
	Having(conds ...gen.Condition) IRemoteVideoDo
	Limit(limit int) IRemoteVideoDo
	Offset(offset int) IRemoteVideoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRemoteVideoDo
	Unscoped() IRemoteVideoDo
	Create(values ...*model.RemoteVideo) error
	CreateInBatches(values []*model.RemoteVideo, batchSize int) error
	Save(values ...*model.RemoteVideo) error
	First() (*model.RemoteVideo, error)
	Take() (*model.RemoteVideo, error)
	Last() (*model.RemoteVideo, error)
	Find() ([]*model.RemoteVideo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RemoteVideo, err error)
	FindInBatches(result *[]*model.RemoteVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RemoteVideo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRemoteVideoDo
	Assign(attrs ...field.AssignExpr) IRemoteVideoDo
	Joins(fields ...field.RelationField) IRemoteVideoDo
	Preload(fields ...field.RelationField) IRemoteVideoDo
	FirstOrInit() (*model.RemoteVideo, error)
	FirstOrCreate() (*model.RemoteVideo, error)
	FindByPage(offset int, limit int) (result []*model.RemoteVideo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRemoteVideoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r remoteVideoDo) Debug() IRemoteVideoDo {
	return r.withDO(r.DO.Debug())
}

func (r remoteVideoDo) WithContext(ctx context.Context) IRemoteVideoDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r remoteVideoDo) ReadDB() IRemoteVideoDo {
	return r.Clauses(dbresolver.Read)
}

func (r remoteVideoDo) WriteDB() IRemoteVideoDo {
	return r.Clauses(dbresolver.Write)
}

func (r remoteVideoDo) Session(config *gorm.Session) IRemoteVideoDo {
	return r.withDO(r.DO.Session(config))
}

func (r remoteVideoDo) Clauses(conds ...clause.Expression) IRemoteVideoDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r remoteVideoDo) Returning(value interface{}, columns ...string) IRemoteVideoDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r remoteVideoDo) Not(conds ...gen.Condition) IRemoteVideoDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r remoteVideoDo) Or(conds ...gen.Condition) IRemoteVideoDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r remoteVideoDo) Select(conds ...field.Expr) IRemoteVideoDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r remoteVideoDo) Where(conds ...gen.Condition) IRemoteVideoDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r remoteVideoDo) Order(conds ...field.Expr) IRemoteVideoDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r remoteVideoDo) Distinct(cols ...field.Expr) IRemoteVideoDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r remoteVideoDo) Omit(cols ...field.Expr) IRemoteVideoDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r remoteVideoDo) Join(table schema.Tabler, on ...field.Expr) IRemoteVideoDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r remoteVideoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRemoteVideoDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r remoteVideoDo) RightJoin(table schema.Tabler, on ...field.Expr) IRemoteVideoDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r remoteVideoDo) Group(cols ...field.Expr) IRemoteVideoDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r remoteVideoDo) Having(conds ...gen.Condition) IRemoteVideoDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r remoteVideoDo) Limit(limit int) IRemoteVideoDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r remoteVideoDo) Offset(offset int) IRemoteVideoDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r remoteVideoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRemoteVideoDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r remoteVideoDo) Unscoped() IRemoteVideoDo {
	return r.withDO(r.DO.Unscoped())
}

func (r remoteVideoDo) Create(values ...*model.RemoteVideo) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r remoteVideoDo) CreateInBatches(values []*model.RemoteVideo, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r remoteVideoDo) Save(values ...*model.RemoteVideo) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r remoteVideoDo) First() (*model.RemoteVideo, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RemoteVideo), nil
	}
}

func (r remoteVideoDo) Take() (*model.RemoteVideo, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RemoteVideo), nil
	}
}

func (r remoteVideoDo) Last() (*model.RemoteVideo, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RemoteVideo), nil
	}
}

func (r remoteVideoDo) Find() ([]*model.RemoteVideo, error) {
	result, err := r.DO.Find()
	return result.([]*model.RemoteVideo), err
}

func (r remoteVideoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RemoteVideo, err error) {
	buf := make([]*model.RemoteVideo, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r remoteVideoDo) FindInBatches(result *[]*model.RemoteVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r remoteVideoDo) Attrs(attrs ...field.AssignExpr) IRemoteVideoDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r remoteVideoDo) Assign(attrs ...field.AssignExpr) IRemoteVideoDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r remoteVideoDo) Joins(fields ...field.RelationField) IRemoteVideoDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r remoteVideoDo) Preload(fields ...field.RelationField) IRemoteVideoDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r remoteVideoDo) FirstOrInit() (*model.RemoteVideo, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RemoteVideo), nil
	}
}

func (r remoteVideoDo) FirstOrCreate() (*model.RemoteVideo, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RemoteVideo), nil
	}
}

func (r remoteVideoDo) FindByPage(offset int, limit int) (result []*model.RemoteVideo, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r remoteVideoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r remoteVideoDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r remoteVideoDo) Delete(models ...*model.RemoteVideo) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *remoteVideoDo) withDO(do gen.Dao) *remoteVideoDo {
	r.DO = *do.(*gen.DO)
	return r
}
