// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newStream(db *gorm.DB, opts ...gen.DOOption) stream {
	_stream := stream{}

	_stream.streamDo.UseDB(db, opts...)
	_stream.streamDo.UseModel(&model.Stream{})

	tableName := _stream.streamDo.TableName()
	_stream.ALL = field.NewAsterisk(tableName)
	_stream.PartID = field.NewField(tableName, "part_id")
	_stream.Idx = field.NewInt(tableName, "idx")
	_stream.Kind = field.NewString(tableName, "kind")
	_stream.Codec = field.NewString(tableName, "codec")
	_stream.Profile = field.NewString(tableName, "profile")
	_stream.Language = field.NewString(tableName, "language")
	_stream.Title = field.NewString(tableName, "title")
	_stream.IsDefault = field.NewBool(tableName, "is_default")
	_stream.Forced = field.NewBool(tableName, "forced")
	_stream.HearingImpaired = field.NewBool(tableName, "hearing_impaired")
	_stream.Commentary = field.NewBool(tableName, "commentary")
	_stream.Width = field.NewInt(tableName, "width")
	_stream.Height = field.NewInt(tableName, "height")
	_stream.FrameRate = field.NewFloat64(tableName, "frame_rate")
	_stream.BitDepth = field.NewInt16(tableName, "bit_depth")
	_stream.Level = field.NewInt(tableName, "level")
	_stream.VideoRange = field.NewString(tableName, "video_range")
	_stream.DVProfile = field.NewInt16(tableName, "dv_profile")
	_stream.DVLevel = field.NewInt16(tableName, "dv_level")
	_stream.DVCompatibility = field.NewInt16(tableName, "dv_compatibility")
	_stream.Channels = field.NewInt(tableName, "channels")
	_stream.ChannelLayout = field.NewString(tableName, "channel_layout")
	_stream.SampleRate = field.NewInt(tableName, "sample_rate")
	_stream.BitrateKbps = field.NewInt(tableName, "bitrate_kbps")

	_stream.fillFieldMap()

	return _stream
}

type stream struct {
	streamDo streamDo

	ALL             field.Asterisk
	PartID          field.Field
	Idx             field.Int
	Kind            field.String
	Codec           field.String
	Profile         field.String
	Language        field.String
	Title           field.String
	IsDefault       field.Bool
	Forced          field.Bool
	HearingImpaired field.Bool
	Commentary      field.Bool
	Width           field.Int
	Height          field.Int
	FrameRate       field.Float64
	BitDepth        field.Int16
	Level           field.Int
	VideoRange      field.String
	DVProfile       field.Int16
	DVLevel         field.Int16
	DVCompatibility field.Int16
	Channels        field.Int
	ChannelLayout   field.String
	SampleRate      field.Int
	BitrateKbps     field.Int

	fieldMap map[string]field.Expr
}

func (s stream) Table(newTableName string) *stream {
	s.streamDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stream) As(alias string) *stream {
	s.streamDo.DO = *(s.streamDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stream) updateTableName(table string) *stream {
	s.ALL = field.NewAsterisk(table)
	s.PartID = field.NewField(table, "part_id")
	s.Idx = field.NewInt(table, "idx")
	s.Kind = field.NewString(table, "kind")
	s.Codec = field.NewString(table, "codec")
	s.Profile = field.NewString(table, "profile")
	s.Language = field.NewString(table, "language")
	s.Title = field.NewString(table, "title")
	s.IsDefault = field.NewBool(table, "is_default")
	s.Forced = field.NewBool(table, "forced")
	s.HearingImpaired = field.NewBool(table, "hearing_impaired")
	s.Commentary = field.NewBool(table, "commentary")
	s.Width = field.NewInt(table, "width")
	s.Height = field.NewInt(table, "height")
	s.FrameRate = field.NewFloat64(table, "frame_rate")
	s.BitDepth = field.NewInt16(table, "bit_depth")
	s.Level = field.NewInt(table, "level")
	s.VideoRange = field.NewString(table, "video_range")
	s.DVProfile = field.NewInt16(table, "dv_profile")
	s.DVLevel = field.NewInt16(table, "dv_level")
	s.DVCompatibility = field.NewInt16(table, "dv_compatibility")
	s.Channels = field.NewInt(table, "channels")
	s.ChannelLayout = field.NewString(table, "channel_layout")
	s.SampleRate = field.NewInt(table, "sample_rate")
	s.BitrateKbps = field.NewInt(table, "bitrate_kbps")

	s.fillFieldMap()

	return s
}

func (s *stream) WithContext(ctx context.Context) IStreamDo { return s.streamDo.WithContext(ctx) }

func (s stream) TableName() string { return s.streamDo.TableName() }

func (s stream) Alias() string { return s.streamDo.Alias() }

func (s stream) Columns(cols ...field.Expr) gen.Columns { return s.streamDo.Columns(cols...) }

func (s *stream) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stream) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 24)
	s.fieldMap["part_id"] = s.PartID
	s.fieldMap["idx"] = s.Idx
	s.fieldMap["kind"] = s.Kind
	s.fieldMap["codec"] = s.Codec
	s.fieldMap["profile"] = s.Profile
	s.fieldMap["language"] = s.Language
	s.fieldMap["title"] = s.Title
	s.fieldMap["is_default"] = s.IsDefault
	s.fieldMap["forced"] = s.Forced
	s.fieldMap["hearing_impaired"] = s.HearingImpaired
	s.fieldMap["commentary"] = s.Commentary
	s.fieldMap["width"] = s.Width
	s.fieldMap["height"] = s.Height
	s.fieldMap["frame_rate"] = s.FrameRate
	s.fieldMap["bit_depth"] = s.BitDepth
	s.fieldMap["level"] = s.Level
	s.fieldMap["video_range"] = s.VideoRange
	s.fieldMap["dv_profile"] = s.DVProfile
	s.fieldMap["dv_level"] = s.DVLevel
	s.fieldMap["dv_compatibility"] = s.DVCompatibility
	s.fieldMap["channels"] = s.Channels
	s.fieldMap["channel_layout"] = s.ChannelLayout
	s.fieldMap["sample_rate"] = s.SampleRate
	s.fieldMap["bitrate_kbps"] = s.BitrateKbps
}

func (s stream) clone(db *gorm.DB) stream {
	s.streamDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stream) replaceDB(db *gorm.DB) stream {
	s.streamDo.ReplaceDB(db)
	return s
}

type streamDo struct{ gen.DO }

type IStreamDo interface {
	gen.SubQuery
	Debug() IStreamDo
	WithContext(ctx context.Context) IStreamDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStreamDo
	WriteDB() IStreamDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStreamDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStreamDo
	Not(conds ...gen.Condition) IStreamDo
	Or(conds ...gen.Condition) IStreamDo
	Select(conds ...field.Expr) IStreamDo
	Where(conds ...gen.Condition) IStreamDo
	Order(conds ...field.Expr) IStreamDo
	Distinct(cols ...field.Expr) IStreamDo
	Omit(cols ...field.Expr) IStreamDo
	Join(table schema.Tabler, on ...field.Expr) IStreamDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStreamDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStreamDo
	Group(cols ...field.Expr) IStreamDo
	Having(conds ...gen.Condition) IStreamDo
	Limit(limit int) IStreamDo
	Offset(offset int) IStreamDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStreamDo
	Unscoped() IStreamDo
	Create(values ...*model.Stream) error
	CreateInBatches(values []*model.Stream, batchSize int) error
	Save(values ...*model.Stream) error
	First() (*model.Stream, error)
	Take() (*model.Stream, error)
	Last() (*model.Stream, error)
	Find() ([]*model.Stream, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Stream, err error)
	FindInBatches(result *[]*model.Stream, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Stream) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStreamDo
	Assign(attrs ...field.AssignExpr) IStreamDo
	Joins(fields ...field.RelationField) IStreamDo
	Preload(fields ...field.RelationField) IStreamDo
	FirstOrInit() (*model.Stream, error)
	FirstOrCreate() (*model.Stream, error)
	FindByPage(offset int, limit int) (result []*model.Stream, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStreamDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s streamDo) Debug() IStreamDo {
	return s.withDO(s.DO.Debug())
}

func (s streamDo) WithContext(ctx context.Context) IStreamDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s streamDo) ReadDB() IStreamDo {
	return s.Clauses(dbresolver.Read)
}

func (s streamDo) WriteDB() IStreamDo {
	return s.Clauses(dbresolver.Write)
}

func (s streamDo) Session(config *gorm.Session) IStreamDo {
	return s.withDO(s.DO.Session(config))
}

func (s streamDo) Clauses(conds ...clause.Expression) IStreamDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s streamDo) Returning(value interface{}, columns ...string) IStreamDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s streamDo) Not(conds ...gen.Condition) IStreamDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s streamDo) Or(conds ...gen.Condition) IStreamDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s streamDo) Select(conds ...field.Expr) IStreamDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s streamDo) Where(conds ...gen.Condition) IStreamDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s streamDo) Order(conds ...field.Expr) IStreamDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s streamDo) Distinct(cols ...field.Expr) IStreamDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s streamDo) Omit(cols ...field.Expr) IStreamDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s streamDo) Join(table schema.Tabler, on ...field.Expr) IStreamDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s streamDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStreamDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s streamDo) RightJoin(table schema.Tabler, on ...field.Expr) IStreamDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s streamDo) Group(cols ...field.Expr) IStreamDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s streamDo) Having(conds ...gen.Condition) IStreamDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s streamDo) Limit(limit int) IStreamDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s streamDo) Offset(offset int) IStreamDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s streamDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStreamDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s streamDo) Unscoped() IStreamDo {
	return s.withDO(s.DO.Unscoped())
}

func (s streamDo) Create(values ...*model.Stream) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s streamDo) CreateInBatches(values []*model.Stream, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s streamDo) Save(values ...*model.Stream) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s streamDo) First() (*model.Stream, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Stream), nil
	}
}

func (s streamDo) Take() (*model.Stream, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Stream), nil
	}
}

func (s streamDo) Last() (*model.Stream, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Stream), nil
	}
}

func (s streamDo) Find() ([]*model.Stream, error) {
	result, err := s.DO.Find()
	return result.([]*model.Stream), err
}

func (s streamDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Stream, err error) {
	buf := make([]*model.Stream, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s streamDo) FindInBatches(result *[]*model.Stream, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s streamDo) Attrs(attrs ...field.AssignExpr) IStreamDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s streamDo) Assign(attrs ...field.AssignExpr) IStreamDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s streamDo) Joins(fields ...field.RelationField) IStreamDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s streamDo) Preload(fields ...field.RelationField) IStreamDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s streamDo) FirstOrInit() (*model.Stream, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Stream), nil
	}
}

func (s streamDo) FirstOrCreate() (*model.Stream, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Stream), nil
	}
}

func (s streamDo) FindByPage(offset int, limit int) (result []*model.Stream, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s streamDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s streamDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s streamDo) Delete(models ...*model.Stream) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *streamDo) withDO(do gen.Dao) *streamDo {
	s.DO = *do.(*gen.DO)
	return s
}
