// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newSubtitleFile(db *gorm.DB, opts ...gen.DOOption) subtitleFile {
	_subtitleFile := subtitleFile{}

	_subtitleFile.subtitleFileDo.UseDB(db, opts...)
	_subtitleFile.subtitleFileDo.UseModel(&model.SubtitleFile{})

	tableName := _subtitleFile.subtitleFileDo.TableName()
	_subtitleFile.ALL = field.NewAsterisk(tableName)
	_subtitleFile.VersionID = field.NewField(tableName, "version_id")
	_subtitleFile.LibraryID = field.NewField(tableName, "library_id")
	_subtitleFile.RelPath = field.NewString(tableName, "rel_path")
	_subtitleFile.Codec = field.NewString(tableName, "codec")
	_subtitleFile.Language = field.NewString(tableName, "language")
	_subtitleFile.Title = field.NewString(tableName, "title")
	_subtitleFile.Forced = field.NewBool(tableName, "forced")
	_subtitleFile.IsDefault = field.NewBool(tableName, "is_default")
	_subtitleFile.HearingImpaired = field.NewBool(tableName, "hearing_impaired")
	_subtitleFile.SizeBytes = field.NewInt64(tableName, "size_bytes")
	_subtitleFile.MtimeNS = field.NewInt64(tableName, "mtime_ns")

	_subtitleFile.fillFieldMap()

	return _subtitleFile
}

type subtitleFile struct {
	subtitleFileDo subtitleFileDo

	ALL             field.Asterisk
	VersionID       field.Field
	LibraryID       field.Field
	RelPath         field.String
	Codec           field.String
	Language        field.String
	Title           field.String
	Forced          field.Bool
	IsDefault       field.Bool
	HearingImpaired field.Bool
	SizeBytes       field.Int64
	MtimeNS         field.Int64

	fieldMap map[string]field.Expr
}

func (s subtitleFile) Table(newTableName string) *subtitleFile {
	s.subtitleFileDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s subtitleFile) As(alias string) *subtitleFile {
	s.subtitleFileDo.DO = *(s.subtitleFileDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *subtitleFile) updateTableName(table string) *subtitleFile {
	s.ALL = field.NewAsterisk(table)
	s.VersionID = field.NewField(table, "version_id")
	s.LibraryID = field.NewField(table, "library_id")
	s.RelPath = field.NewString(table, "rel_path")
	s.Codec = field.NewString(table, "codec")
	s.Language = field.NewString(table, "language")
	s.Title = field.NewString(table, "title")
	s.Forced = field.NewBool(table, "forced")
	s.IsDefault = field.NewBool(table, "is_default")
	s.HearingImpaired = field.NewBool(table, "hearing_impaired")
	s.SizeBytes = field.NewInt64(table, "size_bytes")
	s.MtimeNS = field.NewInt64(table, "mtime_ns")

	s.fillFieldMap()

	return s
}

func (s *subtitleFile) WithContext(ctx context.Context) ISubtitleFileDo {
	return s.subtitleFileDo.WithContext(ctx)
}

func (s subtitleFile) TableName() string { return s.subtitleFileDo.TableName() }

func (s subtitleFile) Alias() string { return s.subtitleFileDo.Alias() }

func (s subtitleFile) Columns(cols ...field.Expr) gen.Columns {
	return s.subtitleFileDo.Columns(cols...)
}

func (s *subtitleFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *subtitleFile) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["version_id"] = s.VersionID
	s.fieldMap["library_id"] = s.LibraryID
	s.fieldMap["rel_path"] = s.RelPath
	s.fieldMap["codec"] = s.Codec
	s.fieldMap["language"] = s.Language
	s.fieldMap["title"] = s.Title
	s.fieldMap["forced"] = s.Forced
	s.fieldMap["is_default"] = s.IsDefault
	s.fieldMap["hearing_impaired"] = s.HearingImpaired
	s.fieldMap["size_bytes"] = s.SizeBytes
	s.fieldMap["mtime_ns"] = s.MtimeNS
}

func (s subtitleFile) clone(db *gorm.DB) subtitleFile {
	s.subtitleFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s subtitleFile) replaceDB(db *gorm.DB) subtitleFile {
	s.subtitleFileDo.ReplaceDB(db)
	return s
}

type subtitleFileDo struct{ gen.DO }

type ISubtitleFileDo interface {
	gen.SubQuery
	Debug() ISubtitleFileDo
	WithContext(ctx context.Context) ISubtitleFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISubtitleFileDo
	WriteDB() ISubtitleFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISubtitleFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISubtitleFileDo
	Not(conds ...gen.Condition) ISubtitleFileDo
	Or(conds ...gen.Condition) ISubtitleFileDo
	Select(conds ...field.Expr) ISubtitleFileDo
	Where(conds ...gen.Condition) ISubtitleFileDo
	Order(conds ...field.Expr) ISubtitleFileDo
	Distinct(cols ...field.Expr) ISubtitleFileDo
	Omit(cols ...field.Expr) ISubtitleFileDo
	Join(table schema.Tabler, on ...field.Expr) ISubtitleFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISubtitleFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISubtitleFileDo
	Group(cols ...field.Expr) ISubtitleFileDo
	Having(conds ...gen.Condition) ISubtitleFileDo
	Limit(limit int) ISubtitleFileDo
	Offset(offset int) ISubtitleFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISubtitleFileDo
	Unscoped() ISubtitleFileDo
	Create(values ...*model.SubtitleFile) error
	CreateInBatches(values []*model.SubtitleFile, batchSize int) error
	Save(values ...*model.SubtitleFile) error
	First() (*model.SubtitleFile, error)
	Take() (*model.SubtitleFile, error)
	Last() (*model.SubtitleFile, error)
	Find() ([]*model.SubtitleFile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SubtitleFile, err error)
	FindInBatches(result *[]*model.SubtitleFile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SubtitleFile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISubtitleFileDo
	Assign(attrs ...field.AssignExpr) ISubtitleFileDo
	Joins(fields ...field.RelationField) ISubtitleFileDo
	Preload(fields ...field.RelationField) ISubtitleFileDo
	FirstOrInit() (*model.SubtitleFile, error)
	FirstOrCreate() (*model.SubtitleFile, error)
	FindByPage(offset int, limit int) (result []*model.SubtitleFile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISubtitleFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s subtitleFileDo) Debug() ISubtitleFileDo {
	return s.withDO(s.DO.Debug())
}

func (s subtitleFileDo) WithContext(ctx context.Context) ISubtitleFileDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s subtitleFileDo) ReadDB() ISubtitleFileDo {
	return s.Clauses(dbresolver.Read)
}

func (s subtitleFileDo) WriteDB() ISubtitleFileDo {
	return s.Clauses(dbresolver.Write)
}

func (s subtitleFileDo) Session(config *gorm.Session) ISubtitleFileDo {
	return s.withDO(s.DO.Session(config))
}

func (s subtitleFileDo) Clauses(conds ...clause.Expression) ISubtitleFileDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s subtitleFileDo) Returning(value interface{}, columns ...string) ISubtitleFileDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s subtitleFileDo) Not(conds ...gen.Condition) ISubtitleFileDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s subtitleFileDo) Or(conds ...gen.Condition) ISubtitleFileDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s subtitleFileDo) Select(conds ...field.Expr) ISubtitleFileDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s subtitleFileDo) Where(conds ...gen.Condition) ISubtitleFileDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s subtitleFileDo) Order(conds ...field.Expr) ISubtitleFileDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s subtitleFileDo) Distinct(cols ...field.Expr) ISubtitleFileDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s subtitleFileDo) Omit(cols ...field.Expr) ISubtitleFileDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s subtitleFileDo) Join(table schema.Tabler, on ...field.Expr) ISubtitleFileDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s subtitleFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISubtitleFileDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s subtitleFileDo) RightJoin(table schema.Tabler, on ...field.Expr) ISubtitleFileDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s subtitleFileDo) Group(cols ...field.Expr) ISubtitleFileDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s subtitleFileDo) Having(conds ...gen.Condition) ISubtitleFileDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s subtitleFileDo) Limit(limit int) ISubtitleFileDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s subtitleFileDo) Offset(offset int) ISubtitleFileDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s subtitleFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISubtitleFileDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s subtitleFileDo) Unscoped() ISubtitleFileDo {
	return s.withDO(s.DO.Unscoped())
}

func (s subtitleFileDo) Create(values ...*model.SubtitleFile) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s subtitleFileDo) CreateInBatches(values []*model.SubtitleFile, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s subtitleFileDo) Save(values ...*model.SubtitleFile) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s subtitleFileDo) First() (*model.SubtitleFile, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubtitleFile), nil
	}
}

func (s subtitleFileDo) Take() (*model.SubtitleFile, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubtitleFile), nil
	}
}

func (s subtitleFileDo) Last() (*model.SubtitleFile, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubtitleFile), nil
	}
}

func (s subtitleFileDo) Find() ([]*model.SubtitleFile, error) {
	result, err := s.DO.Find()
	return result.([]*model.SubtitleFile), err
}

func (s subtitleFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SubtitleFile, err error) {
	buf := make([]*model.SubtitleFile, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s subtitleFileDo) FindInBatches(result *[]*model.SubtitleFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s subtitleFileDo) Attrs(attrs ...field.AssignExpr) ISubtitleFileDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s subtitleFileDo) Assign(attrs ...field.AssignExpr) ISubtitleFileDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s subtitleFileDo) Joins(fields ...field.RelationField) ISubtitleFileDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s subtitleFileDo) Preload(fields ...field.RelationField) ISubtitleFileDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s subtitleFileDo) FirstOrInit() (*model.SubtitleFile, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubtitleFile), nil
	}
}

func (s subtitleFileDo) FirstOrCreate() (*model.SubtitleFile, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SubtitleFile), nil
	}
}

func (s subtitleFileDo) FindByPage(offset int, limit int) (result []*model.SubtitleFile, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s subtitleFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s subtitleFileDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s subtitleFileDo) Delete(models ...*model.SubtitleFile) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *subtitleFileDo) withDO(do gen.Dao) *subtitleFileDo {
	s.DO = *do.(*gen.DO)
	return s
}
