// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newTaskState(db *gorm.DB, opts ...gen.DOOption) taskState {
	_taskState := taskState{}

	_taskState.taskStateDo.UseDB(db, opts...)
	_taskState.taskStateDo.UseModel(&model.TaskState{})

	tableName := _taskState.taskStateDo.TableName()
	_taskState.ALL = field.NewAsterisk(tableName)
	_taskState.Key = field.NewString(tableName, "key")
	_taskState.StartedAt = field.NewTime(tableName, "started_at")
	_taskState.FinishedAt = field.NewTime(tableName, "finished_at")
	_taskState.Result = field.NewString(tableName, "result")
	_taskState.Error = field.NewString(tableName, "error")

	_taskState.fillFieldMap()

	return _taskState
}

type taskState struct {
	taskStateDo taskStateDo

	ALL        field.Asterisk
	Key        field.String
	StartedAt  field.Time
	FinishedAt field.Time
	Result     field.String
	Error      field.String

	fieldMap map[string]field.Expr
}

func (t taskState) Table(newTableName string) *taskState {
	t.taskStateDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t taskState) As(alias string) *taskState {
	t.taskStateDo.DO = *(t.taskStateDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *taskState) updateTableName(table string) *taskState {
	t.ALL = field.NewAsterisk(table)
	t.Key = field.NewString(table, "key")
	t.StartedAt = field.NewTime(table, "started_at")
	t.FinishedAt = field.NewTime(table, "finished_at")
	t.Result = field.NewString(table, "result")
	t.Error = field.NewString(table, "error")

	t.fillFieldMap()

	return t
}

func (t *taskState) WithContext(ctx context.Context) ITaskStateDo {
	return t.taskStateDo.WithContext(ctx)
}

func (t taskState) TableName() string { return t.taskStateDo.TableName() }

func (t taskState) Alias() string { return t.taskStateDo.Alias() }

func (t taskState) Columns(cols ...field.Expr) gen.Columns { return t.taskStateDo.Columns(cols...) }

func (t *taskState) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *taskState) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["key"] = t.Key
	t.fieldMap["started_at"] = t.StartedAt
	t.fieldMap["finished_at"] = t.FinishedAt
	t.fieldMap["result"] = t.Result
	t.fieldMap["error"] = t.Error
}

func (t taskState) clone(db *gorm.DB) taskState {
	t.taskStateDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t taskState) replaceDB(db *gorm.DB) taskState {
	t.taskStateDo.ReplaceDB(db)
	return t
}

type taskStateDo struct{ gen.DO }

type ITaskStateDo interface {
	gen.SubQuery
	Debug() ITaskStateDo
	WithContext(ctx context.Context) ITaskStateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITaskStateDo
	WriteDB() ITaskStateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITaskStateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITaskStateDo
	Not(conds ...gen.Condition) ITaskStateDo
	Or(conds ...gen.Condition) ITaskStateDo
	Select(conds ...field.Expr) ITaskStateDo
	Where(conds ...gen.Condition) ITaskStateDo
	Order(conds ...field.Expr) ITaskStateDo
	Distinct(cols ...field.Expr) ITaskStateDo
	Omit(cols ...field.Expr) ITaskStateDo
	Join(table schema.Tabler, on ...field.Expr) ITaskStateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITaskStateDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITaskStateDo
	Group(cols ...field.Expr) ITaskStateDo
	Having(conds ...gen.Condition) ITaskStateDo
	Limit(limit int) ITaskStateDo
	Offset(offset int) ITaskStateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskStateDo
	Unscoped() ITaskStateDo
	Create(values ...*model.TaskState) error
	CreateInBatches(values []*model.TaskState, batchSize int) error
	Save(values ...*model.TaskState) error
	First() (*model.TaskState, error)
	Take() (*model.TaskState, error)
	Last() (*model.TaskState, error)
	Find() ([]*model.TaskState, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TaskState, err error)
	FindInBatches(result *[]*model.TaskState, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TaskState) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITaskStateDo
	Assign(attrs ...field.AssignExpr) ITaskStateDo
	Joins(fields ...field.RelationField) ITaskStateDo
	Preload(fields ...field.RelationField) ITaskStateDo
	FirstOrInit() (*model.TaskState, error)
	FirstOrCreate() (*model.TaskState, error)
	FindByPage(offset int, limit int) (result []*model.TaskState, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITaskStateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t taskStateDo) Debug() ITaskStateDo {
	return t.withDO(t.DO.Debug())
}

func (t taskStateDo) WithContext(ctx context.Context) ITaskStateDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taskStateDo) ReadDB() ITaskStateDo {
	return t.Clauses(dbresolver.Read)
}

func (t taskStateDo) WriteDB() ITaskStateDo {
	return t.Clauses(dbresolver.Write)
}

func (t taskStateDo) Session(config *gorm.Session) ITaskStateDo {
	return t.withDO(t.DO.Session(config))
}

func (t taskStateDo) Clauses(conds ...clause.Expression) ITaskStateDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taskStateDo) Returning(value interface{}, columns ...string) ITaskStateDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taskStateDo) Not(conds ...gen.Condition) ITaskStateDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taskStateDo) Or(conds ...gen.Condition) ITaskStateDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taskStateDo) Select(conds ...field.Expr) ITaskStateDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taskStateDo) Where(conds ...gen.Condition) ITaskStateDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taskStateDo) Order(conds ...field.Expr) ITaskStateDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taskStateDo) Distinct(cols ...field.Expr) ITaskStateDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taskStateDo) Omit(cols ...field.Expr) ITaskStateDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taskStateDo) Join(table schema.Tabler, on ...field.Expr) ITaskStateDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taskStateDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITaskStateDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taskStateDo) RightJoin(table schema.Tabler, on ...field.Expr) ITaskStateDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taskStateDo) Group(cols ...field.Expr) ITaskStateDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taskStateDo) Having(conds ...gen.Condition) ITaskStateDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taskStateDo) Limit(limit int) ITaskStateDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taskStateDo) Offset(offset int) ITaskStateDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taskStateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskStateDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taskStateDo) Unscoped() ITaskStateDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taskStateDo) Create(values ...*model.TaskState) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taskStateDo) CreateInBatches(values []*model.TaskState, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taskStateDo) Save(values ...*model.TaskState) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taskStateDo) First() (*model.TaskState, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskState), nil
	}
}

func (t taskStateDo) Take() (*model.TaskState, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskState), nil
	}
}

func (t taskStateDo) Last() (*model.TaskState, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskState), nil
	}
}

func (t taskStateDo) Find() ([]*model.TaskState, error) {
	result, err := t.DO.Find()
	return result.([]*model.TaskState), err
}

func (t taskStateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TaskState, err error) {
	buf := make([]*model.TaskState, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taskStateDo) FindInBatches(result *[]*model.TaskState, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taskStateDo) Attrs(attrs ...field.AssignExpr) ITaskStateDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taskStateDo) Assign(attrs ...field.AssignExpr) ITaskStateDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taskStateDo) Joins(fields ...field.RelationField) ITaskStateDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taskStateDo) Preload(fields ...field.RelationField) ITaskStateDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taskStateDo) FirstOrInit() (*model.TaskState, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskState), nil
	}
}

func (t taskStateDo) FirstOrCreate() (*model.TaskState, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskState), nil
	}
}

func (t taskStateDo) FindByPage(offset int, limit int) (result []*model.TaskState, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taskStateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taskStateDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taskStateDo) Delete(models ...*model.TaskState) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taskStateDo) withDO(do gen.Dao) *taskStateDo {
	t.DO = *do.(*gen.DO)
	return t
}
