// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newTheme(db *gorm.DB, opts ...gen.DOOption) theme {
	_theme := theme{}

	_theme.themeDo.UseDB(db, opts...)
	_theme.themeDo.UseModel(&model.Theme{})

	tableName := _theme.themeDo.TableName()
	_theme.ALL = field.NewAsterisk(tableName)
	_theme.ID = field.NewField(tableName, "id")
	_theme.ItemID = field.NewField(tableName, "item_id")
	_theme.Source = field.NewString(tableName, "source")
	_theme.Place = field.NewString(tableName, "place")
	_theme.Position = field.NewInt16(tableName, "position")
	_theme.Folder = field.NewString(tableName, "folder")

	_theme.fillFieldMap()

	return _theme
}

type theme struct {
	themeDo themeDo

	ALL      field.Asterisk
	ID       field.Field
	ItemID   field.Field
	Source   field.String
	Place    field.String
	Position field.Int16
	Folder   field.String

	fieldMap map[string]field.Expr
}

func (t theme) Table(newTableName string) *theme {
	t.themeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t theme) As(alias string) *theme {
	t.themeDo.DO = *(t.themeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *theme) updateTableName(table string) *theme {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewField(table, "id")
	t.ItemID = field.NewField(table, "item_id")
	t.Source = field.NewString(table, "source")
	t.Place = field.NewString(table, "place")
	t.Position = field.NewInt16(table, "position")
	t.Folder = field.NewString(table, "folder")

	t.fillFieldMap()

	return t
}

func (t *theme) WithContext(ctx context.Context) IThemeDo { return t.themeDo.WithContext(ctx) }

func (t theme) TableName() string { return t.themeDo.TableName() }

func (t theme) Alias() string { return t.themeDo.Alias() }

func (t theme) Columns(cols ...field.Expr) gen.Columns { return t.themeDo.Columns(cols...) }

func (t *theme) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *theme) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["id"] = t.ID
	t.fieldMap["item_id"] = t.ItemID
	t.fieldMap["source"] = t.Source
	t.fieldMap["place"] = t.Place
	t.fieldMap["position"] = t.Position
	t.fieldMap["folder"] = t.Folder
}

func (t theme) clone(db *gorm.DB) theme {
	t.themeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t theme) replaceDB(db *gorm.DB) theme {
	t.themeDo.ReplaceDB(db)
	return t
}

type themeDo struct{ gen.DO }

type IThemeDo interface {
	gen.SubQuery
	Debug() IThemeDo
	WithContext(ctx context.Context) IThemeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IThemeDo
	WriteDB() IThemeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IThemeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IThemeDo
	Not(conds ...gen.Condition) IThemeDo
	Or(conds ...gen.Condition) IThemeDo
	Select(conds ...field.Expr) IThemeDo
	Where(conds ...gen.Condition) IThemeDo
	Order(conds ...field.Expr) IThemeDo
	Distinct(cols ...field.Expr) IThemeDo
	Omit(cols ...field.Expr) IThemeDo
	Join(table schema.Tabler, on ...field.Expr) IThemeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IThemeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IThemeDo
	Group(cols ...field.Expr) IThemeDo
	Having(conds ...gen.Condition) IThemeDo
	Limit(limit int) IThemeDo
	Offset(offset int) IThemeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IThemeDo
	Unscoped() IThemeDo
	Create(values ...*model.Theme) error
	CreateInBatches(values []*model.Theme, batchSize int) error
	Save(values ...*model.Theme) error
	First() (*model.Theme, error)
	Take() (*model.Theme, error)
	Last() (*model.Theme, error)
	Find() ([]*model.Theme, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Theme, err error)
	FindInBatches(result *[]*model.Theme, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Theme) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IThemeDo
	Assign(attrs ...field.AssignExpr) IThemeDo
	Joins(fields ...field.RelationField) IThemeDo
	Preload(fields ...field.RelationField) IThemeDo
	FirstOrInit() (*model.Theme, error)
	FirstOrCreate() (*model.Theme, error)
	FindByPage(offset int, limit int) (result []*model.Theme, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IThemeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t themeDo) Debug() IThemeDo {
	return t.withDO(t.DO.Debug())
}

func (t themeDo) WithContext(ctx context.Context) IThemeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t themeDo) ReadDB() IThemeDo {
	return t.Clauses(dbresolver.Read)
}

func (t themeDo) WriteDB() IThemeDo {
	return t.Clauses(dbresolver.Write)
}

func (t themeDo) Session(config *gorm.Session) IThemeDo {
	return t.withDO(t.DO.Session(config))
}

func (t themeDo) Clauses(conds ...clause.Expression) IThemeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t themeDo) Returning(value interface{}, columns ...string) IThemeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t themeDo) Not(conds ...gen.Condition) IThemeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t themeDo) Or(conds ...gen.Condition) IThemeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t themeDo) Select(conds ...field.Expr) IThemeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t themeDo) Where(conds ...gen.Condition) IThemeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t themeDo) Order(conds ...field.Expr) IThemeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t themeDo) Distinct(cols ...field.Expr) IThemeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t themeDo) Omit(cols ...field.Expr) IThemeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t themeDo) Join(table schema.Tabler, on ...field.Expr) IThemeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t themeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IThemeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t themeDo) RightJoin(table schema.Tabler, on ...field.Expr) IThemeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t themeDo) Group(cols ...field.Expr) IThemeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t themeDo) Having(conds ...gen.Condition) IThemeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t themeDo) Limit(limit int) IThemeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t themeDo) Offset(offset int) IThemeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t themeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IThemeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t themeDo) Unscoped() IThemeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t themeDo) Create(values ...*model.Theme) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t themeDo) CreateInBatches(values []*model.Theme, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t themeDo) Save(values ...*model.Theme) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t themeDo) First() (*model.Theme, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Theme), nil
	}
}

func (t themeDo) Take() (*model.Theme, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Theme), nil
	}
}

func (t themeDo) Last() (*model.Theme, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Theme), nil
	}
}

func (t themeDo) Find() ([]*model.Theme, error) {
	result, err := t.DO.Find()
	return result.([]*model.Theme), err
}

func (t themeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Theme, err error) {
	buf := make([]*model.Theme, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t themeDo) FindInBatches(result *[]*model.Theme, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t themeDo) Attrs(attrs ...field.AssignExpr) IThemeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t themeDo) Assign(attrs ...field.AssignExpr) IThemeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t themeDo) Joins(fields ...field.RelationField) IThemeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t themeDo) Preload(fields ...field.RelationField) IThemeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t themeDo) FirstOrInit() (*model.Theme, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Theme), nil
	}
}

func (t themeDo) FirstOrCreate() (*model.Theme, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Theme), nil
	}
}

func (t themeDo) FindByPage(offset int, limit int) (result []*model.Theme, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t themeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t themeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t themeDo) Delete(models ...*model.Theme) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *themeDo) withDO(do gen.Dao) *themeDo {
	t.DO = *do.(*gen.DO)
	return t
}
