// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newWatchState(db *gorm.DB, opts ...gen.DOOption) watchState {
	_watchState := watchState{}

	_watchState.watchStateDo.UseDB(db, opts...)
	_watchState.watchStateDo.UseModel(&model.WatchState{})

	tableName := _watchState.watchStateDo.TableName()
	_watchState.ALL = field.NewAsterisk(tableName)
	_watchState.ProfileID = field.NewField(tableName, "profile_id")
	_watchState.ItemID = field.NewField(tableName, "item_id")
	_watchState.PositionMS = field.NewInt64(tableName, "position_ms")
	_watchState.Plays = field.NewInt(tableName, "plays")
	_watchState.WatchedAt = field.NewTime(tableName, "watched_at")
	_watchState.LastPlayedAt = field.NewTime(tableName, "last_played_at")

	_watchState.fillFieldMap()

	return _watchState
}

type watchState struct {
	watchStateDo watchStateDo

	ALL          field.Asterisk
	ProfileID    field.Field
	ItemID       field.Field
	PositionMS   field.Int64
	Plays        field.Int
	WatchedAt    field.Time
	LastPlayedAt field.Time

	fieldMap map[string]field.Expr
}

func (w watchState) Table(newTableName string) *watchState {
	w.watchStateDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w watchState) As(alias string) *watchState {
	w.watchStateDo.DO = *(w.watchStateDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *watchState) updateTableName(table string) *watchState {
	w.ALL = field.NewAsterisk(table)
	w.ProfileID = field.NewField(table, "profile_id")
	w.ItemID = field.NewField(table, "item_id")
	w.PositionMS = field.NewInt64(table, "position_ms")
	w.Plays = field.NewInt(table, "plays")
	w.WatchedAt = field.NewTime(table, "watched_at")
	w.LastPlayedAt = field.NewTime(table, "last_played_at")

	w.fillFieldMap()

	return w
}

func (w *watchState) WithContext(ctx context.Context) IWatchStateDo {
	return w.watchStateDo.WithContext(ctx)
}

func (w watchState) TableName() string { return w.watchStateDo.TableName() }

func (w watchState) Alias() string { return w.watchStateDo.Alias() }

func (w watchState) Columns(cols ...field.Expr) gen.Columns { return w.watchStateDo.Columns(cols...) }

func (w *watchState) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *watchState) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 6)
	w.fieldMap["profile_id"] = w.ProfileID
	w.fieldMap["item_id"] = w.ItemID
	w.fieldMap["position_ms"] = w.PositionMS
	w.fieldMap["plays"] = w.Plays
	w.fieldMap["watched_at"] = w.WatchedAt
	w.fieldMap["last_played_at"] = w.LastPlayedAt
}

func (w watchState) clone(db *gorm.DB) watchState {
	w.watchStateDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w watchState) replaceDB(db *gorm.DB) watchState {
	w.watchStateDo.ReplaceDB(db)
	return w
}

type watchStateDo struct{ gen.DO }

type IWatchStateDo interface {
	gen.SubQuery
	Debug() IWatchStateDo
	WithContext(ctx context.Context) IWatchStateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWatchStateDo
	WriteDB() IWatchStateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWatchStateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWatchStateDo
	Not(conds ...gen.Condition) IWatchStateDo
	Or(conds ...gen.Condition) IWatchStateDo
	Select(conds ...field.Expr) IWatchStateDo
	Where(conds ...gen.Condition) IWatchStateDo
	Order(conds ...field.Expr) IWatchStateDo
	Distinct(cols ...field.Expr) IWatchStateDo
	Omit(cols ...field.Expr) IWatchStateDo
	Join(table schema.Tabler, on ...field.Expr) IWatchStateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWatchStateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWatchStateDo
	Group(cols ...field.Expr) IWatchStateDo
	Having(conds ...gen.Condition) IWatchStateDo
	Limit(limit int) IWatchStateDo
	Offset(offset int) IWatchStateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWatchStateDo
	Unscoped() IWatchStateDo
	Create(values ...*model.WatchState) error
	CreateInBatches(values []*model.WatchState, batchSize int) error
	Save(values ...*model.WatchState) error
	First() (*model.WatchState, error)
	Take() (*model.WatchState, error)
	Last() (*model.WatchState, error)
	Find() ([]*model.WatchState, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WatchState, err error)
	FindInBatches(result *[]*model.WatchState, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WatchState) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWatchStateDo
	Assign(attrs ...field.AssignExpr) IWatchStateDo
	Joins(fields ...field.RelationField) IWatchStateDo
	Preload(fields ...field.RelationField) IWatchStateDo
	FirstOrInit() (*model.WatchState, error)
	FirstOrCreate() (*model.WatchState, error)
	FindByPage(offset int, limit int) (result []*model.WatchState, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWatchStateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w watchStateDo) Debug() IWatchStateDo {
	return w.withDO(w.DO.Debug())
}

func (w watchStateDo) WithContext(ctx context.Context) IWatchStateDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w watchStateDo) ReadDB() IWatchStateDo {
	return w.Clauses(dbresolver.Read)
}

func (w watchStateDo) WriteDB() IWatchStateDo {
	return w.Clauses(dbresolver.Write)
}

func (w watchStateDo) Session(config *gorm.Session) IWatchStateDo {
	return w.withDO(w.DO.Session(config))
}

func (w watchStateDo) Clauses(conds ...clause.Expression) IWatchStateDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w watchStateDo) Returning(value interface{}, columns ...string) IWatchStateDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w watchStateDo) Not(conds ...gen.Condition) IWatchStateDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w watchStateDo) Or(conds ...gen.Condition) IWatchStateDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w watchStateDo) Select(conds ...field.Expr) IWatchStateDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w watchStateDo) Where(conds ...gen.Condition) IWatchStateDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w watchStateDo) Order(conds ...field.Expr) IWatchStateDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w watchStateDo) Distinct(cols ...field.Expr) IWatchStateDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w watchStateDo) Omit(cols ...field.Expr) IWatchStateDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w watchStateDo) Join(table schema.Tabler, on ...field.Expr) IWatchStateDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w watchStateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWatchStateDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w watchStateDo) RightJoin(table schema.Tabler, on ...field.Expr) IWatchStateDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w watchStateDo) Group(cols ...field.Expr) IWatchStateDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w watchStateDo) Having(conds ...gen.Condition) IWatchStateDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w watchStateDo) Limit(limit int) IWatchStateDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w watchStateDo) Offset(offset int) IWatchStateDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w watchStateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWatchStateDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w watchStateDo) Unscoped() IWatchStateDo {
	return w.withDO(w.DO.Unscoped())
}

func (w watchStateDo) Create(values ...*model.WatchState) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w watchStateDo) CreateInBatches(values []*model.WatchState, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w watchStateDo) Save(values ...*model.WatchState) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w watchStateDo) First() (*model.WatchState, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WatchState), nil
	}
}

func (w watchStateDo) Take() (*model.WatchState, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WatchState), nil
	}
}

func (w watchStateDo) Last() (*model.WatchState, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WatchState), nil
	}
}

func (w watchStateDo) Find() ([]*model.WatchState, error) {
	result, err := w.DO.Find()
	return result.([]*model.WatchState), err
}

func (w watchStateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WatchState, err error) {
	buf := make([]*model.WatchState, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w watchStateDo) FindInBatches(result *[]*model.WatchState, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w watchStateDo) Attrs(attrs ...field.AssignExpr) IWatchStateDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w watchStateDo) Assign(attrs ...field.AssignExpr) IWatchStateDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w watchStateDo) Joins(fields ...field.RelationField) IWatchStateDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w watchStateDo) Preload(fields ...field.RelationField) IWatchStateDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w watchStateDo) FirstOrInit() (*model.WatchState, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WatchState), nil
	}
}

func (w watchStateDo) FirstOrCreate() (*model.WatchState, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WatchState), nil
	}
}

func (w watchStateDo) FindByPage(offset int, limit int) (result []*model.WatchState, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w watchStateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w watchStateDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w watchStateDo) Delete(models ...*model.WatchState) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *watchStateDo) withDO(do gen.Dao) *watchStateDo {
	w.DO = *do.(*gen.DO)
	return w
}
