// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newWebhookEvent(db *gorm.DB, opts ...gen.DOOption) webhookEvent {
	_webhookEvent := webhookEvent{}

	_webhookEvent.webhookEventDo.UseDB(db, opts...)
	_webhookEvent.webhookEventDo.UseModel(&model.WebhookEvent{})

	tableName := _webhookEvent.webhookEventDo.TableName()
	_webhookEvent.ALL = field.NewAsterisk(tableName)
	_webhookEvent.WebhookID = field.NewField(tableName, "webhook_id")
	_webhookEvent.Kind = field.NewString(tableName, "kind")

	_webhookEvent.fillFieldMap()

	return _webhookEvent
}

type webhookEvent struct {
	webhookEventDo webhookEventDo

	ALL       field.Asterisk
	WebhookID field.Field
	Kind      field.String

	fieldMap map[string]field.Expr
}

func (w webhookEvent) Table(newTableName string) *webhookEvent {
	w.webhookEventDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w webhookEvent) As(alias string) *webhookEvent {
	w.webhookEventDo.DO = *(w.webhookEventDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *webhookEvent) updateTableName(table string) *webhookEvent {
	w.ALL = field.NewAsterisk(table)
	w.WebhookID = field.NewField(table, "webhook_id")
	w.Kind = field.NewString(table, "kind")

	w.fillFieldMap()

	return w
}

func (w *webhookEvent) WithContext(ctx context.Context) IWebhookEventDo {
	return w.webhookEventDo.WithContext(ctx)
}

func (w webhookEvent) TableName() string { return w.webhookEventDo.TableName() }

func (w webhookEvent) Alias() string { return w.webhookEventDo.Alias() }

func (w webhookEvent) Columns(cols ...field.Expr) gen.Columns {
	return w.webhookEventDo.Columns(cols...)
}

func (w *webhookEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *webhookEvent) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 2)
	w.fieldMap["webhook_id"] = w.WebhookID
	w.fieldMap["kind"] = w.Kind
}

func (w webhookEvent) clone(db *gorm.DB) webhookEvent {
	w.webhookEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w webhookEvent) replaceDB(db *gorm.DB) webhookEvent {
	w.webhookEventDo.ReplaceDB(db)
	return w
}

type webhookEventDo struct{ gen.DO }

type IWebhookEventDo interface {
	gen.SubQuery
	Debug() IWebhookEventDo
	WithContext(ctx context.Context) IWebhookEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWebhookEventDo
	WriteDB() IWebhookEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWebhookEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWebhookEventDo
	Not(conds ...gen.Condition) IWebhookEventDo
	Or(conds ...gen.Condition) IWebhookEventDo
	Select(conds ...field.Expr) IWebhookEventDo
	Where(conds ...gen.Condition) IWebhookEventDo
	Order(conds ...field.Expr) IWebhookEventDo
	Distinct(cols ...field.Expr) IWebhookEventDo
	Omit(cols ...field.Expr) IWebhookEventDo
	Join(table schema.Tabler, on ...field.Expr) IWebhookEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWebhookEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWebhookEventDo
	Group(cols ...field.Expr) IWebhookEventDo
	Having(conds ...gen.Condition) IWebhookEventDo
	Limit(limit int) IWebhookEventDo
	Offset(offset int) IWebhookEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWebhookEventDo
	Unscoped() IWebhookEventDo
	Create(values ...*model.WebhookEvent) error
	CreateInBatches(values []*model.WebhookEvent, batchSize int) error
	Save(values ...*model.WebhookEvent) error
	First() (*model.WebhookEvent, error)
	Take() (*model.WebhookEvent, error)
	Last() (*model.WebhookEvent, error)
	Find() ([]*model.WebhookEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WebhookEvent, err error)
	FindInBatches(result *[]*model.WebhookEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WebhookEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWebhookEventDo
	Assign(attrs ...field.AssignExpr) IWebhookEventDo
	Joins(fields ...field.RelationField) IWebhookEventDo
	Preload(fields ...field.RelationField) IWebhookEventDo
	FirstOrInit() (*model.WebhookEvent, error)
	FirstOrCreate() (*model.WebhookEvent, error)
	FindByPage(offset int, limit int) (result []*model.WebhookEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWebhookEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w webhookEventDo) Debug() IWebhookEventDo {
	return w.withDO(w.DO.Debug())
}

func (w webhookEventDo) WithContext(ctx context.Context) IWebhookEventDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w webhookEventDo) ReadDB() IWebhookEventDo {
	return w.Clauses(dbresolver.Read)
}

func (w webhookEventDo) WriteDB() IWebhookEventDo {
	return w.Clauses(dbresolver.Write)
}

func (w webhookEventDo) Session(config *gorm.Session) IWebhookEventDo {
	return w.withDO(w.DO.Session(config))
}

func (w webhookEventDo) Clauses(conds ...clause.Expression) IWebhookEventDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w webhookEventDo) Returning(value interface{}, columns ...string) IWebhookEventDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w webhookEventDo) Not(conds ...gen.Condition) IWebhookEventDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w webhookEventDo) Or(conds ...gen.Condition) IWebhookEventDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w webhookEventDo) Select(conds ...field.Expr) IWebhookEventDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w webhookEventDo) Where(conds ...gen.Condition) IWebhookEventDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w webhookEventDo) Order(conds ...field.Expr) IWebhookEventDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w webhookEventDo) Distinct(cols ...field.Expr) IWebhookEventDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w webhookEventDo) Omit(cols ...field.Expr) IWebhookEventDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w webhookEventDo) Join(table schema.Tabler, on ...field.Expr) IWebhookEventDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w webhookEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWebhookEventDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w webhookEventDo) RightJoin(table schema.Tabler, on ...field.Expr) IWebhookEventDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w webhookEventDo) Group(cols ...field.Expr) IWebhookEventDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w webhookEventDo) Having(conds ...gen.Condition) IWebhookEventDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w webhookEventDo) Limit(limit int) IWebhookEventDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w webhookEventDo) Offset(offset int) IWebhookEventDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w webhookEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWebhookEventDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w webhookEventDo) Unscoped() IWebhookEventDo {
	return w.withDO(w.DO.Unscoped())
}

func (w webhookEventDo) Create(values ...*model.WebhookEvent) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w webhookEventDo) CreateInBatches(values []*model.WebhookEvent, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w webhookEventDo) Save(values ...*model.WebhookEvent) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w webhookEventDo) First() (*model.WebhookEvent, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebhookEvent), nil
	}
}

func (w webhookEventDo) Take() (*model.WebhookEvent, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebhookEvent), nil
	}
}

func (w webhookEventDo) Last() (*model.WebhookEvent, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebhookEvent), nil
	}
}

func (w webhookEventDo) Find() ([]*model.WebhookEvent, error) {
	result, err := w.DO.Find()
	return result.([]*model.WebhookEvent), err
}

func (w webhookEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WebhookEvent, err error) {
	buf := make([]*model.WebhookEvent, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w webhookEventDo) FindInBatches(result *[]*model.WebhookEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w webhookEventDo) Attrs(attrs ...field.AssignExpr) IWebhookEventDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w webhookEventDo) Assign(attrs ...field.AssignExpr) IWebhookEventDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w webhookEventDo) Joins(fields ...field.RelationField) IWebhookEventDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w webhookEventDo) Preload(fields ...field.RelationField) IWebhookEventDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w webhookEventDo) FirstOrInit() (*model.WebhookEvent, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebhookEvent), nil
	}
}

func (w webhookEventDo) FirstOrCreate() (*model.WebhookEvent, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebhookEvent), nil
	}
}

func (w webhookEventDo) FindByPage(offset int, limit int) (result []*model.WebhookEvent, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w webhookEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w webhookEventDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w webhookEventDo) Delete(models ...*model.WebhookEvent) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *webhookEventDo) withDO(do gen.Dao) *webhookEventDo {
	w.DO = *do.(*gen.DO)
	return w
}
