// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newWebhookDelivery(db *gorm.DB, opts ...gen.DOOption) webhookDelivery {
	_webhookDelivery := webhookDelivery{}

	_webhookDelivery.webhookDeliveryDo.UseDB(db, opts...)
	_webhookDelivery.webhookDeliveryDo.UseModel(&model.WebhookDelivery{})

	tableName := _webhookDelivery.webhookDeliveryDo.TableName()
	_webhookDelivery.ALL = field.NewAsterisk(tableName)
	_webhookDelivery.ID = field.NewField(tableName, "id")
	_webhookDelivery.WebhookID = field.NewField(tableName, "webhook_id")
	_webhookDelivery.Kind = field.NewString(tableName, "kind")
	_webhookDelivery.Body = field.NewString(tableName, "body")

	_webhookDelivery.fillFieldMap()

	return _webhookDelivery
}

type webhookDelivery struct {
	webhookDeliveryDo webhookDeliveryDo

	ALL       field.Asterisk
	ID        field.Field
	WebhookID field.Field
	Kind      field.String
	Body      field.String

	fieldMap map[string]field.Expr
}

func (w webhookDelivery) Table(newTableName string) *webhookDelivery {
	w.webhookDeliveryDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w webhookDelivery) As(alias string) *webhookDelivery {
	w.webhookDeliveryDo.DO = *(w.webhookDeliveryDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *webhookDelivery) updateTableName(table string) *webhookDelivery {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewField(table, "id")
	w.WebhookID = field.NewField(table, "webhook_id")
	w.Kind = field.NewString(table, "kind")
	w.Body = field.NewString(table, "body")

	w.fillFieldMap()

	return w
}

func (w *webhookDelivery) WithContext(ctx context.Context) IWebhookDeliveryDo {
	return w.webhookDeliveryDo.WithContext(ctx)
}

func (w webhookDelivery) TableName() string { return w.webhookDeliveryDo.TableName() }

func (w webhookDelivery) Alias() string { return w.webhookDeliveryDo.Alias() }

func (w webhookDelivery) Columns(cols ...field.Expr) gen.Columns {
	return w.webhookDeliveryDo.Columns(cols...)
}

func (w *webhookDelivery) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *webhookDelivery) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 4)
	w.fieldMap["id"] = w.ID
	w.fieldMap["webhook_id"] = w.WebhookID
	w.fieldMap["kind"] = w.Kind
	w.fieldMap["body"] = w.Body
}

func (w webhookDelivery) clone(db *gorm.DB) webhookDelivery {
	w.webhookDeliveryDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w webhookDelivery) replaceDB(db *gorm.DB) webhookDelivery {
	w.webhookDeliveryDo.ReplaceDB(db)
	return w
}

type webhookDeliveryDo struct{ gen.DO }

type IWebhookDeliveryDo interface {
	gen.SubQuery
	Debug() IWebhookDeliveryDo
	WithContext(ctx context.Context) IWebhookDeliveryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWebhookDeliveryDo
	WriteDB() IWebhookDeliveryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWebhookDeliveryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWebhookDeliveryDo
	Not(conds ...gen.Condition) IWebhookDeliveryDo
	Or(conds ...gen.Condition) IWebhookDeliveryDo
	Select(conds ...field.Expr) IWebhookDeliveryDo
	Where(conds ...gen.Condition) IWebhookDeliveryDo
	Order(conds ...field.Expr) IWebhookDeliveryDo
	Distinct(cols ...field.Expr) IWebhookDeliveryDo
	Omit(cols ...field.Expr) IWebhookDeliveryDo
	Join(table schema.Tabler, on ...field.Expr) IWebhookDeliveryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWebhookDeliveryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWebhookDeliveryDo
	Group(cols ...field.Expr) IWebhookDeliveryDo
	Having(conds ...gen.Condition) IWebhookDeliveryDo
	Limit(limit int) IWebhookDeliveryDo
	Offset(offset int) IWebhookDeliveryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWebhookDeliveryDo
	Unscoped() IWebhookDeliveryDo
	Create(values ...*model.WebhookDelivery) error
	CreateInBatches(values []*model.WebhookDelivery, batchSize int) error
	Save(values ...*model.WebhookDelivery) error
	First() (*model.WebhookDelivery, error)
	Take() (*model.WebhookDelivery, error)
	Last() (*model.WebhookDelivery, error)
	Find() ([]*model.WebhookDelivery, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WebhookDelivery, err error)
	FindInBatches(result *[]*model.WebhookDelivery, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WebhookDelivery) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWebhookDeliveryDo
	Assign(attrs ...field.AssignExpr) IWebhookDeliveryDo
	Joins(fields ...field.RelationField) IWebhookDeliveryDo
	Preload(fields ...field.RelationField) IWebhookDeliveryDo
	FirstOrInit() (*model.WebhookDelivery, error)
	FirstOrCreate() (*model.WebhookDelivery, error)
	FindByPage(offset int, limit int) (result []*model.WebhookDelivery, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWebhookDeliveryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w webhookDeliveryDo) Debug() IWebhookDeliveryDo {
	return w.withDO(w.DO.Debug())
}

func (w webhookDeliveryDo) WithContext(ctx context.Context) IWebhookDeliveryDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w webhookDeliveryDo) ReadDB() IWebhookDeliveryDo {
	return w.Clauses(dbresolver.Read)
}

func (w webhookDeliveryDo) WriteDB() IWebhookDeliveryDo {
	return w.Clauses(dbresolver.Write)
}

func (w webhookDeliveryDo) Session(config *gorm.Session) IWebhookDeliveryDo {
	return w.withDO(w.DO.Session(config))
}

func (w webhookDeliveryDo) Clauses(conds ...clause.Expression) IWebhookDeliveryDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w webhookDeliveryDo) Returning(value interface{}, columns ...string) IWebhookDeliveryDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w webhookDeliveryDo) Not(conds ...gen.Condition) IWebhookDeliveryDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w webhookDeliveryDo) Or(conds ...gen.Condition) IWebhookDeliveryDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w webhookDeliveryDo) Select(conds ...field.Expr) IWebhookDeliveryDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w webhookDeliveryDo) Where(conds ...gen.Condition) IWebhookDeliveryDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w webhookDeliveryDo) Order(conds ...field.Expr) IWebhookDeliveryDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w webhookDeliveryDo) Distinct(cols ...field.Expr) IWebhookDeliveryDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w webhookDeliveryDo) Omit(cols ...field.Expr) IWebhookDeliveryDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w webhookDeliveryDo) Join(table schema.Tabler, on ...field.Expr) IWebhookDeliveryDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w webhookDeliveryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWebhookDeliveryDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w webhookDeliveryDo) RightJoin(table schema.Tabler, on ...field.Expr) IWebhookDeliveryDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w webhookDeliveryDo) Group(cols ...field.Expr) IWebhookDeliveryDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w webhookDeliveryDo) Having(conds ...gen.Condition) IWebhookDeliveryDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w webhookDeliveryDo) Limit(limit int) IWebhookDeliveryDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w webhookDeliveryDo) Offset(offset int) IWebhookDeliveryDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w webhookDeliveryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWebhookDeliveryDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w webhookDeliveryDo) Unscoped() IWebhookDeliveryDo {
	return w.withDO(w.DO.Unscoped())
}

func (w webhookDeliveryDo) Create(values ...*model.WebhookDelivery) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w webhookDeliveryDo) CreateInBatches(values []*model.WebhookDelivery, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w webhookDeliveryDo) Save(values ...*model.WebhookDelivery) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w webhookDeliveryDo) First() (*model.WebhookDelivery, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebhookDelivery), nil
	}
}

func (w webhookDeliveryDo) Take() (*model.WebhookDelivery, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebhookDelivery), nil
	}
}

func (w webhookDeliveryDo) Last() (*model.WebhookDelivery, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebhookDelivery), nil
	}
}

func (w webhookDeliveryDo) Find() ([]*model.WebhookDelivery, error) {
	result, err := w.DO.Find()
	return result.([]*model.WebhookDelivery), err
}

func (w webhookDeliveryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WebhookDelivery, err error) {
	buf := make([]*model.WebhookDelivery, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w webhookDeliveryDo) FindInBatches(result *[]*model.WebhookDelivery, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w webhookDeliveryDo) Attrs(attrs ...field.AssignExpr) IWebhookDeliveryDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w webhookDeliveryDo) Assign(attrs ...field.AssignExpr) IWebhookDeliveryDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w webhookDeliveryDo) Joins(fields ...field.RelationField) IWebhookDeliveryDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w webhookDeliveryDo) Preload(fields ...field.RelationField) IWebhookDeliveryDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w webhookDeliveryDo) FirstOrInit() (*model.WebhookDelivery, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebhookDelivery), nil
	}
}

func (w webhookDeliveryDo) FirstOrCreate() (*model.WebhookDelivery, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebhookDelivery), nil
	}
}

func (w webhookDeliveryDo) FindByPage(offset int, limit int) (result []*model.WebhookDelivery, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w webhookDeliveryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w webhookDeliveryDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w webhookDeliveryDo) Delete(models ...*model.WebhookDelivery) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *webhookDeliveryDo) withDO(do gen.Dao) *webhookDeliveryDo {
	w.DO = *do.(*gen.DO)
	return w
}
