// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/olivertgwalton/photon-server/internal/store/model"
)

func newWebhook(db *gorm.DB, opts ...gen.DOOption) webhook {
	_webhook := webhook{}

	_webhook.webhookDo.UseDB(db, opts...)
	_webhook.webhookDo.UseModel(&model.Webhook{})

	tableName := _webhook.webhookDo.TableName()
	_webhook.ALL = field.NewAsterisk(tableName)
	_webhook.ID = field.NewField(tableName, "id")
	_webhook.URL = field.NewString(tableName, "url")
	_webhook.Secret = field.NewString(tableName, "secret")
	_webhook.CreatedAt = field.NewTime(tableName, "created_at")

	_webhook.fillFieldMap()

	return _webhook
}

type webhook struct {
	webhookDo webhookDo

	ALL       field.Asterisk
	ID        field.Field
	URL       field.String
	Secret    field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (w webhook) Table(newTableName string) *webhook {
	w.webhookDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w webhook) As(alias string) *webhook {
	w.webhookDo.DO = *(w.webhookDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *webhook) updateTableName(table string) *webhook {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewField(table, "id")
	w.URL = field.NewString(table, "url")
	w.Secret = field.NewString(table, "secret")
	w.CreatedAt = field.NewTime(table, "created_at")

	w.fillFieldMap()

	return w
}

func (w *webhook) WithContext(ctx context.Context) IWebhookDo { return w.webhookDo.WithContext(ctx) }

func (w webhook) TableName() string { return w.webhookDo.TableName() }

func (w webhook) Alias() string { return w.webhookDo.Alias() }

func (w webhook) Columns(cols ...field.Expr) gen.Columns { return w.webhookDo.Columns(cols...) }

func (w *webhook) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *webhook) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 4)
	w.fieldMap["id"] = w.ID
	w.fieldMap["url"] = w.URL
	w.fieldMap["secret"] = w.Secret
	w.fieldMap["created_at"] = w.CreatedAt
}

func (w webhook) clone(db *gorm.DB) webhook {
	w.webhookDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w webhook) replaceDB(db *gorm.DB) webhook {
	w.webhookDo.ReplaceDB(db)
	return w
}

type webhookDo struct{ gen.DO }

type IWebhookDo interface {
	gen.SubQuery
	Debug() IWebhookDo
	WithContext(ctx context.Context) IWebhookDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWebhookDo
	WriteDB() IWebhookDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWebhookDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWebhookDo
	Not(conds ...gen.Condition) IWebhookDo
	Or(conds ...gen.Condition) IWebhookDo
	Select(conds ...field.Expr) IWebhookDo
	Where(conds ...gen.Condition) IWebhookDo
	Order(conds ...field.Expr) IWebhookDo
	Distinct(cols ...field.Expr) IWebhookDo
	Omit(cols ...field.Expr) IWebhookDo
	Join(table schema.Tabler, on ...field.Expr) IWebhookDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWebhookDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWebhookDo
	Group(cols ...field.Expr) IWebhookDo
	Having(conds ...gen.Condition) IWebhookDo
	Limit(limit int) IWebhookDo
	Offset(offset int) IWebhookDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWebhookDo
	Unscoped() IWebhookDo
	Create(values ...*model.Webhook) error
	CreateInBatches(values []*model.Webhook, batchSize int) error
	Save(values ...*model.Webhook) error
	First() (*model.Webhook, error)
	Take() (*model.Webhook, error)
	Last() (*model.Webhook, error)
	Find() ([]*model.Webhook, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Webhook, err error)
	FindInBatches(result *[]*model.Webhook, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Webhook) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWebhookDo
	Assign(attrs ...field.AssignExpr) IWebhookDo
	Joins(fields ...field.RelationField) IWebhookDo
	Preload(fields ...field.RelationField) IWebhookDo
	FirstOrInit() (*model.Webhook, error)
	FirstOrCreate() (*model.Webhook, error)
	FindByPage(offset int, limit int) (result []*model.Webhook, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWebhookDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w webhookDo) Debug() IWebhookDo {
	return w.withDO(w.DO.Debug())
}

func (w webhookDo) WithContext(ctx context.Context) IWebhookDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w webhookDo) ReadDB() IWebhookDo {
	return w.Clauses(dbresolver.Read)
}

func (w webhookDo) WriteDB() IWebhookDo {
	return w.Clauses(dbresolver.Write)
}

func (w webhookDo) Session(config *gorm.Session) IWebhookDo {
	return w.withDO(w.DO.Session(config))
}

func (w webhookDo) Clauses(conds ...clause.Expression) IWebhookDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w webhookDo) Returning(value interface{}, columns ...string) IWebhookDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w webhookDo) Not(conds ...gen.Condition) IWebhookDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w webhookDo) Or(conds ...gen.Condition) IWebhookDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w webhookDo) Select(conds ...field.Expr) IWebhookDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w webhookDo) Where(conds ...gen.Condition) IWebhookDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w webhookDo) Order(conds ...field.Expr) IWebhookDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w webhookDo) Distinct(cols ...field.Expr) IWebhookDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w webhookDo) Omit(cols ...field.Expr) IWebhookDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w webhookDo) Join(table schema.Tabler, on ...field.Expr) IWebhookDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w webhookDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWebhookDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w webhookDo) RightJoin(table schema.Tabler, on ...field.Expr) IWebhookDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w webhookDo) Group(cols ...field.Expr) IWebhookDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w webhookDo) Having(conds ...gen.Condition) IWebhookDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w webhookDo) Limit(limit int) IWebhookDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w webhookDo) Offset(offset int) IWebhookDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w webhookDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWebhookDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w webhookDo) Unscoped() IWebhookDo {
	return w.withDO(w.DO.Unscoped())
}

func (w webhookDo) Create(values ...*model.Webhook) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w webhookDo) CreateInBatches(values []*model.Webhook, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w webhookDo) Save(values ...*model.Webhook) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w webhookDo) First() (*model.Webhook, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Webhook), nil
	}
}

func (w webhookDo) Take() (*model.Webhook, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Webhook), nil
	}
}

func (w webhookDo) Last() (*model.Webhook, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Webhook), nil
	}
}

func (w webhookDo) Find() ([]*model.Webhook, error) {
	result, err := w.DO.Find()
	return result.([]*model.Webhook), err
}

func (w webhookDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Webhook, err error) {
	buf := make([]*model.Webhook, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w webhookDo) FindInBatches(result *[]*model.Webhook, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w webhookDo) Attrs(attrs ...field.AssignExpr) IWebhookDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w webhookDo) Assign(attrs ...field.AssignExpr) IWebhookDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w webhookDo) Joins(fields ...field.RelationField) IWebhookDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w webhookDo) Preload(fields ...field.RelationField) IWebhookDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w webhookDo) FirstOrInit() (*model.Webhook, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Webhook), nil
	}
}

func (w webhookDo) FirstOrCreate() (*model.Webhook, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Webhook), nil
	}
}

func (w webhookDo) FindByPage(offset int, limit int) (result []*model.Webhook, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w webhookDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w webhookDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w webhookDo) Delete(models ...*model.Webhook) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *webhookDo) withDO(do gen.Dao) *webhookDo {
	w.DO = *do.(*gen.DO)
	return w
}
